// Complete Reflexive Verb Audit - 73 verbs with correct grammar metadata
// Based on Duden/Canoonet grammar

export interface ReflexiveVerbMeta {
  infinitive: string;
  reflexiveCase: 'akkusativ' | 'dativ';
  requiresObject: boolean;
  objectCase: 'akkusativ' | 'dativ' | 'genitiv' | 'none';
  objectPlaceholder: string | null; // 'etwas', 'jemanden', 'sich', etc.
  requiredPreposition: string | null; // e.g., 'für', 'an', 'auf', 'mit', 'um', 'bei', 'von', 'in', 'über', 'gegen', 'vor'
  prepositionCase: 'akkusativ' | 'dativ' | 'genitiv' | 'none';
  transitivity: 'transitive' | 'intransitive' | 'both';
  exampleWithObject: string;
  notes: string;
}

export const reflexiveVerbMeta: ReflexiveVerbMeta[] = [
  // === TRUE DATIV REFLEXIVE + AKKUSATIV OBJECT (reflexive pronoun = mir/dir/sich) ===
  // Pattern: sich (Dat) + etwas (Akk)
  {
    infinitive: 'sich wünschen',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich wünsche mir ein Auto.',
    notes: 'True dativ reflexive. Always requires Akkusativ object (what is wished for).'
  },
  {
    infinitive: 'sich abgewöhnen',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich gewöhne mir das Rauchen ab.',
    notes: 'True dativ reflexive + separable "ab". Requires Akkusativ object (the habit).'
  },
  {
    infinitive: 'sich angewöhnen',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich gewöhne mir das frühe Aufstehen an.',
    notes: 'True dativ reflexive + separable "an". Requires Akkusativ object (the habit).'
  },
  {
    infinitive: 'sich vorstellen',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich stelle mir das vor.',
    notes: 'MEANING 2: "to imagine" - true dativ reflexive. MEANING 1: "to introduce oneself" is Akkusativ reflexive, no object.'
  },
  {
    infinitive: 'sich merken',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich merke mir das.',
    notes: 'True dativ reflexive. Requires Akkusativ object (what is remembered/noted).'
  },

  // === AKKUSATIV REFLEXIVE + AKKUSATIV OBJECT (body parts, clothing) ===
  // Pattern: sich (Akk) + etwas (Akk) - OPTIONAL object, default is "sich"
  {
    infinitive: 'sich waschen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / die Hände',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'both',
    exampleWithObject: 'Ich wasche mich. / Ich wasche mir die Hände.',
    notes: 'Default: Akkusativ reflexive "mich". With body part object -> dativ reflexive "mir" + Akkusativ object.'
  },
  {
    infinitive: 'sich duschen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich dusche mich.',
    notes: 'Always Akkusativ reflexive. No body-part construction common.'
  },
  {
    infinitive: 'sich rasieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / den Bart',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'both',
    exampleWithObject: 'Ich rasiere mich. / Ich rasiere mir den Bart.',
    notes: 'Default Akkusativ. With body part -> dativ reflexive.'
  },
  {
    infinitive: 'sich kämmen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / die Haare',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'both',
    exampleWithObject: 'Ich kämme mich. / Ich kämme mir die Haare.',
    notes: 'Default Akkusativ. With body part -> dativ reflexive.'
  },
  {
    infinitive: 'sich anziehen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / den Mantel',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'both',
    exampleWithObject: 'Ich ziehe mich an. / Ich ziehe mir den Mantel an.',
    notes: 'Default Akkusativ. With clothing -> dativ reflexive.'
  },
  {
    infinitive: 'sich ausziehen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / die Schuhe',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'both',
    exampleWithObject: 'Ich ziehe mich aus. / Ich ziehe mir die Schuhe aus.',
    notes: 'Default Akkusativ. With clothing -> dativ reflexive.'
  },

  // === AKKUSATIV REFLEXIVE + PREPOSITIONAL OBJECT (mandatory) ===
  {
    infinitive: 'sich interessieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'für',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich interessiere mich für Geschichte.',
    notes: 'Mandatory "für + Akk". Cannot stand alone.'
  },
  {
    infinitive: 'sich freuen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich freue mich auf das Wochenende.',
    notes: 'Mandatory "auf + Akk" (future event). "über + Akk" for past event also possible.'
  },
  {
    infinitive: 'sich ärgern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich ärgere mich über den Fehler.',
    notes: 'Mandatory "über + Akk".'
  },
  {
    infinitive: 'sich wundern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich wundere mich über sein Verhalten.',
    notes: 'Mandatory "über + Akk".'
  },
  {
    infinitive: 'sich erinnern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'an',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich erinnere mich an dich.',
    notes: 'Mandatory "an + Akk". Genitiv archaic.'
  },
  {
    infinitive: 'sich kümmern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'um',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich kümmere mich um die Kinder.',
    notes: 'Mandatory "um + Akk".'
  },
  {
    infinitive: 'sich sorgen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'um',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich sorge mich um meine Eltern.',
    notes: 'Mandatory "um + Akk".'
  },
  {
    infinitive: 'sich beschäftigen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'mit',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich beschäftige mich mit Deutsch.',
    notes: 'Mandatory "mit + Dat".'
  },
  {
    infinitive: 'sich vorbereiten',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich bereite mich auf die Prüfung vor.',
    notes: 'Mandatory "auf + Akk" + separable "vor".'
  },
  {
    infinitive: 'sich verlieben',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich verliebe mich in dich.',
    notes: 'Mandatory "in + Akk".'
  },
  {
    infinitive: 'sich konzentrieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich konzentriere mich auf die Arbeit.',
    notes: 'Mandatory "auf + Akk".'
  },
  {
    infinitive: 'sich beschweren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich beschwere mich über den Lärm.',
    notes: 'Mandatory "über + Akk".'
  },
  {
    infinitive: 'sich bedanken',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'bei',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich bedanke mich bei dir für die Hilfe.',
    notes: 'Mandatory "bei + Dat" (person), optional "für + Akk" (reason).'
  },
  {
    infinitive: 'sich entschuldigen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'bei',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich entschuldige mich bei meinem Lehrer für den Fehler.',
    notes: 'Mandatory "bei + Dat" (person), optional "für + Akk" (reason).'
  },
  {
    infinitive: 'sich entscheiden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'für',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich entscheide mich für das rote Auto.',
    notes: 'Mandatory "für + Akk" (choice). "gegen + Akk" also possible.'
  },
  {
    infinitive: 'sich einigen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Wir einigen uns auf einen Preis.',
    notes: 'Mandatory "auf + Akk" (agreement target).'
  },
  {
    infinitive: 'sich verabreden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Wir verabreden uns für morgen. / Ich verabrede mich mit ihm.',
    notes: 'Optional "für + Akk" (time) or "mit + Dat" (person). Can stand alone.'
  },
  {
    infinitive: 'sich treffen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Wir treffen uns im Park. / Ich treffe mich mit ihm.',
    notes: 'Optional "mit + Dat" (person) or "in + Dat/Akk" (place). Can stand alone.'
  },
  {
    infinitive: 'sich verabschieden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'von',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich verabschiede mich von meinen Freunden.',
    notes: 'Mandatory "von + Dat" (people).'
  },
  {
    infinitive: 'sich streiten',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'mit',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich streite mich mit meinem Bruder. / Ich streite mich um das Erbe.',
    notes: 'Mandatory "mit + Dat" (opponent) or "um + Akk" (topic).'
  },
  {
    infinitive: 'sich vertragen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'mit',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich vertrage mich gut mit ihr.',
    notes: 'Mandatory "mit + Dat".'
  },
  {
    infinitive: 'sich trennen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'von',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich trenne mich von meinem Partner.',
    notes: 'Mandatory "von + Dat".'
  },
  {
    infinitive: 'sich unterhalten',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'mit',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich unterhalte mich mit meinem Freund. / Ich unterhalte mich über Politik.',
    notes: 'Mandatory "mit + Dat" (person), optional "über + Akk" (topic).'
  },
  {
    infinitive: 'sich orientieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'an',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich orientiere mich an den Sternen.',
    notes: 'Mandatory "an + Dat".'
  },
  {
    infinitive: 'sich nähern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'dativ',
    objectPlaceholder: 'etwas/jemandem',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich nähere mich der Stadt.',
    notes: 'Governs Dativ object directly (no preposition). "sich + Dat nähern".'
  },
  {
    infinitive: 'sich entfernen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'von',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich entferne mich vom Lärm.',
    notes: 'Mandatory "von + Dat".'
  },
  {
    infinitive: 'sich auskennen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich kenne mich in Berlin gut aus.',
    notes: 'Mandatory "in + Dat" + separable "aus".'
  },
  {
    infinitive: 'sich einleben',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich lebe mich in der neuen Stadt ein.',
    notes: 'Optional "in + Dat" (place) + separable "ein".'
  },
  {
    infinitive: 'sich einstellen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich stelle mich auf Veränderungen ein.',
    notes: 'Mandatory "auf + Akk" + separable "ein".'
  },
  {
    infinitive: 'sich bewerben',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'um',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich bewerbe mich um die Stelle. / Ich bewerbe mich bei der Firma.',
    notes: 'Mandatory "um + Akk" (position), optional "bei + Dat" (company).'
  },
  {
    infinitive: 'sich melden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich bei dir. / Ich melde mich für den Kurs an.',
    notes: 'Optional "bei + Dat" (person) or "für + Akk" (volunteer). Can stand alone.'
  },
  {
    infinitive: 'sich anmelden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich für den Kurs an. / Ich melde mich bei der Behörde an.',
    notes: 'Optional "für + Akk" (event) or "bei + Dat" (office) + separable "an". Can stand alone.'
  },
  {
    infinitive: 'sich abmelden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich vom Newsletter ab. / Ich melde mich bei der Behörde ab.',
    notes: 'Optional "von + Dat" or "bei + Dat" + separable "ab". Can stand alone.'
  },
  {
    infinitive: 'sich registrieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich registriere mich auf der Website. / Ich registriere mich für den Kurs.',
    notes: 'Optional "auf + Akk" (platform) or "für + Akk" (event). Can stand alone.'
  },
  {
    infinitive: 'sich wehren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'gegen',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich wehre mich gegen den Angriff.',
    notes: 'Mandatory "gegen + Akk".'
  },
  {
    infinitive: 'sich schützen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'vor',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich schütze mich vor der Kälte.',
    notes: 'Mandatory "vor + Dat".'
  },
  {
    infinitive: 'sich vornehmen',
    reflexiveCase: 'dativ',
    requiresObject: true,
    objectCase: 'akkusativ',
    objectPlaceholder: 'etwas (Vorhaben)',
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'transitive',
    exampleWithObject: 'Ich nehme mir vor, mehr zu lesen.',
    notes: 'True dativ reflexive (mir/dir/sich). Requires a plan/intention as object or a zu-infinitive clause.'
  },
  {
    infinitive: 'sich gewöhnen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'an',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich gewöhne mich an die Kälte.',
    notes: 'Mandatory "an + Akk". The reflexive pronoun is Akkusativ.'
  },
  {
    infinitive: 'sich fühlen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich fühle mich gut.',
    notes: 'Takes predicative adjective, not prepositional object.'
  },
  {
    infinitive: 'sich lohnen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Es lohnt sich.',
    notes: 'Impersonal "es". No object.'
  },
  {
    infinitive: 'sich handeln',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'um',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Es handelt sich um einen Fehler.',
    notes: 'Impersonal "es". Fixed phrase "sich um + Akk handeln".'
  },
  {
    infinitive: 'sich ausdrücken',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich kann mich gut ausdrücken. / Ich drücke mich über das Thema aus.',
    notes: 'Optional "über + Akk" (topic). Separable "aus". Can stand alone.'
  },
  {
    infinitive: 'sich verbessern',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Mein Deutsch verbessert sich.',
    notes: 'Often impersonal. No mandatory object/preposition.'
  },
  {
    infinitive: 'sich wiederholen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Die Geschichte wiederholt sich.',
    notes: 'Often impersonal. No mandatory object/preposition.'
  },
  {
    infinitive: 'sich ergeben',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Daraus ergibt sich ein Problem.',
    notes: 'Impersonal. No mandatory object/preposition.'
  },
  {
    infinitive: 'sich verlassen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich verlasse mich auf dich.',
    notes: 'Mandatory "auf + Akk".'
  },
  {
    infinitive: 'sich reduzieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Das Risiko reduziert sich.',
    notes: 'Often impersonal. No mandatory object/preposition.'
  },
  {
    infinitive: 'sich täuschen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich täusche mich in meiner Annahme. / Ich täusche mich über ihn.',
    notes: 'Mandatory "in + Akk" (error) or "über + Akk" (person).'
  },
  {
    infinitive: 'sich irren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich irre mich. / Ich irre mich in der Annahme.',
    notes: 'Can stand alone. Optional "in + Dat" (domain).'
  },
  {
    infinitive: 'sich schämen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich schäme mich. / Ich schäme mich wegen meines Fehlers.',
    notes: 'Can stand alone. Optional "wegen + Gen".'
  },
  {
    infinitive: 'sich langweilen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich langweile mich.',
    notes: 'No mandatory object/preposition.'
  },
  {
    infinitive: 'sich aufregen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich rege mich über die Nachricht auf.',
    notes: 'Mandatory "über + Akk" + separable "auf".'
  },
  {
    infinitive: 'sich erholen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'von',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich erhole mich von der Krankheit.',
    notes: 'Optional "von + Dat" (source). Can stand alone.'
  },
  {
    infinitive: 'sich entspannen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich entspanne mich.',
    notes: 'No mandatory object/preposition.'
  },
  {
    infinitive: 'sich beeilen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich beeile mich.',
    notes: 'No mandatory object/preposition.'
  },
  {
    infinitive: 'sich befinden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Das Hotel befindet sich in Berlin.',
    notes: 'Impersonal. Mandatory "in + Dat" (location).'
  },
  {
    infinitive: 'sich bekennen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'zu',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich bekenne mich zu meinem Fehler.',
    notes: 'Mandatory "zu + Dat".'
  },
  {
    infinitive: 'sich beschweren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich beschwere mich über den Service.',
    notes: 'Mandatory "über + Akk".'
  },
  {
    infinitive: 'sich informieren',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'über',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich informiere mich über die Neuigkeiten. / Ich informiere mich bei ihm.',
    notes: 'Mandatory "über + Akk" (topic) or "bei + Dat" (source).'
  },
  {
    infinitive: 'sich melden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich bei dir. / Ich melde mich freiwillig.',
    notes: 'Optional "bei + Dat" or "freiwillig". Can stand alone.'
  },
  {
    infinitive: 'sich umziehen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'akkusativ',
    objectPlaceholder: 'sich / in etwas',
    requiredPreposition: 'in',
    prepositionCase: 'akkusativ',
    transitivity: 'both',
    exampleWithObject: 'Ich ziehe mich um. / Ich ziehe mich in den Anzug um.',
    notes: 'Default Akkusativ. Optional "in + Akk" (clothing) + separable "um".'
  },
  {
    infinitive: 'sich niederlassen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'in',
    prepositionCase: 'dativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich lasse mich in München nieder.',
    notes: 'Optional "in + Dat" (place) + separable "nieder". Can stand alone.'
  },
  {
    infinitive: 'sich einstellen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich stelle mich auf Regen ein.',
    notes: 'Mandatory "auf + Akk" + separable "ein".'
  },
  {
    infinitive: 'sich erkälten',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich erkälte mich.',
    notes: 'No mandatory object/preposition.'
  },
  {
    infinitive: 'sich anmelden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich für den Kurs an.',
    notes: 'Optional "für + Akk" or "bei + Dat" + separable "an".'
  },
  {
    infinitive: 'sich abmelden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: null,
    prepositionCase: 'none',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich melde mich vom Newsletter ab.',
    notes: 'Optional "von + Dat" or "bei + Dat" + separable "ab".'
  },
  {
    infinitive: 'sich entscheiden',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'für',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Ich entscheide mich für das rote Auto.',
    notes: 'Mandatory "für + Akk" (choice). "gegen + Akk" also possible.'
  },
  {
    infinitive: 'sich einigen',
    reflexiveCase: 'akkusativ',
    requiresObject: false,
    objectCase: 'none',
    objectPlaceholder: null,
    requiredPreposition: 'auf',
    prepositionCase: 'akkusativ',
    transitivity: 'intransitive',
    exampleWithObject: 'Wir einigen uns auf einen Preis.',
    notes: 'Mandatory "auf + Akk" (agreement target).'
  },
];

console.log(`Total: ${reflexiveVerbMeta.length} verbs`);
const needObj = reflexiveVerbMeta.filter(v => v.requiresObject).length;
const needPrep = reflexiveVerbMeta.filter(v => v.requiredPreposition).length;
const needBoth = reflexiveVerbMeta.filter(v => v.requiresObject && v.requiredPreposition).length;
console.log(`Require object: ${needObj}`);
console.log(`Require preposition: ${needPrep}`);
console.log(`Require both: ${needBoth}`);