-- UPDATE synonyms and antonyms for ALL 73 reflexive verbs in public.german_verbs

UPDATE public.german_verbs SET synonyms = ARRAY['sich reinigen', 'sich säubern', 'duschen'], antonyms = ARRAY['sich beschmutzen', 'verschmutzen'] WHERE infinitive = 'sich waschen';
UPDATE public.german_verbs SET synonyms = ARRAY['duschen gehen', 'abduschen'], antonyms = ARRAY['verschmutzen'] WHERE infinitive = 'sich duschen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich scheren', 'sich rasieren'], antonyms = ARRAY['wachsen lassen'] WHERE infinitive = 'sich rasieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich frisieren', 'sich die Haare bürsten'], antonyms = ARRAY['sich verwirren', 'sich zerzausen'] WHERE infinitive = 'sich kämmen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich kleiden', 'sich einkleiden', 'sich ankleiden'], antonyms = ARRAY['sich ausziehen', 'sich entkleiden'] WHERE infinitive = 'sich anziehen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich entkleiden', 'sich auskleiden', 'ablegen'], antonyms = ARRAY['sich anziehen', 'sich bekleiden'] WHERE infinitive = 'sich ausziehen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich erhoffen', 'begehren', 'ersehnen'], antonyms = ARRAY['ablehnen', 'verweigern'] WHERE infinitive = 'sich wünschen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich anpassen', 'sich einleben', 'sich einstellen'], antonyms = ARRAY['sich entfremden', 'sich abgewöhnen'] WHERE infinitive = 'sich gewöhnen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich aneignen', 'erlernen', 'sich zulegen'], antonyms = ARRAY['sich abgewöhnen', 'aufgeben'] WHERE infinitive = 'sich angewöhnen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich entwöhnen', 'aufgeben', 'verlernen'], antonyms = ARRAY['sich angewöhnen', 'sich aneignen'] WHERE infinitive = 'sich abgewöhnen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich vergucken', 'sich verknallen', 'Zuneigung fassen'], antonyms = ARRAY['sich trennen', 'sich entlieben'] WHERE infinitive = 'sich verlieben';
UPDATE public.german_verbs SET synonyms = ARRAY['sich erfreuen', 'jubeln', 'strahlen'], antonyms = ARRAY['trauern', 'sich ärgern'] WHERE infinitive = 'sich freuen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich aufregen', 'sich empören', 'sich entrüsten'], antonyms = ARRAY['sich freuen', 'sich beruhigen'] WHERE infinitive = 'sich ärgern';
UPDATE public.german_verbs SET synonyms = ARRAY['staunen', 'sich verwundern', 'erstaunt sein'], antonyms = ARRAY['gleichgültig bleiben', 'sich nicht wundern'] WHERE infinitive = 'sich wundern';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ennuyieren', 'sich öden', 'die Zeit totschlagen'], antonyms = ARRAY['sich amüsieren', 'sich unterhalten'] WHERE infinitive = 'sich langweilen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich genieren', 'verlegen sein', 'beschämt sein'], antonyms = ARRAY['stolz sein', 'sich rühmen'] WHERE infinitive = 'sich schämen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ärgern', 'sich empören', 'sich entrüsten'], antonyms = ARRAY['sich beruhigen', 'sich entspannen'] WHERE infinitive = 'sich aufregen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ausruhen', 'relaxen', 'sich lockern'], antonyms = ARRAY['sich anspannen', 'sich aufregen'] WHERE infinitive = 'sich entspannen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ausruhen', 'sich regenerieren', 'genesen'], antonyms = ARRAY['sich verausgaben', 'sich überanstrengen'] WHERE infinitive = 'sich erholen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich entspannen', 'rasten', 'pausieren'], antonyms = ARRAY['sich anstrengen', 'arbeiten'] WHERE infinitive = 'sich ausruhen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich verkühlen', 'eine Erkältung bekommen'], antonyms = ARRAY['gesund bleiben', 'genesen'] WHERE infinitive = 'sich erkälten';
UPDATE public.german_verbs SET synonyms = ARRAY['sich sputen', 'sich ranhalten', 'sich ellen'], antonyms = ARRAY['trödeln', 'zögern'] WHERE infinitive = 'sich beeilen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich fokussieren', 'sich sammeln', 'sich vertiefen'], antonyms = ARRAY['abschweifen', 'sich ablenken'] WHERE infinitive = 'sich konzentrieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich begeistern für', 'Anteil nehmen', 'sich engagieren'], antonyms = ARRAY['gleichgültig sein', 'sich nicht kümmern'] WHERE infinitive = 'sich interessieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich befassen', 'sich abgeben', 'sich widmen'], antonyms = ARRAY['müßig sein', 'nichts tun'] WHERE infinitive = 'sich beschäftigen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich sorgen um', 'sich annehmen', 'betreuen'], antonyms = ARRAY['vernachlässigen', 'ignorieren'] WHERE infinitive = 'sich kümmern';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ängstigen', 'besorgt sein', 'sich grämen'], antonyms = ARRAY['sich entspannen', 'vertrauen'] WHERE infinitive = 'sich sorgen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich beklagen', 'reklamieren', 'murren'], antonyms = ARRAY['loben', 'sich zufriedengeben'] WHERE infinitive = 'sich beschweren';
UPDATE public.german_verbs SET synonyms = ARRAY['um Verzeihung bitten', 'sich entschuldigen bei', 'Abbitte leisten'], antonyms = ARRAY['beschuldigen', 'Vorwürfe machen'] WHERE infinitive = 'sich entschuldigen';
UPDATE public.german_verbs SET synonyms = ARRAY['Dank sagen', 'danken', 'sich erkenntlich zeigen'], antonyms = ARRAY['ignorieren', 'vergessen'] WHERE infinitive = 'sich bedanken';
UPDATE public.german_verbs SET synonyms = ARRAY['sich entschließen', 'wählen', 'sich festlegen'], antonyms = ARRAY['unentschlossen sein', 'zögern'] WHERE infinitive = 'sich entscheiden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich verständigen', 'übereinkommen', 'sich arrangieren'], antonyms = ARRAY['sich streiten', 'uneinig sein'] WHERE infinitive = 'sich einigen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich treffen', 'einen Termin ausmachen', 'sich verabreden'], antonyms = ARRAY['absagen', 'sich verspäten'] WHERE infinitive = 'sich verabreden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich begegnen', 'zusammenkommen', 'sich verabreden'], antonyms = ARRAY['sich verpassen', 'ausweichen'] WHERE infinitive = 'sich treffen';
UPDATE public.german_verbs SET synonyms = ARRAY['Abschied nehmen', 'Auf Wiedersehen sagen', 'sich empfehlen'], antonyms = ARRAY['begrüßen', 'willkommen heißen'] WHERE infinitive = 'sich verabschieden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich zanken', 'sich fetzen', 'sich krachen'], antonyms = ARRAY['sich vertragen', 'sich versöhnen'] WHERE infinitive = 'sich streiten';
UPDATE public.german_verbs SET synonyms = ARRAY['sich verstehen', 'auskommen', 'harmonieren'], antonyms = ARRAY['sich streiten', 'sich zanken'] WHERE infinitive = 'sich vertragen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich scheiden', 'sich lösen', 'auseinandergehen'], antonyms = ARRAY['sich vereinigen', 'zusammenbleiben'] WHERE infinitive = 'sich trennen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich umkleiden', 'sich frisch machen'], antonyms = ARRAY['anbehalten'] WHERE infinitive = 'sich umziehen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich bekannt machen', 'sich präsentieren', 'sich vorstellen'], antonyms = ARRAY['anonym bleiben'] WHERE infinitive = 'sich vorstellen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich rüsten', 'Vorkehrungen treffen', 'sich einstellen auf'], antonyms = ARRAY['improvisieren', 'unvorbereitet sein'] WHERE infinitive = 'sich vorbereiten';
UPDATE public.german_verbs SET synonyms = ARRAY['sich eingewöhnen', 'sich zurechtfinden', 'sich akklimatisieren'], antonyms = ARRAY['sich fremd fühlen', 'sich ausgestoßen fühlen'] WHERE infinitive = 'sich einleben';
UPDATE public.german_verbs SET synonyms = ARRAY['sich anpassen', 'sich gewöhnen', 'sich umstellen'], antonyms = ARRAY['sich widersetzen', 'beharren'] WHERE infinitive = 'sich einstellen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich zurechtfinden', 'sich informieren', 'sich auskennen'], antonyms = ARRAY['sich verirren', 'sich verlaufen'] WHERE infinitive = 'sich orientieren';
UPDATE public.german_verbs SET synonyms = ARRAY['herankommen', 'sich annähern', 'näher kommen'], antonyms = ARRAY['sich entfernen', 'weggehen'] WHERE infinitive = 'sich nähern';
UPDATE public.german_verbs SET synonyms = ARRAY['weggehen', 'sich zurückziehen', 'sich fortbewegen'], antonyms = ARRAY['sich nähern', 'sich annähern'] WHERE infinitive = 'sich entfernen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich aufhalten', 'sein', 'liegen'], antonyms = ARRAY['fehlen', 'abwesend sein'] WHERE infinitive = 'sich befinden';
UPDATE public.german_verbs SET synonyms = ARRAY['Bescheid wissen', 'sich orientieren können', 'sich auskennen'], antonyms = ARRAY['sich nicht auskennen', 'unerfahren sein'] WHERE infinitive = 'sich auskennen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich äußern', 'sich zu Wort melden', 'sich zeigen'], antonyms = ARRAY['schweigen', 'sich verstecken'] WHERE infinitive = 'sich melden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich registrieren', 'sich eintragen', 'sich einschreiben'], antonyms = ARRAY['sich abmelden', 'austragen'] WHERE infinitive = 'sich anmelden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich austragen', 'sich abkoppeln', 'kündigen'], antonyms = ARRAY['sich anmelden', 'sich eintragen'] WHERE infinitive = 'sich abmelden';
UPDATE public.german_verbs SET synonyms = ARRAY['sich anmelden', 'sich eintragen', 'sich einschreiben'], antonyms = ARRAY['sich abmelden', 'sich austragen'] WHERE infinitive = 'sich registrieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich bewerben um', 'kandidieren', 'sich bemühen um'], antonyms = ARRAY['ablehnen', 'zurückziehen'] WHERE infinitive = 'sich bewerben';
UPDATE public.german_verbs SET synonyms = ARRAY['planen', 'beabsichtigen', 'sich vornehmen'], antonyms = ARRAY['verzichten', 'aufgeben'] WHERE infinitive = 'sich vornehmen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich erneut ereignen', 'wiederkehren', 'sich wiederholen'], antonyms = ARRAY['einmalig sein', 'sich ändern'] WHERE infinitive = 'sich wiederholen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich zeigen', 'sich herausstellen', 'folgen aus'], antonyms = ARRAY['ausbleiben', 'fehlen'] WHERE infinitive = 'sich ergeben';
UPDATE public.german_verbs SET synonyms = ARRAY['sich drehen um', 'betreffen', 'gehen um'], antonyms = ARRAY['unbedeutend sein', 'irrelevant sein'] WHERE infinitive = 'sich handeln';
UPDATE public.german_verbs SET synonyms = ARRAY['sich verteidigen', 'Widerstand leisten', 'sich sträuben'], antonyms = ARRAY['sich ergeben', 'nachgeben'] WHERE infinitive = 'sich wehren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich absichern', 'sich bewahren', 'sich wappnen'], antonyms = ARRAY['sich gefährden', 'riskieren'] WHERE infinitive = 'sich schützen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich irren', 'einen Fehler machen', 'falschliegen'], antonyms = ARRAY['recht haben', 'richtigliegen'] WHERE infinitive = 'sich täuschen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich täuschen', 'falschliegen', 'auf dem Holzweg sein'], antonyms = ARRAY['recht haben', 'richtig vermuten'] WHERE infinitive = 'sich irren';
UPDATE public.german_verbs SET synonyms = ARRAY['vertrauen', 'bauen auf', 'zählen auf'], antonyms = ARRAY['misstrauen', 'anzweifeln'] WHERE infinitive = 'sich verlassen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich verringern', 'abnehmen', 'sinken'], antonyms = ARRAY['sich vergrößern', 'zunehmen'] WHERE infinitive = 'sich reduzieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich steigern', 'vorankommen', 'Fortschritte machen'], antonyms = ARRAY['sich verschlechtern', 'sich verschlimmern'] WHERE infinitive = 'sich verbessern';
UPDATE public.german_verbs SET synonyms = ARRAY['sich formulieren', 'sich artikulieren', 'sich äußern'], antonyms = ARRAY['schweigen', 'sich verstellen'] WHERE infinitive = 'sich ausdrücken';
UPDATE public.german_verbs SET synonyms = ARRAY['sich ansiedeln', 'sich sesshaft machen', 'sich niederlassen'], antonyms = ARRAY['aufbrechen', 'weiterziehen'] WHERE infinitive = 'sich niederlassen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich erkundigen', 'nachlesen', 'recherchieren'], antonyms = ARRAY['ignorieren', 'unwissend bleiben'] WHERE infinitive = 'sich informieren';
UPDATE public.german_verbs SET synonyms = ARRAY['sich beschweren', 'jammern', 'klagen'], antonyms = ARRAY['loben', 'preisen'] WHERE infinitive = 'sich beklagen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich austauschen', 'plaudern', 'konversieren'], antonyms = ARRAY['schweigen', 'sich zurückhalten'] WHERE infinitive = 'sich unterhalten';
UPDATE public.german_verbs SET synonyms = ARRAY['empfinden', 'sich befinden'], antonyms = ARRAY['gefühllos sein'] WHERE infinitive = 'sich fühlen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich rentieren', 'lohnenswert sein', 'sich bezahlt machen'], antonyms = ARRAY['sich nicht lohnen', 'unrentabel sein'] WHERE infinitive = 'sich lohnen';
UPDATE public.german_verbs SET synonyms = ARRAY['sich entsinnen', 'gedenken', 'sich ins Gedächtnis rufen'], antonyms = ARRAY['vergessen', 'verdrängen'] WHERE infinitive = 'sich erinnern';
UPDATE public.german_verbs SET synonyms = ARRAY['Platz nehmen', 'sich hinsetzen', 'sich niedersetzen'], antonyms = ARRAY['aufstehen', 'stehen'] WHERE infinitive = 'sich setzen';
