// COMPLETE Reflexive Verb Audit — All 73 verbs from database
// Based on Duden/Canoonet grammar

export interface ReflexiveVerbMeta {
  infinitive: string;
  reflexiveCase: 'akkusativ' | 'dativ';
  requiresObject: boolean;
  objectCase: 'akkusativ' | 'dativ' | 'genitiv' | 'none';
  objectPlaceholder: string | null;
  requiredPreposition: string | null;
  prepositionCase: 'akkusativ' | 'dativ' | 'genitiv' | 'none';
  transitivity: 'transitive' | 'intransitive' | 'both';
  exampleWithObject: string;
  notes: string;
}

export const reflexiveVerbMeta: ReflexiveVerbMeta[] = [
  {
    "infinitive": "sich wünschen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich wünsche mir ein Auto.",
    "notes": "True dativ reflexive. Requires Akkusativ object (what is wished for)."
  },
  {
    "infinitive": "sich abgewöhnen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich gewöhne mir das Rauchen ab.",
    "notes": "True dativ reflexive + separable \"ab\". Requires Akkusativ object (the habit)."
  },
  {
    "infinitive": "sich angewöhnen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich gewöhne mir das frühe Aufstehen an.",
    "notes": "True dativ reflexive + separable \"an\". Requires Akkusativ object (the habit)."
  },
  {
    "infinitive": "sich vorstellen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich stelle mir das vor.",
    "notes": "MEANING 2: \"to imagine\" - true dativ reflexive. MEANING 1: \"to introduce oneself\" is Akkusativ, no object."
  },
  {
    "infinitive": "sich waschen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich / die Hände",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "both",
    "exampleWithObject": "Ich wasche mich. / Ich wasche mir die Hände.",
    "notes": "Default: Akkusativ reflexive \"mich\". With body part -> dativ reflexive \"mir\" + Akkusativ object."
  },
  {
    "infinitive": "sich duschen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich dusche mich.",
    "notes": "Always Akkusativ reflexive. No body-part construction common."
  },
  {
    "infinitive": "sich rasieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich / den Bart",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "both",
    "exampleWithObject": "Ich rasiere mich. / Ich rasiere mir den Bart.",
    "notes": "Default Akkusativ. With body part -> dativ reflexive."
  },
  {
    "infinitive": "sich kämmen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich / die Haare",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "both",
    "exampleWithObject": "Ich kämme mich. / Ich kämme mir die Haare.",
    "notes": "Default Akkusativ. With body part -> dativ reflexive."
  },
  {
    "infinitive": "sich anziehen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich / den Mantel",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "both",
    "exampleWithObject": "Ich ziehe mich an. / Ich ziehe mir den Mantel an.",
    "notes": "Default Akkusativ. With clothing -> dativ reflexive."
  },
  {
    "infinitive": "sich ausziehen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "akkusativ",
    "objectPlaceholder": "sich / die Schuhe",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "both",
    "exampleWithObject": "Ich ziehe mich aus. / Ich ziehe mir die Schuhe aus.",
    "notes": "Default Akkusativ. With clothing -> dativ reflexive."
  },
  {
    "infinitive": "sich interessieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "für",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich interessiere mich für Geschichte.",
    "notes": "Mandatory \"für + Akk\". Cannot stand alone."
  },
  {
    "infinitive": "sich freuen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich freue mich auf das Wochenende.",
    "notes": "Mandatory \"auf + Akk\" (future event). \"über + Akk\" for past event also possible."
  },
  {
    "infinitive": "sich ärgern",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich ärgere mich über den Fehler.",
    "notes": "Mandatory \"über + Akk\"."
  },
  {
    "infinitive": "sich wundern",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich wundere mich über sein Verhalten.",
    "notes": "Mandatory \"über + Akk\"."
  },
  {
    "infinitive": "sich erinnern",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "an",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich erinnere mich an dich.",
    "notes": "Mandatory \"an + Akk\". Genitiv archaic."
  },
  {
    "infinitive": "sich kümmern",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "um",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich kümmere mich um die Kinder.",
    "notes": "Mandatory \"um + Akk\"."
  },
  {
    "infinitive": "sich sorgen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "um",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich sorge mich um meine Eltern.",
    "notes": "Mandatory \"um + Akk\"."
  },
  {
    "infinitive": "sich beschäftigen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "mit",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich beschäftige mich mit Deutsch.",
    "notes": "Mandatory \"mit + Dat\"."
  },
  {
    "infinitive": "sich vorbereiten",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich bereite mich auf die Prüfung vor.",
    "notes": "Mandatory \"auf + Akk\" + separable \"vor\"."
  },
  {
    "infinitive": "sich konzentrieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich konzentriere mich auf die Arbeit.",
    "notes": "Mandatory \"auf + Akk\"."
  },
  {
    "infinitive": "sich beschweren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich beschwere mich über den Lärm.",
    "notes": "Mandatory \"über + Akk\"."
  },
  {
    "infinitive": "sich bedanken",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "bei",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich bedanke mich bei dir für die Hilfe.",
    "notes": "Mandatory \"bei + Dat\" (person), optional \"für + Akk\" (reason)."
  },
  {
    "infinitive": "sich entschuldigen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "bei",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich entschuldige mich bei meinem Lehrer für den Fehler.",
    "notes": "Mandatory \"bei + Dat\" (person), optional \"für + Akk\" (reason)."
  },
  {
    "infinitive": "sich entscheiden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "für",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich entscheide mich für das rote Auto.",
    "notes": "Mandatory \"für + Akk\" (choice). \"gegen + Akk\" also possible."
  },
  {
    "infinitive": "sich einigen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Wir einigen uns auf einen Preis.",
    "notes": "Mandatory \"auf + Akk\" (agreement target)."
  },
  {
    "infinitive": "sich verabschieden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "von",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich verabschiede mich von meinen Freunden.",
    "notes": "Mandatory \"von + Dat\" (people)."
  },
  {
    "infinitive": "sich streiten",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "mit",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich streite mich mit meinem Bruder. / Ich streite mich um das Erbe.",
    "notes": "Mandatory \"mit + Dat\" (opponent) or \"um + Akk\" (topic)."
  },
  {
    "infinitive": "sich vertragen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "mit",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich vertrage mich gut mit ihr.",
    "notes": "Mandatory \"mit + Dat\"."
  },
  {
    "infinitive": "sich trennen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "von",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich trenne mich von meinem Partner.",
    "notes": "Mandatory \"von + Dat\"."
  },
  {
    "infinitive": "sich orientieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "an",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich orientiere mich an den Sternen.",
    "notes": "Mandatory \"an + Dat\"."
  },
  {
    "infinitive": "sich einleben",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich lebe mich in der neuen Stadt ein.",
    "notes": "Optional \"in + Dat\" (place) + separable \"ein\"."
  },
  {
    "infinitive": "sich einstellen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich stelle mich auf Veränderungen ein.",
    "notes": "Mandatory \"auf + Akk\" + separable \"ein\"."
  },
  {
    "infinitive": "sich bewerben",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "um",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich bewerbe mich um die Stelle. / Ich bewerbe mich bei der Firma.",
    "notes": "Mandatory \"um + Akk\" (position), optional \"bei + Dat\" (company)."
  },
  {
    "infinitive": "sich auskennen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich kenne mich in Berlin gut aus.",
    "notes": "Mandatory \"in + Dat\" + separable \"aus\"."
  },
  {
    "infinitive": "sich nähern",
    "reflexiveCase": "akkusativ",
    "requiresObject": true,
    "objectCase": "dativ",
    "objectPlaceholder": "etwas/jemandem",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich nähere mich der Stadt.",
    "notes": "Governs Dativ object directly (no preposition). \"sich + Dat nähern\"."
  },
  {
    "infinitive": "sich entfernen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "von",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich entferne mich vom Lärm.",
    "notes": "Mandatory \"von + Dat\"."
  },
  {
    "infinitive": "sich verabreden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Wir verabreden uns für morgen. / Ich verabrede mich mit ihm.",
    "notes": "Optional \"für + Akk\" (time) or \"mit + Dat\" (person). Can stand alone."
  },
  {
    "infinitive": "sich melden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich melde mich bei dir. / Ich melde mich für den Kurs an.",
    "notes": "Optional \"bei + Dat\" (person) or \"für + Akk\" (volunteer). Can stand alone."
  },
  {
    "infinitive": "sich erholen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "von",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich erhole mich. / Ich erhole mich von der Krankheit.",
    "notes": "Optional \"von + Dat\". Can stand alone."
  },
  {
    "infinitive": "sich entspannen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich entspanne mich.",
    "notes": "Can stand alone. No preposition required."
  },
  {
    "infinitive": "sich beeilen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich beeile mich.",
    "notes": "No preposition. Can stand alone."
  },
  {
    "infinitive": "sich aufregen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich rege mich über die Nachricht auf.",
    "notes": "Optional \"über + Akk\". Can stand alone: \"Ich rege mich auf.\""
  },
  {
    "infinitive": "sich abmelden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich melde mich ab.",
    "notes": "Pure reflexive + separable \"ab\". Can take \"von/bei + Dat\" optionally."
  },
  {
    "infinitive": "sich anmelden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich melde mich an.",
    "notes": "Pure reflexive + separable \"an\". Can take \"für + Akk\" or \"bei + Dat\" optionally."
  },
  {
    "infinitive": "sich befinden",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Das Hotel befindet sich in Berlin.",
    "notes": "Impersonal. Requires location \"in + Dat\"."
  },
  {
    "infinitive": "sich beklagen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich beklage mich über die schlechte Qualität.",
    "notes": "Synonym to sich beschweren. \"über + Akk\" mandatory."
  },
  {
    "infinitive": "sich ergeben",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Daraus ergibt sich ein Problem.",
    "notes": "Impersonal. No object/preposition."
  },
  {
    "infinitive": "sich fühlen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich fühle mich gut.",
    "notes": "Pure reflexive + predicative adjective. No prepositional object."
  },
  {
    "infinitive": "sich handeln",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "um",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Es handelt sich um einen Fehler.",
    "notes": "Impersonal \"es\". Fixed phrase \"sich um + Akk handeln\"."
  },
  {
    "infinitive": "sich irren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich irre mich.",
    "notes": "Can stand alone. Optional \"in + Dat\" (domain)."
  },
  {
    "infinitive": "sich langweilen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich langweile mich.",
    "notes": "Pure reflexive. No object/preposition."
  },
  {
    "infinitive": "sich lohnen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Es lohnt sich.",
    "notes": "Impersonal \"es\". Pure reflexive."
  },
  {
    "infinitive": "sich reduzieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Das Risiko reduziert sich.",
    "notes": "Often impersonal. No object/preposition."
  },
  {
    "infinitive": "sich registrieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich registriere mich.",
    "notes": "Can stand alone. Optional \"auf + Akk\" or \"für + Akk\"."
  },
  {
    "infinitive": "sich schämen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich schäme mich.",
    "notes": "Can stand alone. Optional \"wegen + Gen\"."
  },
  {
    "infinitive": "sich schützen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "vor",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich schütze mich vor der Kälte.",
    "notes": "Mandatory \"vor + Dat\" (threat)."
  },
  {
    "infinitive": "sich setzen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich setze mich. / Ich setze mich auf den Stuhl.",
    "notes": "Default no prep. Optional \"auf + Akk\" (location)."
  },
  {
    "infinitive": "sich verbessern",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Mein Deutsch verbessert sich.",
    "notes": "Often impersonal. No object/preposition."
  },
  {
    "infinitive": "sich wehren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "gegen",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich wehre mich gegen den Angriff.",
    "notes": "Mandatory \"gegen + Akk\"."
  },
  {
    "infinitive": "sich wiederholen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Die Geschichte wiederholt sich.",
    "notes": "Often impersonal. No object/preposition."
  },
  {
    "infinitive": "sich ausdrücken",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich kann mich gut ausdrücken.",
    "notes": "Can stand alone. Optional \"über + Akk\" (topic). Separable \"aus\"."
  },
  {
    "infinitive": "sich ausruhen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich ruhe mich aus.",
    "notes": "Pure reflexive + separable \"aus\". No preposition needed."
  },
  {
    "infinitive": "sich erkälten",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": "sich",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich erkälte mich.",
    "notes": "Pure reflexive. No object/preposition."
  },
  {
    "infinitive": "sich gewöhnen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": "an",
    "prepositionCase": "akkusativ",
    "transitivity": "transitive",
    "exampleWithObject": "Ich gewöhne mir das an. / Ich gewöhne mich an den Lärm.",
    "notes": "True dativ reflexive + \"an + Akk\". Both \"mir\" and \"mich\" possible."
  },
  {
    "infinitive": "sich informieren",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "über",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich informiere mich über die Neuigkeiten.",
    "notes": "Mandatory \"über + Akk\" (topic). Optional \"bei + Dat\" (source)."
  },
  {
    "infinitive": "sich niederlassen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich lasse mich in München nieder.",
    "notes": "Optional \"in + Dat\" (place). Separable \"nieder\"."
  },
  {
    "infinitive": "sich umziehen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich ziehe mich um.",
    "notes": "Pure reflexive + separable \"um\". Can take \"in + Akk\" (clothing)."
  },
  {
    "infinitive": "sich vornehmen",
    "reflexiveCase": "dativ",
    "requiresObject": true,
    "objectCase": "akkusativ",
    "objectPlaceholder": "etwas",
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "transitive",
    "exampleWithObject": "Ich nehme mir vor, mehr zu lesen.",
    "notes": "True dativ reflexive pattern! \"mir\" (Dat) + Akkusativ clause. Separable \"vor\"."
  },
  {
    "infinitive": "sich verlassen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "auf",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich verlasse mich auf dich.",
"notes": "Mandatory \"auf + Akk\" (person/thing relied on)."
  },
  {
    "infinitive": "sich täuschen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich täusche mich in meiner Annahme.",
    "notes": "Mandatory \"in + Akk\" (error). Can take \"über + Akk\" (person)."
  },
  {
    "infinitive": "sich verlieben",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "in",
    "prepositionCase": "akkusativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich verliebe mich in dich.",
    "notes": "Mandatory \"in + Akk\"."
  },
  {
    "infinitive": "sich treffen",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": null,
    "prepositionCase": "none",
    "transitivity": "intransitive",
    "exampleWithObject": "Wir treffen uns im Park. / Ich treffe mich mit ihm.",
    "notes": "Optional \"mit + Dat\" (person) or \"in + Dat/Akk\" (place). Can stand alone."
  },
  {
    "infinitive": "sich unterhalten",
    "reflexiveCase": "akkusativ",
    "requiresObject": false,
    "objectCase": "none",
    "objectPlaceholder": null,
    "requiredPreposition": "mit",
    "prepositionCase": "dativ",
    "transitivity": "intransitive",
    "exampleWithObject": "Ich unterhalte mich mit meinem Freund. / Ich unterhalte mich über Politik.",
    "notes": "Mandatory \"mit + Dat\" (person), optional \"über + Akk\" (topic)."
  }
];
