// A1 German Verbs — Essential everyday verbs
import type { VerbEntry } from './types'

export const a1Verbs: VerbEntry[] = [
  // === SEIN / HABEN / WERDEN (Auxiliary) ===
  { infinitive: 'sein', en: 'to be', ar: 'يكون', fr: 'être', level: 'A1', freq: 'very_common', type: 'auxiliary', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gewesen', ipa: '/zaɪn/', syn: ['existieren', 'vorhanden sein'], ant: ['nicht sein', 'fehlen'], tags: ['essential', 'auxiliary', 'daily_life'] },
  { infinitive: 'haben', en: 'to have', ar: 'يملك', fr: 'avoir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gehabt', ipa: '/ˈhaːbən/', syn: ['besitzen', 'verfügen'], ant: ['entbehren', 'nicht haben'], tags: ['essential', 'auxiliary', 'daily_life'] },
  { infinitive: 'werden', en: 'to become', ar: 'يصبح', fr: 'devenir', level: 'A1', freq: 'very_common', type: 'auxiliary', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'geworden', ipa: '/ˈvɛʁdən/', syn: ['entwickeln', 'wachsen'], ant: ['bleiben', 'stagnieren'], tags: ['essential', 'auxiliary', 'change'] },

  // === MODAL VERBS ===
  { infinitive: 'können', en: 'can, to be able', ar: 'يستطيع', fr: 'pouvoir', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gekonnt', ipa: '/ˈkœnən/', syn: ['vermögen', 'imstande sein'], ant: ['nicht können', 'müssen'], tags: ['modal', 'essential'] },
  { infinitive: 'müssen', en: 'must, to have to', ar: 'يجب', fr: 'devoir', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemusst', ipa: '/ˈmʏsən/', syn: ['sollen', 'gezwungen sein'], ant: ['dürfen', 'können'], tags: ['modal', 'essential'] },
  { infinitive: 'dürfen', en: 'may, to be allowed', ar: 'يسمح', fr: 'avoir le droit', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gedurft', ipa: '/ˈdʏʁfən/', syn: ['erlaubt sein', 'gestattet sein'], ant: ['verboten sein', 'müssen'], tags: ['modal', 'essential'] },
  { infinitive: 'sollen', en: 'should, ought to', ar: 'ينبغي', fr: 'devoir', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesollt', ipa: '/ˈzɔlən/', syn: ['müssen', 'verpflichtet sein'], ant: ['dürfen', 'können'], tags: ['modal', 'essential'] },
  { infinitive: 'wollen', en: 'to want', ar: 'يريد', fr: 'vouloir', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gewollt', ipa: '/ˈvɔlən/', syn: ['wünschen', 'beabsichtigen'], ant: ['ablehnen', 'verweigern'], tags: ['modal', 'essential'] },
  { infinitive: 'mögen', en: 'to like', ar: 'يحب', fr: 'aimer', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemocht', ipa: '/ˈmøːɡən/', syn: ['lieben', 'gern haben'], ant: ['hassen', 'nicht mögen'], tags: ['modal', 'feelings'] },

  // === REGULAR VERBS ===
  { infinitive: 'lernen', en: 'to learn', ar: 'يتعلم', fr: 'apprendre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gelernt', ipa: '/ˈlɛʁnən/', syn: ['pauken', 'studieren', 'sich bilden'], ant: ['vergessen', 'verlernen'], tags: ['education', 'school', 'daily_life'] },
  { infinitive: 'kaufen', en: 'to buy', ar: 'يشتري', fr: 'acheter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gekauft', ipa: '/ˈkaʊfən/', syn: ['erwerben', 'einkaufen', 'besorgen'], ant: ['verkaufen', 'abgeben'], tags: ['shopping', 'daily_life'] },
  { infinitive: 'verkaufen', en: 'to sell', ar: 'يبيع', fr: 'vendre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'verkauft', ipa: '/fɛʁˈkaʊfən/', syn: ['anbieten', 'veräußern', 'abgeben'], ant: ['kaufen', 'erwerben'], tags: ['shopping', 'business'] },
  { infinitive: 'sagen', en: 'to say', ar: 'يقول', fr: 'dire', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesagt', ipa: '/ˈzaːɡən/', syn: ['sprechen', 'äußern', 'mitteilen'], ant: ['schweigen', 'verschweigen'], tags: ['communication', 'daily_life'] },
  { infinitive: 'machen', en: 'to make, to do', ar: 'يفعل', fr: 'faire', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemacht', ipa: '/ˈmaxən/', ant: ['lassen', 'unterlassen'], tags: ['daily_life', 'action', 'essential'] },
  { infinitive: 'arbeiten', en: 'to work', ar: 'يعمل', fr: 'travailler', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gearbeitet', ipa: '/ˈaʁbaɪtən/', syn: ['tätig sein', 'schaffen', 'jobben'], ant: ['faulenzen', 'ausruhen', 'pausieren'], tags: ['work', 'profession', 'daily_life'] },
  { infinitive: 'wohnen', en: 'to live, reside', ar: 'يسكن', fr: 'habiter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gewohnt', ipa: '/ˈvoːnən/', syn: ['leben', 'sich aufhalten'], ant: ['umziehen', 'wegziehen', 'reisen'], tags: ['home', 'living', 'daily_life'] },
  { infinitive: 'spielen', en: 'to play', ar: 'يلعب', fr: 'jouer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gespielt', ipa: '/ˈʃpiːlən/', syn: ['sich vergnügen', 'tollen'], ant: ['arbeiten', 'lernen'], tags: ['free_time', 'sports', 'fun'] },
  { infinitive: 'brauchen', en: 'to need', ar: 'يحتاج', fr: 'avoir besoin de', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebraucht', ipa: '/ˈbʁaʊxən/', syn: ['benötigen', 'nötig haben'], ant: ['entbehren', 'verzichten'], tags: ['daily_life', 'essential'] },
  { infinitive: 'suchen', en: 'to search, look for', ar: 'يبحث', fr: 'chercher', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesucht', ipa: '/ˈzuːxən/', syn: ['forschen', 'nachgehen'], ant: ['finden', 'entdecken'], tags: ['daily_life', 'action'] },
  { infinitive: 'finden', en: 'to find', ar: 'يجد', fr: 'trouver', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gefunden', ipa: '/ˈfɪndən/', syn: ['entdecken', 'auffinden'], ant: ['suchen', 'verlieren', 'übersehen'], tags: ['daily_life', 'essential'] },
  { infinitive: 'geben', en: 'to give', ar: 'يعطي', fr: 'donner', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'dativ', aux: 'haben', p2: 'gegeben', ipa: '/ˈɡeːbən/', syn: ['schenken', 'reichen', 'überreichen'], ant: ['nehmen', 'erhalten', 'bekommen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'nehmen', en: 'to take', ar: 'يأخذ', fr: 'prendre', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'genommen', ipa: '/ˈneːmən/', syn: ['greifen', 'ergreifen', 'sich bedienen'], ant: ['geben', 'reichen', 'liefern'], tags: ['actions', 'daily_life'] },
  { infinitive: 'kommen', en: 'to come', ar: 'يأتي', fr: 'venir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gekommen', ipa: '/ˈkɔmən/', syn: ['eintreffen', 'ankommen', 'herkommen'], ant: ['gehen', 'fahren', 'weggehen'], tags: ['movement', 'essential'] },
  { infinitive: 'gehen', en: 'to go', ar: 'يذهب', fr: 'aller', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gegangen', ipa: '/ˈɡeːən/', syn: ['laufen', 'spazieren'], ant: ['kommen', 'bleiben', 'stehen'], tags: ['movement', 'essential'] },
  { infinitive: 'essen', en: 'to eat', ar: 'يأكل', fr: 'manger', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gegessen', ipa: '/ˈɛsən/', syn: ['speisen', 'sich ernähren', 'fressen'], ant: ['fasten', 'hungern', 'auslassen'], tags: ['food', 'daily_life'] },
  { infinitive: 'trinken', en: 'to drink', ar: 'يشرب', fr: 'boire', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'getrunken', ipa: '/ˈtʁɪŋkən/', syn: ['schlucken', 'nippen'], ant: ['hungern', 'dürsten'], tags: ['food', 'daily_life'] },
  { infinitive: 'schlafen', en: 'to sleep', ar: 'ينام', fr: 'dormir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geschlafen', ipa: '/ˈʃlaːfən/', syn: ['ruhen', 'dösen', 'schlummern'], ant: ['wachen', 'aufwachen', 'wachen'], tags: ['daily_life', 'health'] },
  { infinitive: 'lesen', en: 'to read', ar: 'يقرأ', fr: 'lire', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gelesen', ipa: '/ˈleːzən/', syn: ['durchlesen', 'sich durchlesen', 'studieren'], ant: ['schreiben', 'überspringen'], tags: ['education', 'free_time'] },
  { infinitive: 'schreiben', en: 'to write', ar: 'يكتب', fr: 'écrire', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geschrieben', ipa: '/ˈʃʁaɪbən/', syn: ['notieren', 'verfassen', 'aufschreiben'], ant: ['lesen', 'löschen'], tags: ['education', 'communication'] },
  { infinitive: 'sprechen', en: 'to speak', ar: 'يتكلم', fr: 'parler', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesprochen', ipa: '/ˈʃpʁɛçən/', syn: ['reden', 'sich unterhalten', 'plaudern'], ant: ['schweigen', 'verstummen'], tags: ['communication', 'essential'] },
  { infinitive: 'sehen', en: 'to see', ar: 'يرى', fr: 'voir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesehen', ipa: '/ˈzeːən/', syn: ['erblicken', 'schauen', 'gucken'], ant: ['übersehen', 'blinzeln', 'ignorieren'], tags: ['senses', 'daily_life'] },
  { infinitive: 'hören', en: 'to hear', ar: 'يسمع', fr: 'entendre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gehört', ipa: '/ˈhøːʁən/', syn: ['lauschen', 'zuhören', 'vernehmen'], ant: ['ignorieren', 'überhören'], tags: ['senses', 'communication'] },
  { infinitive: 'verstehen', en: 'to understand', ar: 'يفهم', fr: 'comprendre', level: 'A1', freq: 'very_common', type: 'inseparable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'verstanden', ipa: '/fɛʁˈʃteːən/', syn: ['begreifen', 'kapieren', 'nachvollziehen'], ant: ['missverstehen', 'nicht verstehen'], tags: ['education', 'communication'] },
  { infinitive: 'heißen', en: 'to be called', ar: 'يدعى', fr: 's\'appeler', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geheißen', ipa: '/ˈhaɪsən/', syn: ['genannt werden', 'bekannt sein als'], ant: ['unbekannt sein'], tags: ['introduction', 'daily_life'] },
  { infinitive: 'wohnen', en: 'to live, reside', ar: 'يسكن', fr: 'habiter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gewohnt', ipa: '/ˈvoːnən/', syn: ['leben', 'sich aufhalten', 'hausen'], ant: ['umziehen', 'wegziehen'], tags: ['home', 'daily_life'] },
  { infinitive: 'lieben', en: 'to love', ar: 'يحب', fr: 'aimer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geliebt', ipa: '/ˈliːbən/', syn: ['vergöttern', 'anbeten', 'verehren'], ant: ['hassen', 'verabscheuen'], tags: ['feelings', 'relationships'] },
  { infinitive: 'hassen', en: 'to hate', ar: 'يكره', fr: 'haïr', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gehasst', ipa: '/ˈhasən/', syn: ['verabscheuen', 'nicht ausstehen'], ant: ['lieben', 'mögen', 'verehren'], tags: ['feelings', 'relationships'] },
  { infinitive: 'fragen', en: 'to ask', ar: 'يسأل', fr: 'demander', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gefragt', ipa: '/ˈfʁaːɡən/', syn: ['nachfragen', 'erkundigen', 'befragen'], ant: ['antworten', 'erwidern'], tags: ['communication', 'education'] },
  { infinitive: 'antworten', en: 'to answer', ar: 'يجيب', fr: 'répondre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'geantwortet', ipa: '/ˈantvɔʁtən/', syn: ['erwidern', 'reagieren', 'entgegnen'], ant: ['fragen', 'schweigen'], tags: ['communication', 'education'] },
  { infinitive: 'zahlen', en: 'to pay', ar: 'يدفع', fr: 'payer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'bezahlt', ipa: '/ˈtsaːlən/', syn: ['bezahlen', 'begleichen'], ant: ['kassieren', 'schulden'], tags: ['money', 'shopping'] },
  { infinitive: 'offnen', en: 'to open', ar: 'يفتح', fr: 'ouvrir', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geoffnet', ipa: '/ˈœfnən/', syn: ['aufmachen', 'aufsperren'], ant: ['schließen', 'zumachen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'schließen', en: 'to close', ar: 'يغلق', fr: 'fermer', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geschlossen', ipa: '/ˈʃliːsən/', syn: ['zumachen', 'versperren'], ant: ['öffnen', 'aufmachen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'öffnen', en: 'to open', ar: 'يفتح', fr: 'ouvrir', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geöffnet', ipa: '/ˈœfnən/', syn: ['aufmachen', 'aufsperren', 'eröffnen'], ant: ['schließen', 'zumachen', 'versperren'], tags: ['actions', 'daily_life'] },
  { infinitive: 'putzen', en: 'to clean', ar: 'ينظف', fr: 'nettoyer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geputzt', ipa: '/ˈpʊtsən/', syn: ['reinigen', 'säubern', 'wischen'], ant: ['verschmutzen', 'beschmutzen'], tags: ['housework', 'daily_life'] },
  { infinitive: 'kochen', en: 'to cook', ar: 'يطبخ', fr: 'cuisiner', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gekocht', ipa: '/ˈkɔxən/', syn: ['zubereiten', 'braten', 'kochen'], ant: ['bestellen', 'essen gehen'], tags: ['food', 'housework'] },
  { infinitive: 'backen', en: 'to bake', ar: 'يخبز', fr: 'cuire au four', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebacken', ipa: '/ˈbakən/', syn: ['braten', 'rösten', 'zubereiten'], ant: ['kochen', 'braten'], tags: ['food', 'cooking'] },
  { infinitive: 'träumen', en: 'to dream', ar: 'يحلم', fr: 'rêver', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geträumt', ipa: '/ˈtʁɔʏmən/', syn: ['fantasieren', 'hoffen'], ant: ['realisieren', 'erwachen'], tags: ['feelings', 'daily_life'] },
  { infinitive: 'tanzen', en: 'to dance', ar: 'يرقص', fr: 'danser', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'getanzt', ipa: '/ˈtantsən/', syn: ['hüpfen', 'springen', 'sich bewegen'], ant: ['stehen', 'sitzen', 'ruhen'], tags: ['free_time', 'sports'] },
  { infinitive: 'reisen', en: 'to travel', ar: 'يسافر', fr: 'voyager', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gereist', ipa: '/ˈʁaɪzən/', syn: ['verreisen', 'unterwegs sein', 'eine Reise machen'], ant: ['bleiben', 'daheim bleiben'], tags: ['travel', 'free_time'] },
  { infinitive: 'wandern', en: 'to hike', ar: 'يتجول', fr: 'randonner', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gewandert', ipa: '/ˈvandɐn/', syn: ['gehen', 'spazieren', 'laufen'], ant: ['bleiben', 'rasten'], tags: ['free_time', 'nature'] },
  { infinitive: 'schwimmen', en: 'to swim', ar: 'يسبح', fr: 'nager', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'geschwommen', ipa: '/ˈʃvɪmən/', syn: ['wasserratten', 'tauchen', 'planschen'], ant: ['sinken', 'untergehen'], tags: ['sports', 'free_time'] },
  { infinitive: 'fahren', en: 'to drive, go by', ar: 'يقود', fr: 'conduire', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gefahren', ipa: '/ˈfaːʁən/', syn: ['lenken', 'steuern', 'kutschieren'], ant: ['gehen', 'laufen', 'fliegen'], tags: ['travel', 'transportation'] },
  { infinitive: 'laufen', en: 'to run, walk', ar: 'يجري', fr: 'courir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gelaufen', ipa: '/ˈlaʊfən/', syn: ['rennen', 'sprinten', 'eilen'], ant: ['gehen', 'stehen', 'sitzen'], tags: ['sports', 'movement'] },
  { infinitive: 'fliegen', en: 'to fly', ar: 'يطير', fr: 'voler', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'geflogen', ipa: '/ˈfliːɡən/', syn: ['schweben', 'gleiten', 'sich in die Luft erheben'], ant: ['landen', 'abstürzen'], tags: ['travel', 'movement'] },
  { infinitive: 'bleiben', en: 'to stay, remain', ar: 'يبقى', fr: 'rester', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'geblieben', ipa: '/ˈblaɪbən/', syn: ['verweilen', 'sich aufhalten', 'ausharren'], ant: ['gehen', 'verreisen', 'weggehen'], tags: ['daily_life', 'essential'] },
  { infinitive: 'sitzen', en: 'to sit', ar: 'يجلس', fr: 'être assis', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gesessen', ipa: '/ˈzɪtsən/', syn: ['hocken', 'platznehmen', 'thronen'], ant: ['stehen', 'liegen', 'laufen'], tags: ['daily_life', 'position'] },
  { infinitive: 'stehen', en: 'to stand', ar: 'يقف', fr: 'être debout', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gestanden', ipa: '/ˈʃteːən/', syn: ['aufrecht sein', 'sich befinden'], ant: ['sitzen', 'liegen', 'fallen'], tags: ['daily_life', 'position'] },
  { infinitive: 'liegen', en: 'to lie, be located', ar: 'يكمن', fr: 'être couché', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gelegen', ipa: '/ˈliːɡən/', syn: ['sich befinden', 'ruhen', 'ausgestreckt sein'], ant: ['stehen', 'sitzen', 'aufrecht sein'], tags: ['position', 'daily_life'] },
  { infinitive: 'fallen', en: 'to fall', ar: 'يسقط', fr: 'tomber', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gefallen', ipa: '/ˈfalən/', ant: ['stehen', 'aufstehen', 'steigen'], tags: ['movement', 'daily_life'] },

  // === SEPARABLE PREFIX VERBS ===
  { infinitive: 'aufstehen', en: 'to get up', ar: 'يستيقظ', fr: 'se lever', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'aufgestanden', sep: 'auf', ipa: '/ˈaʊfʃteːən/', syn: ['aufwachen', 'erwachen', 'hochkommen'], ant: ['schlafen', 'liegen bleiben', 'sich hinlegen'], tags: ['morning_routine', 'daily_life'] },
  { infinitive: 'aufmachen', en: 'to open', ar: 'يفتح', fr: 'ouvrir', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'aufgemacht', sep: 'auf', ipa: '/ˈaʊfmakən/', syn: ['öffnen', 'aufsperren'], ant: ['zumachen', 'schließen'], tags: ['daily_life', 'actions'] },
  { infinitive: 'zumachen', en: 'to close, shut', ar: 'يغلق', fr: 'fermer', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'zugemacht', sep: 'zu', ipa: '/ˈtsuːmakən/', syn: ['schließen', 'versperren', 'verriegeln'], ant: ['aufmachen', 'öffnen'], tags: ['daily_life', 'actions'] },
  { infinitive: 'einkaufen', en: 'to shop', ar: 'يتسوق', fr: 'faire des courses', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'eingekauft', sep: 'ein', ipa: '/ˈaɪnkaʊfən/', syn: ['kaufen', 'erwerben', 'shoppen'], ant: ['verkaufen', 'nichts kaufen'], tags: ['shopping', 'daily_life'] },
  { infinitive: 'mitnehmen', en: 'to take along', ar: 'يأخذ معه', fr: 'emporter', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'mitgenommen', sep: 'mit', ipa: '/ˈmɪtneːmən/', syn: ['einpacken', 'dabeihaben', 'transportieren'], ant: ['lassen', 'zurücklassen', 'vergessen'], tags: ['travel', 'daily_life'] },
  { infinitive: 'mitbringen', en: 'to bring along', ar: 'يجلب', fr: 'apporter', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'mitgebracht', sep: 'mit', ipa: '/ˈmɪtbʁɪŋən/', syn: ['herbringen', 'dabeihaben', 'mitnehmen'], ant: ['wegbringen', 'zurücklassen'], tags: ['social', 'daily_life'] },
  { infinitive: 'vorstellen', en: 'to introduce', ar: 'يقدم', fr: 'présenter', level: 'A1', freq: 'very_common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'vorgestellt', sep: 'vor', ipa: '/ˈfoːɐʃtɛlən/', syn: ['bekannt machen', 'präsentieren'], ant: ['verstecken', 'verschweigen'], tags: ['social', 'introduction'] },
  { infinitive: 'anfangen', en: 'to begin, start', ar: 'يبدأ', fr: 'commencer', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'angefangen', sep: 'an', ipa: '/ˈanfaŋən/', syn: ['beginnen', 'starten', 'loslegen'], ant: ['aufhören', 'beenden', 'stoppen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'aufhören', en: 'to stop, cease', ar: 'يتوقف', fr: 'arrêter', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'aufgehört', sep: 'auf', ipa: '/ˈaʊfhøːʁən/', syn: ['beenden', 'stoppen', 'schluss machen'], ant: ['anfangen', 'beginnen', 'fortsetzen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'fernsehen', en: 'to watch TV', ar: 'يشاهد التلفاز', fr: 'regarder la télé', level: 'A1', freq: 'common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'ferngesehen', sep: 'fern', ipa: '/ˈfɛʁnzeːən/', syn: ['glotzen', 'schauen'], ant: ['lesen', 'hören', 'arbeiten'], tags: ['media', 'free_time'] },
  { infinitive: 'spazieren', en: 'to walk, stroll', ar: 'يتنزه', fr: 'se promener', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'spaziert', ipa: '/ʃpaˈtsiːʁən/', syn: ['gehen', 'flanieren', 'bummeln'], ant: ['rennen', 'eilen', 'bleiben'], tags: ['free_time', 'nature'] },
  { infinitive: 'rechnen', en: 'to calculate', ar: 'يحسب', fr: 'calculer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gerechnet', ipa: '/ˈʁɛçnən/', syn: ['berechnen', 'kalkulieren', 'ausrechnen'], ant: ['schätzen', 'raten'], tags: ['math', 'education', 'daily_life'] },
  { infinitive: 'zeichnen', en: 'to draw', ar: 'يرسم', fr: 'dessiner', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gezeichnet', ipa: '/ˈtsaɪçnən/', syn: ['malen', 'skizzieren', 'kritzeln'], ant: ['löschen', 'ausradieren'], tags: ['arts', 'hobby'] },
  { infinitive: 'malen', en: 'to paint', ar: 'يرسم', fr: 'peindre', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemalt', ipa: '/ˈmaːlən/', syn: ['zeichnen', 'anmalen', 'pinseln'], ant: ['löschen', 'wegwischen'], tags: ['arts', 'hobby'] },
  { infinitive: 'singen', en: 'to sing', ar: 'يغني', fr: 'chanter', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesungen', ipa: '/ˈzɪŋən/', syn: ['trällern', 'summen', 'vortragen'], ant: ['schweigen', 'pfeifen'], tags: ['music', 'free_time'] },
  { infinitive: 'feiern', en: 'to celebrate', ar: 'يحتفل', fr: 'fêter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gefeiert', ipa: '/ˈfaɪɐn/', syn: ['festen', 'party machen', 'begehen'], ant: ['trauern', 'betrauern'], tags: ['social', 'celebrations'] },
  { infinitive: 'wünschen', en: 'to wish', ar: 'يتمنى', fr: 'souhaiter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'dativ', aux: 'haben', p2: 'gewünscht', ipa: '/ˈvʏnʃən/', syn: ['hoffen', 'begehren', 'ersehnen'], ant: ['ablehnen', 'verweigern'], tags: ['communication', 'social'] },
  { infinitive: 'danken', en: 'to thank', ar: 'يشكر', fr: 'remercier', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'gedankt', ipa: '/ˈdaŋkən/', syn: ['sich bedanken', 'Dank sagen', 'dankbar sein'], ant: ['ignorieren', 'vergessen'], tags: ['communication', 'politeness'] },
  { infinitive: 'grüßen', en: 'to greet', ar: 'يسلم', fr: 'saluer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gegrüßt', ipa: '/ˈɡʁyːsən/', syn: ['begrüßen', 'willkommen heißen'], ant: ['ignorieren', 'vermeiden'], tags: ['social', 'politeness'] },
  { infinitive: 'lächeln', en: 'to smile', ar: 'يبتسم', fr: 'sourire', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gelächelt', ipa: '/ˈlɛçəln/', syn: ['strahlen', 'grinsen', 'schmunzeln'], ant: ['weinen', 'trauern', 'frieren'], tags: ['feelings', 'social'] },
  { infinitive: 'weinen', en: 'to cry', ar: 'يبكي', fr: 'pleurer', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geweint', ipa: '/ˈvaɪnən/', syn: ['schluchzen', 'heulen', 'tränen'], ant: ['lachen', 'lächeln'], tags: ['feelings', 'daily_life'] },
  { infinitive: 'lachen', en: 'to laugh', ar: 'يضحك', fr: 'rire', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gelacht', ipa: '/ˈlaxən/', syn: ['kichern', 'grinsen', 'schmunzeln'], ant: ['weinen', 'trauern'], tags: ['feelings', 'social'] },

  // === INTRODUCTIONS / PERSONAL INFO ===
  { infinitive: 'wohnen', en: 'to live', ar: 'يسكن', fr: 'habiter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gewohnt', ipa: '/ˈvoːnən/', syn: ['leben', 'hausen'], ant: ['reisen', 'umziehen', 'wegziehen'], tags: ['home', 'daily_life'] },
  { infinitive: 'kommen', en: 'to come from', ar: 'يأتي من', fr: 'venir de', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gekommen', ipa: '/ˈkɔmən/', tags: ['introduction', 'daily_life'] },
  { infinitive: 'studieren', en: 'to study (university)', ar: 'يدرس في الجامعة', fr: 'étudier', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'studiert', ipa: '/ʃtuˈdiːʁən/', syn: ['lernen', 'sich bilden', 'forschen'], ant: ['arbeiten', 'jobben'], tags: ['education', 'university'] },

  // === CLOTHES / APPEARANCE ===
  { infinitive: 'tragen', en: 'to wear, carry', ar: 'يرتدي', fr: 'porter', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'getragen', ipa: '/ˈtʁaːɡən/', syn: ['anhaben', 'bekleiden', 'schultern'], ant: ['ablegen', 'ausziehen'], tags: ['clothing', 'daily_life'] },
  { infinitive: 'anziehen', en: 'to put on (clothes)', ar: 'يرتدي', fr: 'mettre', level: 'A1', freq: 'very_common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'angezogen', sep: 'an', ipa: '/ˈantsiːən/', syn: ['anlegen', 'überziehen', 'bekleiden'], ant: ['ausziehen', 'ablegen'], tags: ['clothing', 'daily_life'] },
  { infinitive: 'ausziehen', en: 'to take off (clothes)', ar: 'يخلع', fr: 'enlever', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'ausgezogen', sep: 'aus', ipa: '/ˈaʊstsiːən/', syn: ['ablegen', 'abstreifen'], ant: ['anziehen', 'überziehen'], tags: ['clothing', 'daily_life'] },
  { infinitive: 'waschen', en: 'to wash', ar: 'يغسل', fr: 'laver', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gewaschen', ipa: '/ˈvaʃən/', syn: ['reinigen', 'säubern', 'putzen'], ant: ['verschmutzen', 'beschmutzen'], tags: ['housework', 'hygiene'] },

  // === WEATHER / NATURE ===
  { infinitive: 'regnen', en: 'to rain', ar: 'تمطر', fr: 'pleuvoir', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geregnet', ipa: '/ˈʁeːɡnən/', syn: ['nieseln', 'schütten', 'tröpfeln'], ant: ['scheinen', 'aufklaren'], tags: ['weather', 'nature'] },
  { infinitive: 'schneien', en: 'to snow', ar: 'تتساقط الثلوج', fr: 'neiger', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geschneit', ipa: '/ˈʃnaɪən/', syn: ['flocken', 'eiskristalle fallen'], ant: ['tauen', 'regnen'], tags: ['weather', 'nature'] },
  { infinitive: 'scheinen', en: 'to shine', ar: 'تشرق', fr: 'briller', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geschienen', ipa: '/ˈʃaɪnən/', syn: ['leuchten', 'strahlen', 'glänzen'], ant: ['regnen', 'bewölkt sein'], tags: ['weather', 'nature'] },

  // === COMMUNICATION ===
  { infinitive: 'rufen', en: 'to call', ar: 'ينادي', fr: 'appeler', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gerufen', ipa: '/ˈʁuːfən/', syn: ['schreien', 'brüllen', 'herbeirufen'], ant: ['flüstern', 'schweigen'], tags: ['communication', 'social'] },
  { infinitive: 'holen', en: 'to fetch, get', ar: 'يجلب', fr: 'aller chercher', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geholt', ipa: '/ˈhoːlən/', syn: ['bringen', 'besorgen', 'abholen'], ant: ['bringen', 'liefern', 'geben'], tags: ['actions', 'daily_life'] },
  { infinitive: 'legen', en: 'to lay, put', ar: 'يضع', fr: 'poser', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gelegt', ipa: '/ˈleːɡən/', syn: ['stellen', 'setzen', 'packen'], ant: ['nehmen', 'wegnehmen', 'entfernen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'stellen', en: 'to place, put upright', ar: 'يضع', fr: 'mettre debout', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gestellt', ipa: '/ˈʃtɛlən/', syn: ['aufstellen', 'platzieren', 'positionieren'], ant: ['wegnehmen', 'entfernen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'setzen', en: 'to set, put (seated)', ar: 'يجلس', fr: 'asseoir', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesetzt', ipa: '/ˈzɛtsən/', syn: ['platzieren', 'hinsetzen', 'deponieren'], ant: ['stehen', 'aufheben'], tags: ['actions', 'daily_life'] },
  { infinitive: 'bringen', en: 'to bring', ar: 'يجلب', fr: 'apporter', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebracht', ipa: '/ˈbʁɪŋən/', syn: ['herbringen', 'liefern', 'transportieren'], ant: ['wegnehmen', 'entfernen', 'holen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'halten', en: 'to hold, stop', ar: 'يمسك', fr: 'tenir', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gehalten', ipa: '/ˈhaltən/', syn: ['festhalten', 'umklammern', 'stoppen'], ant: ['loslassen', 'fallen lassen', 'freigeben'], tags: ['actions', 'daily_life'] },
  { infinitive: 'werfen', en: 'to throw', ar: 'يرمي', fr: 'lancer', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geworfen', ipa: '/ˈvɛʁfən/', syn: ['schleudern', 'schmeißen', 'befördern'], ant: ['fangen', 'auffangen', 'halten'], tags: ['actions', 'sports'] },
  { infinitive: 'fangen', en: 'to catch', ar: 'يمسك', fr: 'attraper', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gefangen', ipa: '/ˈfaŋən/', syn: ['ergreifen', 'fassen', 'einfangen'], ant: ['werfen', 'loslassen', 'entkommen lassen'], tags: ['actions', 'sports'] },
  { infinitive: 'zeigen', en: 'to show', ar: 'يظهر', fr: 'montrer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'dativ', aux: 'haben', p2: 'gezeigt', ipa: '/ˈtsaɪɡən/', syn: ['präsentieren', 'vorführen', 'demonstrieren'], ant: ['verstecken', 'verbergen'], tags: ['communication', 'education'] },
  { infinitive: 'erzählen', en: 'to tell, narrate', ar: 'يروي', fr: 'raconter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'dativ', aux: 'haben', p2: 'erzählt', ipa: '/ɛʁˈtsɛːlən/', syn: ['berichten', 'schildern', 'wiedergeben'], ant: ['verschweigen', 'verheimlichen'], tags: ['communication', 'social'] },
  { infinitive: 'glauben', en: 'to believe', ar: 'يصدق', fr: 'croire', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'dativ', aux: 'haben', p2: 'geglaubt', ipa: '/ˈɡlaʊbən/', syn: ['vertrauen', 'überzeugt sein', 'denken'], ant: ['bezweifeln', 'anzweifeln', 'misstrauen'], tags: ['thought', 'feelings'] },
  { infinitive: 'brauchen', en: 'to need', ar: 'يحتاج', fr: 'avoir besoin', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebraucht', ipa: '/ˈbʁaʊxən/', syn: ['benötigen', 'nötig haben', 'erfordern'], ant: ['entbehren', 'verzichten'], tags: ['daily_life', 'essential'] },

  // === FREE TIME ===
  { infinitive: 'reisen', en: 'to travel', ar: 'يسافر', fr: 'voyager', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gereist', ipa: '/ˈʁaɪzən/', syn: ['verreisen', 'unterwegs sein', 'auf Reisen gehen'], ant: ['bleiben', 'daheim bleiben'], tags: ['travel', 'free_time'] },
  { infinitive: 'fotografieren', en: 'to photograph', ar: 'يصوّر', fr: 'photographier', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'fotografiert', ipa: '/fotoɡʁaˈfiːʁən/', syn: ['knipsen', 'aufnehmen', 'foto machen'], ant: ['löschen', 'wegwerfen'], tags: ['hobby', 'free_time'] },
  { infinitive: 'kochen', en: 'to cook', ar: 'يطبخ', fr: 'cuisiner', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gekocht', ipa: '/ˈkɔxən/', syn: ['zubereiten', 'braten', 'kochen'], ant: ['bestellen', 'essen gehen'], tags: ['food', 'housework'] },
  { infinitive: 'backen', en: 'to bake', ar: 'يخبز', fr: 'cuire au four', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebacken', ipa: '/ˈbakən/', syn: ['braten', 'rösten'], ant: ['roh lassen'], tags: ['food', 'cooking'] },

  // === SHOPPING / MONEY ===
  { infinitive: 'kosten', en: 'to cost', ar: 'يكلف', fr: 'coûter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'akkusativ', aux: 'haben', p2: 'gekostet', ipa: '/ˈkɔstən/', syn: ['betragen', 'zu stehen kommen'], ant: ['geschenkt sein', 'umsonst sein'], tags: ['money', 'shopping'] },
  { infinitive: 'bezahlen', en: 'to pay', ar: 'يدفع', fr: 'payer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'bezahlt', ipa: '/bəˈtsaːlən/', syn: ['zahlen', 'begleichen', 'abbezahlen'], ant: ['schulden', 'kassieren'], tags: ['money', 'shopping'] },
  { infinitive: 'sparen', en: 'to save (money)', ar: 'يدخر', fr: 'économiser', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gespart', ipa: '/ˈʃpaːʁən/', syn: ['zurücklegen', 'ansparen', 'sammeln'], ant: ['ausgeben', 'verschwenden', 'verprassen'], tags: ['money', 'daily_life'] },

  // === HEALTH ===
  { infinitive: 'helfen', en: 'to help', ar: 'يساعد', fr: 'aider', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'geholfen', ipa: '/ˈhɛlfən/', syn: ['unterstützen', 'beistehen', 'assistieren'], ant: ['hindern', 'blockieren', 'im Wege stehen'], tags: ['social', 'essential'] },
  { infinitive: 'nützen', en: 'to be useful', ar: 'ينفع', fr: 'être utile', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'genützt', ipa: '/ˈnʏtsən/', syn: ['dienen', 'helfen', 'von Nutzen sein'], ant: ['schaden', 'stören', 'hindern'], tags: ['daily_life', 'utility'] },
  { infinitive: 'passen', en: 'to fit, suit', ar: 'يناسب', fr: 'aller (bien)', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'gepasst', ipa: '/ˈpasən/', syn: ['sitzen', 'gut stehen', 'angemessen sein'], ant: ['nicht passen', 'stören'], tags: ['clothing', 'daily_life'] },

  // === MODAL VERB EXTENDED ===
  { infinitive: 'mögen', en: 'to like', ar: 'يحب', fr: 'aimer', level: 'A1', freq: 'very_common', type: 'modal', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemocht', ipa: '/ˈmøːɡən/', syn: ['lieben', 'gern haben', 'bevorzugen'], ant: ['hassen', 'nicht mögen', 'verabscheuen'], tags: ['modal', 'feelings'] },

  // === EVERYDAY ACTIVITIES ===
  { infinitive: 'frühstücken', en: 'to have breakfast', ar: 'يتناول الفطور', fr: 'prendre le petit-déjeuner', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gefrühstückt', ipa: '/ˈfʁyːʃtʏkən/', tags: ['food', 'daily_life'] },
  { infinitive: 'aufräumen', en: 'to clean up, tidy', ar: 'يرتب', fr: 'ranger', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'aufgeräumt', sep: 'auf', ipa: '/ˈaʊfʁɔʏmən/', syn: ['ordnen', 'säubern', 'putzen'], ant: ['durcheinanderbringen', 'verwirren'], tags: ['housework', 'daily_life'] },
  { infinitive: 'abwaschen', en: 'to wash dishes', ar: 'يغسل الصحون', fr: 'laver la vaisselle', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'abgewaschen', sep: 'ab', ipa: '/ˈapvaʃən/', syn: ['spülen', 'säubern', 'reinigen'], ant: ['beschmutzen', 'einschmutzig'], tags: ['housework', 'daily_life'] },
  { infinitive: 'einschlafen', en: 'to fall asleep', ar: 'ينام', fr: 's\'endormir', level: 'A1', freq: 'common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'eingeschlafen', sep: 'ein', ipa: '/ˈaɪnʃlaːfən/', syn: ['einnicken', 'wegdösen', 'in Morpheus Armen'], ant: ['aufwachen', 'wach bleiben', 'aufstehen'], tags: ['daily_life', 'health'] },
  { infinitive: 'aufwachen', en: 'to wake up', ar: 'يستيقظ', fr: 'se réveiller', level: 'A1', freq: 'common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'aufgewacht', sep: 'auf', ipa: '/ˈaʊfvaxən/', syn: ['erwachen', 'munter werden'], ant: ['einschlafen', 'weiterschlafen'], tags: ['daily_life', 'morning_routine'] },

  // === DIRECTION / ORIENTATION ===
  { infinitive: 'biegen', en: 'to turn', ar: 'ينعطف', fr: 'tourner', level: 'A1', freq: 'common', type: 'irregular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'gebogen', ipa: '/ˈbiːɡən/', syn: ['abbiegen', 'einbiegen', 'abschwenken'], ant: ['geradeaus gehen', 'weitergehen'], tags: ['traffic', 'directions'] },
  { infinitive: 'abbiegen', en: 'to turn off', ar: 'ينعطف', fr: 'tourner', level: 'A1', freq: 'common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'abgebogen', sep: 'ab', ipa: '/ˈapbiːɡən/', syn: ['biegen', 'einbiegen', 'abschwenken'], ant: ['geradeaus fahren'], tags: ['traffic', 'directions'] },

  // === EXTRA A1 COMMON ===
  { infinitive: 'atmen', en: 'to breathe', ar: 'يتنفس', fr: 'respirer', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geatmet', ipa: '/ˈaːtmən/', syn: ['einatmen', 'ausatmen', 'schnaufen'], ant: ['erstickten', 'keuchen'], tags: ['health', 'body'] },
  { infinitive: 'läuten', en: 'to ring', ar: 'يدق', fr: 'sonner', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geläutet', ipa: '/ˈlɔʏtən/', syn: ['klingeln', 'bimmeln', 'schrillen'], ant: ['schweigen', 'still sein'], tags: ['daily_life', 'sounds'] },
  { infinitive: 'klingeln', en: 'to ring (bell)', ar: 'يدق الجرس', fr: 'sonner (cloche)', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geklingelt', ipa: '/ˈklɪŋəln/', syn: ['läuten', 'bimmeln', 'schellen'], ant: ['still sein', 'schweigen'], tags: ['daily_life', 'sounds'] },
  { infinitive: 'klopfen', en: 'to knock', ar: 'يقرع', fr: 'frapper', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geklopft', ipa: '/ˈklɔpfən/', syn: ['hämmern', 'pochen', 'tippen'], ant: ['still sein', 'warten'], tags: ['daily_life', 'sounds'] },
  { infinitive: 'warten', en: 'to wait', ar: 'ينتظر', fr: 'attendre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gewartet', ipa: '/ˈvaʁtən/', syn: ['ausharren', 'abwarten', 'sich gedulden'], ant: ['gehen', 'weggehen', 'aufgeben'], tags: ['daily_life', 'actions'] },
  { infinitive: 'schicken', en: 'to send', ar: 'يرسل', fr: 'envoyer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geschickt', ipa: '/ˈʃɪkən/', syn: ['senden', 'verschicken', 'übermitteln'], ant: ['empfangen', 'bekommen', 'erhalten'], tags: ['communication', 'daily_life'] },
  { infinitive: 'probieren', en: 'to try, taste', ar: 'يجرب', fr: 'essayer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'probiert', ipa: '/pʁoˈbiːʁən/', syn: ['versuchen', 'testen', 'kosten'], ant: ['ablehnen', 'verweigern', 'vermeiden'], tags: ['food', 'actions'] },
  { infinitive: 'versuchen', en: 'to try, attempt', ar: 'يحاول', fr: 'tenter', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'versucht', ipa: '/fɛʁˈzuːxən/', syn: ['probieren', 'anstreben', 'sich bemühen'], ant: ['aufgeben', 'verzichten', 'lassen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'passieren', en: 'to happen', ar: 'يحدث', fr: 'arriver', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'passiert', ipa: '/paˈsiːʁən/', syn: ['geschehen', 'sich ereignen', 'vorfallen'], ant: ['bleiben aus', 'nicht eintreten'], tags: ['daily_life', 'events'] },
  { infinitive: 'besuchen', en: 'to visit', ar: 'يزور', fr: 'rendre visite', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'besucht', ipa: '/bəˈzuːxən/', syn: ['aufssuchen', 'vorbeischauen', 'einen Besuch machen'], ant: ['meiden', 'ausweichen', 'ignorieren'], tags: ['social', 'travel'] },
  { infinitive: 'vergessen', en: 'to forget', ar: 'ينسى', fr: 'oublier', level: 'A1', freq: 'very_common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'vergessen', sep: 'ver-', ipa: '/fɛʁˈɡɛsən/', syn: ['nicht denken an', 'übersehen', 'vernachlässigen'], ant: ['erinnern', 'behalten', 'merken'], tags: ['daily_life', 'memory'] },
  { infinitive: 'erinnern', en: 'to remind', ar: 'يذكر', fr: 'rappeler', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'erinnert', ipa: '/ɛˈʁɪnɐn/', ant: ['vergessen'], tags: ['daily_life', 'memory'] },
  { infinitive: 'merken', en: 'to notice, memorize', ar: 'يلاحظ', fr: 'remarquer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemerkt', ipa: '/ˈmɛʁkən/', syn: ['bemerken', 'wahrnehmen', 'sich einprägen'], ant: ['vergessen', 'übersehen'], tags: ['daily_life', 'memory'] },
  { infinitive: 'stimmen', en: 'to be correct', ar: 'يكون صحيحا', fr: 'être correct', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gestimmt', ipa: '/ˈʃtɪmən/', syn: ['richtig sein', 'korrekt sein', 'zutreffen'], ant: ['falsch sein', 'unwahr sein'], tags: ['daily_life', 'communication'] },
  { infinitive: 'fehlen', en: 'to be missing, absent', ar: 'يكون غائبا', fr: 'manquer', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gefehlt', ipa: '/ˈfeːlən/', syn: ['vermissen', 'abwesend sein', 'mangelnd'], ant: ['da sein', 'anwesend sein'], tags: ['daily_life', 'school'] },
  { infinitive: 'unterschreiben', en: 'to sign', ar: 'يوقع', fr: 'signer', level: 'A1', freq: 'common', type: 'inseparable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'unterschrieben', ipa: '/ʊntɐˈʃʁaɪbən/', syn: ['signieren', 'unterzeichnen', 'unterschreiben lassen'], ant: ['löschen', 'annullieren'], tags: ['office', 'daily_life'] },
  { infinitive: 'sammeln', en: 'to collect', ar: 'يجمع', fr: 'collectionner', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gesammelt', ipa: '/ˈzamlən/', syn: ['ansammeln', 'häufen', 'aufspeichern'], ant: ['zerstreuen', 'verteilen', 'ausgeben'], tags: ['hobby', 'daily_life'] },
  { infinitive: 'ordnen', en: 'to organize, arrange', ar: 'يرتب', fr: 'organiser', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geordnet', ipa: '/ˈɔʁdnən/', syn: ['sortieren', 'aufräumen', 'systematisieren'], ant: ['durcheinanderbringen', 'verwirren'], tags: ['housework', 'daily_life'] },
  { infinitive: 'wechseln', en: 'to change', ar: 'يغير', fr: 'changer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gewechselt', ipa: '/ˈvɛksəln/', syn: ['tauschen', 'austauschen', 'umstellen'], ant: ['behalten', 'festhalten', 'stabil'], tags: ['daily_life', 'actions'] },
  { infinitive: 'tauschen', en: 'to exchange, swap', ar: 'يتبادل', fr: 'échanger', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'getauscht', ipa: '/ˈtaʊʃən/', syn: ['austauschen', 'umtauschen', 'wechseln'], ant: ['behalten', 'nichts geben'], tags: ['social', 'shopping'] },
  { infinitive: 'buchen', en: 'to book', ar: 'يحجز', fr: 'réserver', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebracht', ipa: '/ˈbuːxən/', syn: ['reservieren', 'vorbestellen', 'buchen lassen'], ant: ['stornieren', 'abbestellen'], tags: ['travel', 'shopping'] },
  { infinitive: 'drucken', en: 'to print', ar: 'يطبع', fr: 'imprimer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gedruckt', ipa: '/ˈdʁʏkən/', syn: ['ausdrucken', 'kopieren'], ant: ['löschen', 'digital speichern'], tags: ['office', 'technology'] },
  { infinitive: 'packen', en: 'to pack', ar: 'يحزم', fr: 'emballer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gepackt', ipa: '/ˈpakən/', syn: ['einpacken', 'verpacken', 'hineinlegen'], ant: ['auspacken', 'leeren', 'entfernen'], tags: ['travel', 'daily_life'] },
  { infinitive: 'putzen', en: 'to clean', ar: 'ينظف', fr: 'nettoyer', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geputzt', ipa: '/ˈpʊtsən/', tags: ['housework', 'daily_life'] },
  { infinitive: 'rasieren', en: 'to shave', ar: 'يحلق', fr: 'raser', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'rasiert', ipa: '/ʁaˈziːʁən/', tags: ['hygiene', 'daily_life'] },
  { infinitive: 'duschen', en: 'to shower', ar: 'يستحم', fr: 'se doucher', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'geduscht', ipa: '/ˈduːʃən/', syn: ['waschen', 'baden', 'sich abduschen'], ant: ['verschmutzen', 'schwitzen'], tags: ['hygiene', 'daily_life'] },
  { infinitive: 'baden', en: 'to bathe', ar: 'يستحم', fr: 'baigner', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gebadet', ipa: '/ˈbaːdən/', syn: ['duschen', 'waschen', 'plantschen'], ant: ['trocken bleiben', 'schwitzen'], tags: ['hygiene', 'daily_life'] },

  // === COOKING / KITCHEN ===
  { infinitive: 'braten', en: 'to fry, roast', ar: 'يقلي', fr: 'faire frire', level: 'A1', freq: 'common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebraten', ipa: '/ˈbʁaːtən/', syn: ['rösten', 'grillen', 'schmoren'], ant: ['kochen', 'dämpfen'], tags: ['cooking', 'food'] },
  { infinitive: 'schneiden', en: 'to cut', ar: 'يقطع', fr: 'couper', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'geschnitten', ipa: '/ˈʃnaɪdən/', syn: ['hacken', 'zerteilen', 'trennen'], ant: ['kleben', 'verbinden', 'fügen'], tags: ['cooking', 'actions'] },
  { infinitive: 'mischen', en: 'to mix', ar: 'يخلط', fr: 'mélanger', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gemischt', ipa: '/ˈmɪʃən/', syn: ['vermischen', 'verrühren', 'kombinieren'], ant: ['trennen', 'sortieren', 'separieren'], tags: ['cooking', 'actions'] },

  // === COMMUNICATION EXTENDED ===
  { infinitive: 'bitten', en: 'to ask, request', ar: 'يطلب', fr: 'prier', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gebeten', ipa: '/ˈbɪtən/', syn: ['ersuchen', 'anflehen', 'erbitten'], ant: ['ablehnen', 'verweigern', 'fordern'], tags: ['communication', 'social'] },
  { infinitive: 'einladen', en: 'to invite', ar: 'يدعو', fr: 'inviter', level: 'A1', freq: 'common', type: 'separable', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'eingeladen', sep: 'ein', ipa: '/ˈaɪnlaːdən/', syn: ['herbitten', 'willkommen heißen', 'gastgeben'], ant: ['ausschließen', 'ausladen'], tags: ['social', 'celebrations'] },

  // === FEELINGS ===
  { infinitive: 'hoffen', en: 'to hope', ar: 'يأمل', fr: 'espérer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gehofft', ipa: '/ˈhɔfən/', syn: ['wünschen', 'vertrauen', 'zuversichtlich sein'], ant: ['verzweifeln', 'befürchten', 'zweifeln'], tags: ['feelings', 'daily_life'] },
  { infinitive: 'fürchten', en: 'to fear', ar: 'يخاف', fr: 'craindre', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gefürchtet', ipa: '/ˈfʏʁçtən/', syn: ['Angst haben', 'bang sein', 'sich ängstigen'], ant: ['hoffen', 'vertrauen'], tags: ['feelings', 'daily_life'] },
  { infinitive: 'staunen', en: 'to be amazed', ar: 'يتعجب', fr: 's\'étonner', level: 'A1', freq: 'common', type: 'regular', tr: 'intransitive', obj: 'none', aux: 'haben', p2: 'gestaunt', ipa: '/ˈʃtaʊnən/', syn: ['sich wundern', 'erstaunt sein', 'verblüfft sein'], ant: ['gleichgültig sein'], tags: ['feelings', 'daily_life'] },

  // === TRAVEL ===
  { infinitive: 'abfahren', en: 'to depart', ar: 'ينطلق', fr: 'partir', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'abgefahren', sep: 'ab', ipa: '/ˈapfaːʁən/', syn: ['losfahren', 'aufbrechen', 'wegfahren'], ant: ['ankommen', 'eintreffen', 'anhalten'], tags: ['travel', 'transportation'] },
  { infinitive: 'ankommen', en: 'to arrive', ar: 'يصل', fr: 'arriver', level: 'A1', freq: 'very_common', type: 'separable', tr: 'intransitive', obj: 'none', aux: 'sein', p2: 'angekommen', sep: 'an', ipa: '/ˈankɔmən/', syn: ['eintreffen', 'auftauchen', 'hinkommen'], ant: ['abfahren', 'weggehen', 'verlassen'], tags: ['travel', 'transportation'] },

  // === EXTRA A1 ===
  { infinitive: 'decken', en: 'to cover, set (table)', ar: 'يغطي', fr: 'couvrir', level: 'A1', freq: 'common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'gedeckt', ipa: '/ˈdɛkən/', syn: ['bedecken', 'zudecken', 'überdecken'], ant: ['entdecken', 'aufdecken'], tags: ['housework', 'daily_life'] },
  { infinitive: 'bedeuten', en: 'to mean', ar: 'يعني', fr: 'signifier', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'bedeutet', ipa: '/bəˈdɔʏtən/', syn: ['heißen', 'ausdrücken', 'implizieren'], ant: ['verschweigen', 'verbergen'], tags: ['communication', 'education'] },
  { infinitive: 'passen', en: 'to fit, suit', ar: 'يناسب', fr: 'convenir', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'gepasst', ipa: '/ˈpasən/', syn: ['angemessen sein', 'gut sein'], ant: ['nicht passen', 'stören'], tags: ['daily_life', 'clothing'] },
  { infinitive: 'gehören', en: 'to belong', ar: 'ينتمي', fr: 'appartenir', level: 'A1', freq: 'very_common', type: 'regular', tr: 'intransitive', obj: 'dativ', aux: 'haben', p2: 'gehört', ipa: '/ɡəˈhøːʁən/', syn: ['zugehören', 'eigen sein', 'zustehen'], ant: ['fremd sein', 'nicht gehören'], tags: ['possession', 'daily_life'] },
  { infinitive: 'betreten', en: 'to enter', ar: 'يدخل', fr: 'entrer', level: 'A1', freq: 'common', type: 'inseparable', tr: 'transitive', obj: 'akkusativ', aux: 'sein', p2: 'betreten', ipa: '/bəˈtʁeːtən/', syn: ['hineingehen', 'eintreten', 'hereinkommen'], ant: ['verlassen', 'hinausgehen', 'weggehen'], tags: ['movement', 'daily_life'] },
  { infinitive: 'verlassen', en: 'to leave', ar: 'يغادر', fr: 'quitter', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'verlassen', ipa: '/fɛʁˈlasən/', syn: ['weggehen', 'fortgehen', 'sich entfernen'], ant: ['bleiben', 'ankommen', 'betreten'], tags: ['movement', 'travel'] },
  { infinitive: 'erreichen', en: 'to reach, achieve', ar: 'يصل إلى', fr: 'atteindre', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'erreicht', ipa: '/ɛˈʁaɪçən/', syn: ['schaffen', 'bewältigen', 'ankommen'], ant: ['verfehlen', 'übersehen', 'aufgeben'], tags: ['achievement', 'daily_life'] },
  { infinitive: 'beginnen', en: 'to begin', ar: 'يبدأ', fr: 'commencer', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'begonnen', ipa: '/bəˈɡɪnən/', syn: ['anfangen', 'starten', 'loslegen'], ant: ['beenden', 'aufhören', 'abschließen'], tags: ['actions', 'daily_life'] },
  { infinitive: 'beenden', en: 'to end, finish', ar: 'ينهي', fr: 'terminer', level: 'A1', freq: 'very_common', type: 'regular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'beendet', ipa: '/bəˈʔɛndən/', syn: ['abschließen', 'fertig machen', 'vollenden'], ant: ['beginnen', 'anfangen', 'starten'], tags: ['actions', 'daily_life'] },
  { infinitive: 'genießen', en: 'to enjoy', ar: 'يستمتع', fr: 'profiter', level: 'A1', freq: 'very_common', type: 'irregular', tr: 'transitive', obj: 'akkusativ', aux: 'haben', p2: 'genossen', ipa: '/ɡəˈniːsən/', syn: ['erfreuen', 'auskosten', 'Gefallen finden'], ant: ['leiden', 'ertragen', 'hassen'], tags: ['feelings', 'free_time'] },
]
