const verbsByLevel: Record<string, string[]> = {
  a1: [
    'sein', 'haben', 'werden', 'können', 'müssen', 'wollen', 'dürfen', 'sollen', 'mögen',
    'heißen', 'wohnen', 'kommen', 'gehen', 'machen', 'sagen', 'geben', 'nehmen', 'sehen',
    'hören', 'lesen', 'schreiben', 'sprechen', 'verstehen', 'lernen', 'arbeiten', 'spielen',
    'essen', 'trinken', 'kaufen', 'bezahlen', 'öffnen', 'schließen', 'bringen', 'holen',
    'suchen', 'finden', 'brauchen', 'haben', 'liegen', 'stehen', 'sitzen', 'schlafen',
    'aufstehen', 'anfangen', 'mitkommen', 'fernsehen', 'einkaufen', 'mitbringen',
    'anrufen', 'einladen', 'ausgehen', 'vorstellen', 'putzen', 'waschen', 'kochen',
    'frühstücken', 'abendessen', 'reisen', 'fahren', 'fliegen', 'laufen', 'schwimmen',
    'tanzen', 'singen', 'malen', 'zeichnen', 'basteln', 'feiern', 'schenken', 'bekommen',
    'studieren', 'besuchen', 'wohnen', 'leben', 'sterben', 'geboren', 'wachsen',
    'helfen', 'danken', 'wünschen', 'fragen', 'antworten', 'erzählen', 'erklären',
    'zeigen', 'glauben', 'denken', 'wissen', 'vergessen', 'erinnern', 'bitten',
    'grüßen', 'verabschieden', 'entschuldigen', 'dürfen', 'probieren', 'passen',
    'gefallen', 'schmecken', 'kosten', 'tun', 'lassen', 'bleiben', 'passieren',
  ],

  a2: [
    'backen', 'baden', 'bauen', 'bedeuten', 'beginnen', 'bekommen', 'beschreiben',
    'bestehen', 'bestellen', 'besuchen', 'betreten', 'bewegen', 'bezahlen',
    'bieten', 'bilden', 'bleiben', 'blicken', 'bohren', 'borgen', 'brauchen',
    'brennen', 'bringen', 'buchen', 'dauern', 'decken', 'dienen', 'diskutieren',
    'drucken', 'drücken', 'dürfen', 'empfehlen', 'enden', 'entdecken', 'enthalten',
    'entwickeln', 'erhalten', 'erkennen', 'erreichen', 'erscheinen', 'erwarten',
    'erziehen', 'erzählen', 'fahren', 'fallen', 'fangen', 'fassen', 'fehlen',
    'feiern', 'fernsehen', 'feststellen', 'finden', 'fliegen', 'fließen', 'folgen',
    'fordern', 'fragen', 'freuen', 'führen', 'füllen', 'fürchten', 'gebrauchen',
    'gedenken', 'gehen', 'gehören', 'gelten', 'genießen', 'gewinnen', 'gießen',
    'glauben', 'graben', 'greifen', 'gründen', 'grüßen', 'halten', 'handeln',
    'hängen', 'heben', 'heiraten', 'heißen', 'herausfinden', 'hereinkommen',
    'hinlegen', 'hinstellen', 'hoffen', 'holen', 'hören', 'informieren',
    'interessieren', 'jemanden', 'kämpfen', 'kaufen', 'kennen', 'klären',
    'klopfen', 'kochen', 'kommen', 'kontrollieren', 'können', 'kriegen',
    'kündigen', 'lächeln', 'lachen', 'laden', 'langen', 'lassen', 'laufen',
    'leben', 'legen', 'lehren', 'leiden', 'leihen', 'lernen', 'lesen', 'lieben',
    'liefern', 'liegen', 'loben', 'lösen', 'lügen', 'machen', 'malen', 'meinen',
    'melden', 'messen', 'mieten', 'mitbringen', 'mitkommen', 'mitnehmen',
    'mögen', 'müssen', 'nachdenken', 'nachfragen', 'nehmen', 'nennen',
    'nützen', 'öffnen', 'ordnen', 'passen', 'passieren', 'planen', 'probieren',
    'prüfen', 'putzen', 'rasieren', 'rechnen', 'recht', 'reden', 'regnen',
    'reichen', 'reisen', 'rennen', 'retten', 'riechen', 'rufen', 'ruhen',
    'sagen', 'sammeln', 'schaffen', 'schenken', 'schicken', 'schieben',
    'schlafen', 'schlagen', 'schließen', 'schmecken', 'schmelzen', 'schneiden',
    'schneien', 'schreiben', 'schreien', 'schweigen', 'schwimmen', 'schwitzen',
    'segeln', 'sehen', 'sein', 'senden', 'setzen', 'sich', 'singen', 'sinken',
    'sitzen', 'sollen', 'sparen', 'spazieren', 'spielen', 'sprechen', 'springen',
    'stampfen', 'stärken', 'starten', 'staunen', 'stecken', 'stehen', 'steigen',
    'stellen', 'sterben', 'stimmen', 'stören', 'stoßen', 'streichen', 'streiten',
    'studieren', 'stürzen', 'suchen', 'tanzen', 'tätigen', 'tauchen', 'teilen',
    'telefonieren', 'testen', 'töten', 'tragen', 'trauen', 'träumen', 'treffen',
    'treiben', 'treten', 'trinken', 'trocknen', 'tun', 'überlegen', 'überraschen',
    'übersetzen', 'üben', 'umarmen', 'umziehen', 'unterhalten', 'unterscheiden',
    'unterstützen', 'unterrichten', 'verabschieden', 'verändern', 'verbessern',
    'verbinden', 'verbringen', 'verdienen', 'vereinbaren', 'vergleichen',
    'vergessen', 'verkaufen', 'verlangen', 'verlassen', 'verlieren', 'vermeiden',
    'vermieten', 'verpassen', 'verraten', 'verreisen', 'versammeln', 'verschwinden',
    'versprechen', 'verstehen', 'versuchen', 'verteilen', 'vertragen', 'verwandeln',
    'verwenden', 'verzeihen', 'vollenden', 'vorbereiten', 'vorschlagen',
    'vorstellen', 'wachen', 'wachsen', 'wagen', 'wählen', 'wandern', 'warten',
    'waschen', 'wechseln', 'wecken', 'weggehen', 'wehtun', 'weinen', 'weitermachen',
    'welken', 'wenden', 'werben', 'werden', 'werfen', 'wiegen', 'wiederholen',
    'winken', 'wirken', 'wissen', 'wohnen', 'wollen', 'wünschen', 'zahlen',
    'zeichnen', 'zeigen', 'ziehen', 'zittern', 'zögern', 'zuhören', 'zumachen',
    'zurechtkommen', 'zurückgeben', 'zurückkommen', 'zusammenarbeiten',
    'zustimmen', 'zwingen',
  ],

  b1: [
    'abbrechen', 'abdrehen', 'abfahren', 'abgeben', 'abhängen', 'ablehnen',
    'ablesen', 'abmachen', 'abnehmen', 'absagen', 'abschalten', 'abschließen',
    'abschneiden', 'absetzen', 'abstellen', 'abstimmen', 'abwechseln', 'abziehen',
    'achten', 'akklimatisieren', 'aktualisieren', 'annehmen', 'anpassen', 'anprobieren',
    'anregen', 'anschalten', 'ansehen', 'ansprechen', 'anstellen', 'anstrengen',
    'antreffen', 'antworten', 'anvertrauen', 'anweisen', 'anwenden', 'anzeigen',
    'arbeiten', 'argumentieren', 'ärgern', 'arrangieren', 'atmen', 'auftauchen',
    'auftragen', 'auftreten', 'aufwachsen', 'ausbilden', 'ausdrücken', 'ausfallen',
    'ausfüllen', 'ausgeben', 'ausgleichen', 'aushalten', 'auskommen', 'ausmachen',
    'ausruhen', 'ausschalten', 'aussehen', 'aussetzen', 'aussprechen', 'aussteigen',
    'ausstellen', 'aussuchend', 'ausüben', 'auswählen', 'auswandern', 'ausziehen',
    'backen', 'baden', 'bauen', 'beachten', 'bearbeiten', 'beauftragen', 'bedanken',
    'bedauern', 'bedecken', 'bedienen', 'bedingen', 'beeilen', 'beeinflussen',
    'befehlen', 'befinden', 'befragen', 'befreien', 'begleiten', 'begraben',
    'begreifen', 'begründen', 'behalten', 'behandeln', 'behaupten', 'beherrschen',
    'behindern', 'beißen', 'beitragen', 'bekanntgeben', 'beklagen', 'bekämpfen',
    'bekommen', 'belauben', 'beleidigen', 'beliefern', 'bemerken', 'bemühen',
    'benachrichtigen', 'benutzen', 'beobachten', 'beraten', 'berechnen', 'bereiten',
    'bereuen', 'berichten', 'berücksichtigen', 'beruhigen', 'berühren', 'beschädigen',
    'beschäftigen', 'bescheinigen', 'beschließen', 'beschränken', 'beschützen',
    'beseitigen', 'besitzen', 'besorgen', 'bestehen', 'bestimmen', 'bestrafen',
    'bestätigen', 'beteiligen', 'betonen', 'betrachten', 'betragen', 'betrügen',
    'beurteilen', 'bevorzugen', 'bewahren', 'bewegen', 'beweisen', 'bewerben',
    'bewerten', 'bewilligen', 'bezweifeln', 'bieten', 'bilden', 'billigen',
    'bitten', 'blasen', 'blicken', 'blühen', 'bohren', 'borgen', 'brauen',
    'brav', 'brennen', 'bringen', 'buchen', 'bügeln', 'charakterisieren',
    'dämmern', 'dämpfen', 'danken', 'darstellen', 'dauern', 'dehnen', 'dekorieren',
    'demonstrieren', 'denken', 'deponieren', 'deuten', 'dichten', 'dienen',
    'diskutieren', 'disziplinieren', 'donnern', 'drängen', 'drehen', 'dringen',
    'drucken', 'dulden', 'durchführen', 'durchsetzen', 'dürfen', 'eben',
    'ehren', 'eigen', 'eilig', 'einatmen', 'einbauen', 'einbringen', 'einfallen',
    'einführen', 'eingeben', 'einhalten', 'einigen', 'einkaufen', 'einladen',
    'einlegen', 'einrichten', 'einschalten', 'einschätzen', 'einsetzen', 'einsteigen',
    'einstellen', 'einteilen', 'eintragen', 'einwerfen', 'einwilligen', 'einziehen',
    'empfangen', 'empfinden', 'entfernen', 'entführen', 'entgegnen', 'enthalten',
    'entkommen', 'entlassen', 'entschädigen', 'entscheiden', 'entschließen',
    'entsetzen', 'entspannen', 'entsprechen', 'entstehen', 'enttäuschen', 'entwerfen',
    'entwickeln', 'erbauen', 'erblicken', 'erbrechen', 'erfahren', 'erfinden',
    'erfolgen', 'erfordern', 'erfüllen', 'ergeben', 'erhalten', 'erheben',
    'erhöhen', 'erkälten', 'erkennen', 'erklären', 'erkundigen', 'erlauben',
    'erleben', 'erledigen', 'erleichtern', 'erlernen', 'ermöglichen', 'ermutigen',
    'ernähren', 'erneuern', 'erobern', 'eröffnen', 'erraten', 'erregen', 'erreichen',
    'erschaffen', 'erscheinen', 'erschrecken', 'ersetzen', 'ertragen', 'erwachen',
    'erwähnen', 'erwarten', 'erwecken', 'erweisen', 'erzwingen', 'existieren',
    'experimentieren', 'exportieren',
  ],

  b2: [
    'abbremsen', 'abdanken', 'abdrücken', 'abfahren', 'abfeuern', 'abfliegen',
    'abgrenzen', 'abhalten', 'abheben', 'abholen', 'abhören', 'abkommen',
    'abkühlen', 'abladen', 'ableiten', 'ablösen', 'abmelden', 'abmessen',
    'abonnieren', 'abräumen', 'abreiben', 'abreisen', 'abreißen', 'abrutschen',
    'abscheuern', 'abschleppen', 'abschrecken', 'abschreiben', 'abschweifen',
    'absegnen', 'absenden', 'absichern', 'absolvieren', 'abspalten', 'abspielen',
    'absprechen', 'abstammen', 'abstempeln', 'abstoßen', 'absuchen', 'abtasten',
    'abtrainieren', 'abtrocknen', 'abwägen', 'abwandeln', 'abwarten', 'abwaschen',
    'abwehren', 'abwerfen', 'abwickeln', 'abzählen', 'anbauen', 'anbieten',
    'anbringen', 'andeuten', 'aneignen', 'anerkennen', 'anfabrizieren', 'anfachen',
    'anfertigen', 'anfeuern', 'anfliegen', 'anfordern', 'anführen', 'angeln',
    'angreifen', 'angrenzen', 'anhäufen', 'anklagen', 'ankleben', 'ankommen',
    'ankreuzen', 'ankündigen', 'anlächeln', 'anlachen', 'anlegen', 'anlehnen',
    'anleiten', 'anliefern', 'anlocken', 'anmalen', 'anmaßen', 'anmelden',
    'annähern', 'annullieren', 'anordnen', 'anpacken', 'anpflanzen', 'anprangern',
    'anrechnen', 'anreichern', 'anreisen', 'anrennen', 'anrufen', 'ansagen',
    'ansammeln', 'anschaffen', 'anschaulich', 'anschlagen', 'anschließen',
    'anschnallen', 'anschreiben', 'ansehen', 'ansiedeln', 'ansparen', 'anspitzen',
    'ansprechen', 'anstarren', 'anstecken', 'ansteigen', 'anstellen', 'anstoßen',
    'anstreben', 'anstrengen', 'antreten', 'antworten', 'anvertrauen', 'anwachsen',
    'anweisen', 'anwenden', 'anwerben', 'anzeigen', 'anziehen', 'anzünden',
    'applaudieren', 'apportieren', 'approbieren', 'argumentieren', 'arrangieren',
    'arten', 'artikulieren', 'atmen', 'attackieren', 'auben', 'auferlegen',
    'auferstehen', 'auffahren', 'auffallen', 'auffinden', 'auffordern',
    'aufführen', 'aufgeben', 'aufgreifen', 'aufhalten', 'aufheben', 'aufholen',
    'aufklären', 'aufkommen', 'aufladen', 'auflösen', 'aufmachen', 'aufmalen',
    'aufnehmen', 'aufopfern', 'aufpassen', 'aufräumen', 'aufregen', 'aufreiben',
    'aufrichten', 'aufrufen', 'aufrunden', 'aufschlagen', 'aufschreiben',
    'aufsehen', 'aufsetzen', 'aufspannen', 'aufsparen', 'aufsperren', 'aufspielen',
    'aufspringen', 'aufstampfen', 'aufstehen', 'aufstellen', 'aufstocken',
    'auftauchen', 'auftellen', 'auftragen', 'auftreiben', 'auftreten', 'aufwachen',
    'aufwachsen', 'aufwärmen', 'aufwerten', 'aufziehen', 'ausarbeiten',
    'ausatmen', 'ausbessern', 'ausbilden', 'ausbleiben', 'ausbreiten', 'ausbrennen',
    'ausdehnen', 'ausdenken', 'ausdrücken', 'auseinandersetzen', 'auserkoren',
    'auserwählen', 'ausfahren', 'ausfallen', 'ausfertigen', 'ausfragen',
    'ausführen', 'ausgeben', 'ausgehen', 'ausgleichen', 'ausgraben', 'aushalten',
    'aushändigen', 'aushelfen', 'aushöhlen', 'auskennen', 'ausklammern',
    'auskleiden', 'auskommen', 'auskosten', 'auskuppeln', 'auslachen', 'ausladen',
    'auslagen', 'ausliefern', 'auslösen', 'ausmachen', 'ausmalen', 'ausmerzen',
    'ausmisten', 'ausmustern', 'ausnutzen', 'auspacken', 'ausprobieren',
    'auspumpen', 'ausradieren', 'ausrasten', 'ausräumen', 'ausrechnen',
    'ausreden', 'ausreichen', 'ausreisen', 'ausreißen', 'ausrichten', 'ausrotten',
    'ausrüsten', 'ausschalten', 'ausschlafen', 'ausschließen', 'ausschneiden',
    'ausschreiben', 'aussehen', 'außen', 'aussetzen', 'aussicht', 'aussiedeln',
    'aussortieren', 'aussprechen', 'ausstatten', 'aussteigen', 'ausstellen',
    'aussterben', 'ausstoßen', 'ausstrahlen', 'ausstrecken', 'aussuchen',
    'austauschen', 'austeilen', 'austragen', 'austreiben', 'austreten', 'ausüben',
    'ausverkaufen', 'auswachsen', 'auswählen', 'auswandern', 'auswärtigen',
    'ausweichen', 'ausweisen', 'auswerfen', 'auswirken', 'auszahlen', 'auszeichnen',
    'ausziehen', 'auszubilden',
  ],

  c1: [
    'abberufen', 'abbestellen', 'abbiegen', 'abbilden', 'abbinden', 'abblitzen',
    'abdrosseln', 'aberkennen', 'abfärben', 'abfinden', 'abflachen', 'abgeben',
    'abgewöhnen', 'abgleiten', 'abgöttisch', 'abgreifen', 'abhaken', 'abhandeln',
    'abheften', 'abholen', 'abirren', 'abkapseln', 'abklemmen', 'abknicken',
    'abkommandieren', 'abkoppeln', 'abkriegen', 'abkürzen', 'ablachen', 'ablaufen',
    'ablecken', 'ablegen', 'ablehnen', 'ableisten', 'ablenken', 'ablesen',
    'abliefern', 'abmachen', 'abmagern', 'abmahnung', 'abmarschieren', 'abmelden',
    'abmildern', 'abmontieren', 'abnagen', 'abnehmen', 'abnötigen', 'abnutzen',
    'abonnieren', 'abordnen', 'abpflücken', 'abputzen', 'abquälen', 'abraten',
    'abräumen', 'abrechnen', 'abriegeln', 'abringen', 'abrutschen', 'absacken',
    'absagen', 'abschaffen', 'abschalten', 'abscheiden', 'abschieben', 'abschirmen',
    'abschlachten', 'abschleifen', 'abschließen', 'abschluss', 'abschmecken',
    'abschmieren', 'abschneiden', 'abschnüren', 'abschotten', 'abschrecken',
    'abschreiben', 'abschweifen', 'absegnen', 'absetzen', 'absichern', 'absieden',
    'absitzen', 'absolut', 'absondern', 'absperren', 'abspielen', 'absprechen',
    'abspringen', 'abstammen', 'abstechen', 'abstecken', 'abstehen', 'absteigen',
    'abstellen', 'abstimmen', 'abstottern', 'abstrahlen', 'abstreifen', 'abstufen',
    'abstürzen', 'absuchen', 'abtreiben', 'abtrennen', 'abtrocknen', 'abtun',
    'abverlangen', 'abwägen', 'abwandeln', 'abwarten', 'abwaschen', 'abwechseln',
    'abwehren', 'abweichen', 'abwerfen', 'abwesend', 'abwickeln', 'abwimmeln',
    'abwürgen', 'abzahlen', 'abzäunen', 'abziehen', 'abzielen', 'abzocken',
    'ächzen', 'ackern', 'ahnden', 'ähneln', 'ahnen', 'aktivieren', 'aktualisieren',
    'alarmieren', 'album', 'alien', 'alignieren', 'allein', 'allgemein',
    'alternative', 'amateur', 'ambitioniert', 'ambulant', 'amerikanisch',
    'amnestieren', 'analysieren', 'anbahnen', 'anbändeln', 'anbehalten',
    'anbeißen', 'anbekommen', 'anbeten', 'anbieten', 'anbinden', 'anblasen',
    'anblicken', 'anbraten', 'anbrechen', 'anbrennen', 'anbringen', 'andauern',
    'andeuten', 'anecken', 'aneignen', 'anerziehen', 'anfahren', 'anfallen',
    'anfangen', 'anfassen', 'anfertigen', 'anfeuchten', 'anfeuern', 'anflehen',
    'anfliegen', 'anfordern', 'anfragen', 'anführen', 'anfüllen', 'angaffen',
    'angeben', 'angehen', 'angewöhnen', 'angleichen', 'angliedern', 'angreifen',
    'angucken', 'anhaben', 'anhalten', 'anhängen', 'anhauen', 'anheben',
    'anheften', 'anheimeln', 'anheizen', 'anherrschen', 'ankämpfen', 'ankleben',
    'ankleiden', 'anklopfen', 'anknüpfen', 'ankommen', 'ankündigen', 'ankurbeln',
    'anlächeln', 'anlachen', 'anlangen', 'anlaufen', 'anlegen', 'anleiten',
    'anlernen', 'anliefern', 'anlocken', 'anlügen', 'anmalen', 'anmaßen',
    'anmelden', 'anmerken', 'annähen', 'annehmen', 'annullieren', 'anordnen',
    'anpacken', 'anpflanzen', 'anprangern', 'anprobieren', 'anraten', 'anrechnen',
    'anregen', 'anreichern', 'anreisen', 'anrempeln', 'anrichten', 'anrufen',
    'ansagen', 'ansammeln', 'ansässig', 'anschaffen', 'anschalten', 'anschauen',
    'anscheißen', 'anschirren', 'anschlagen', 'anschleichen', 'anschließen',
    'anschnallen', 'anschneiden', 'anschreiben', 'anschreien', 'ansehen',
    'ansetzen', 'ansiedeln', 'ansparen', 'anspinnen', 'anspitzen', 'ansprechen',
    'anspringen', 'anstacheln', 'anstarren', 'anstatt', 'anstauen', 'anstecken',
    'anstehen', 'ansteigen', 'anstellen', 'anstimmen', 'anstoßen', 'anstreben',
    'anstreichen', 'anstrengen', 'anstückeln', 'antanzen', 'antasten', 'antelefonieren',
    'antippen', 'antragen', 'antreffen', 'antreiben', 'antreten', 'antun',
    'anvertrauen', 'anwachsen', 'anwählen', 'anwärmen', 'anweisen', 'anwenden',
    'anwerben', 'anwesend', 'anwidern', 'anzeigen', 'anziehen', 'anzünden',
    'appellieren', 'approbieren', 'apropos', 'arbeiten', 'argumentieren',
    'arrangieren', 'arretieren', 'artikulieren', 'attackieren', 'ätzen',
    'aufatmen', 'aufbahren', 'aufbauen', 'aufbäumen', 'aufbessern', 'aufbewahren',
    'aufbiegen', 'aufbinden', 'aufblasen', 'aufblättern', 'aufblühen',
    'aufbrechen', 'aufbringen', 'aufdecken', 'aufdrehen', 'aufdringen',
    'aufeinander', 'aufessen', 'auffädeln', 'auffahren', 'auffallen', 'auffangen',
    'auffassen', 'auffichten', 'auffinden', 'auffliegen', 'auffordern',
    'auffressen', 'aufführen', 'aufgeben', 'aufgehen', 'aufgießen', 'aufgreifen',
    'aufhalten', 'aufhängen', 'aufhäufen', 'aufheben', 'aufheitern', 'aufhelfen',
    'aufhellen', 'aufhetzen', 'aufhorchen', 'aufhören', 'aufkaufen', 'aufklappen',
    'aufklären', 'aufkleben', 'aufkommen', 'aufkündigen', 'auflachen', 'aufladen',
    'auflauern', 'auflaufen', 'aufleben', 'auflegen', 'auflehnen', 'auflisten',
    'auflockern', 'auflösen', 'aufmachen', 'aufmarschieren', 'aufmerksam',
    'aufmuntern', 'aufnehmen', 'aufnötigen', 'aufopfern', 'aufpacken', 'aufpassen',
    'aufpflanzen', 'aufplustern', 'aufpolieren', 'aufprägen', 'aufputschen',
    'aufraffen', 'aufräumen', 'aufrechnen', 'aufrecht', 'aufregen', 'aufreiben',
    'aufreißen', 'aufrichten', 'aufrollen', 'aufrücken', 'aufrufen', 'aufrunden',
    'aufrüsten', 'aufrütteln', 'aufsagen', 'aufsammeln', 'aufschichten',
    'aufschieben', 'aufschlagen', 'aufschließen', 'aufschlitzen', 'aufschneiden',
    'aufschreiben', 'aufschreien', 'aufschürfen', 'aufschwimmen', 'aufsehen',
    'aufsetzen', 'aufsitzen', 'aufspannen', 'aufsparen', 'aufsperren', 'aufspielen',
    'aufsprengen', 'aufspringen', 'aufspüren', 'aufstacheln', 'aufstampfen',
    'aufstauen', 'aufstechen', 'aufstehen', 'aufsteigen', 'aufstellen',
    'aufstocken', 'aufstöhnen', 'aufstülpen', 'aufsuchen', 'auftanken', 'auftauchen',
    'auftauen', 'aufteilen', 'auftischen', 'auftragen', 'auftreffen', 'auftreiben',
    'auftreten', 'auftrumpfen', 'auftun', 'aufwachen', 'aufwachsen', 'aufwallen',
    'aufwärmen', 'aufwarten', 'aufwärts', 'aufwecken', 'aufweichen', 'aufweisen',
    'aufwenden', 'aufwerfen', 'aufwickeln', 'aufwiegen', 'aufwischen', 'aufwühlen',
    'aufzählen', 'aufzeichnen', 'aufziehen', 'aufzwingen', 'ausbaden', 'ausbaggern',
    'ausbauen', 'ausbessern', 'ausbeuten', 'ausbilden', 'ausbleiben', 'ausblenden',
    'ausbrechen', 'ausbreiten', 'ausbrennen', 'ausbringen', 'ausbügeln', 'ausbürgern',
    'ausdehnen', 'ausdenken', 'ausdrehen', 'ausdünsten', 'auseinander',
    'auserwählen', 'ausfahren', 'ausfallen', 'ausfeilen', 'ausfertigen',
    'ausfragen', 'ausführen', 'ausfüllen', 'ausgären', 'ausgeben', 'ausgehen',
    'ausgießen', 'ausgleichen', 'ausgraben', 'ausgrenzen', 'aushalten', 'aushändigen',
    'ausharren', 'ausheben', 'aushelfen', 'aushöhlen', 'ausholen', 'auskennen',
    'ausklammern', 'auskleiden', 'ausklingen', 'ausknipsen', 'auskommen',
    'auskosten', 'auskratzen', 'auskugeln', 'auskuppeln', 'auslachen', 'ausladen',
    'auslagern', 'auslangen', 'auslassen', 'auslaufen', 'auslegen', 'ausleihen',
    'ausliefern', 'auslöschen', 'auslösen', 'ausmachen', 'ausmalen', 'ausmerzen',
    'ausmessen', 'ausmustern', 'ausnehmen', 'ausnutzen', 'auspacken', 'auspowern',
    'ausprobieren', 'auspumpen', 'ausquartieren', 'ausquetschen', 'ausradieren',
    'ausrangieren', 'ausrasten', 'ausrauben', 'ausräumen', 'ausrechnen', 'ausrecken',
    'ausreden', 'ausreichen', 'ausreisen', 'ausreißen', 'ausrenken', 'ausrichten',
    'ausrotten', 'ausrücken', 'ausrufen', 'ausruhen', 'ausrüsten', 'ausrutschen',
    'aussäen', 'aussagen', 'ausschachten', 'ausschalten', 'ausscheiden',
    'ausschenken', 'ausschimpfen', 'ausschlafen', 'ausschlagen', 'ausschleusen',
    'ausschließen', 'ausschlüpfen', 'ausschmücken', 'ausschneiden', 'ausschöpfen',
    'ausschreiben', 'ausschreiten', 'aussehen', 'außen', 'aussetzen', 'aussiedeln',
    'aussöhnen', 'aussondern', 'aussortieren', 'ausspannen', 'aussparen',
    'aussperren', 'ausspielen', 'aussprechen', 'ausspucken', 'ausstaffieren',
    'ausstatten', 'ausstechen', 'ausstehen', 'aussteigen', 'ausstellen',
    'aussterben', 'ausstiefeln', 'ausstoßen', 'ausstrahlen', 'ausstrecken',
    'ausstreuen', 'ausströmen', 'aussuchen', 'austanzen', 'austauschen',
    'austeilen', 'austragen', 'austreiben', 'austreten', 'austricksen', 'ausüben',
    'ausverkaufen', 'auswachsen', 'auswählen', 'auswalzen', 'auswandern',
    'auswärtig', 'auswaschen', 'auswechseln', 'ausweichen', 'ausweisen',
    'ausweiten', 'auswerfen', 'auswerten', 'auswirken', 'auswischen', 'auszahlen',
    'auszanken', 'auszehren', 'auszeichnen', 'ausziehen', 'auszischen',
  ],

  c2: [
    'abdanken', 'abdingen', 'abebben', 'aberziehen', 'abfeiern', 'abfeilschen',
    'abgabenfrei', 'abgelten', 'abgewöhnen', 'abgöttisch', 'abgrenzen', 'abhalten',
    'abheben', 'abhetzen', 'abholzen', 'abjagen', 'abkanzeln', 'abkaufen',
    'abklatschen', 'abklingen', 'abknallen', 'abknöpfen', 'abkommandieren',
    'abkoppeln', 'abkriegen', 'abkühlen', 'abkürzen', 'abladen', 'ablaufen',
    'ablegen', 'ablehnen', 'ableisten', 'ablenken', 'ablesen', 'abliefern',
    'abmachen', 'abmagern', 'abmahnung', 'abmelden', 'abmessen', 'abmontieren',
    'abmühen', 'abnagen', 'abnehmen', 'abnicken', 'abnötigen', 'abnutzen',
    'abonnieren', 'abqualifizieren', 'abquälen', 'abrackern', 'abraten',
    'abräumen', 'abreagieren', 'abrechnen', 'abreiben', 'abreisen', 'abreißen',
    'abrichten', 'abriegeln', 'abringen', 'abrollen', 'abrücken', 'abrufen',
    'abrunden', 'abrüsten', 'abrutschen', 'absahnen', 'absägen', 'absatteln',
    'abschaffen', 'abschalten', 'abschätzen', 'abscheren', 'abschieben',
    'abschirmen', 'abschlachten', 'abschleifen', 'abschleppen', 'abschließen',
    'abschmecken', 'abschmieren', 'abschminken', 'abschnallen', 'abschneiden',
    'abschnüren', 'abschotten', 'abschrägen', 'abschrecken', 'abschreiben',
    'abschreiten', 'abschuppen', 'abschütteln', 'abschwächen', 'abschweifen',
    'abschwellen', 'abschwören', 'absegnen', 'absenken', 'absetzen', 'absichern',
    'absinken', 'absitzen', 'absondern', 'absorberen', 'abspeichern', 'absperren',
    'abspielen', 'absprechen', 'abspringen', 'abspülen', 'abstammen', 'abstechen',
    'abstecken', 'abstehen', 'absteigen', 'abstellen', 'abstempeln', 'absterben',
    'abstimmen', 'abstottern', 'abstoßen', 'abstottern', 'abstrahlen', 'abstreifen',
    'abstufen', 'abstumpfen', 'abstürzen', 'absuchen', 'abtanzen', 'abtasten',
    'abteilen', 'abtippen', 'abtragen', 'abtreiben', 'abtrennen', 'abtreten',
    'abtrocknen', 'abtropfen', 'abtun', 'abverlangen', 'abwägen', 'abwählen',
    'abwandeln', 'abwandern', 'abwarten', 'abwaschen', 'abwechseln', 'abwegen',
    'abwehren', 'abweichen', 'abweiden', 'abwerben', 'abwerfen', 'abwerten',
    'abwesend', 'abwickeln', 'abwimmeln', 'abwinken', 'abwirtschaften',
    'abwischen', 'abwürgen', 'abzahlen', 'abzapfen', 'abzäunen', 'abzehren',
    'abzeichnen', 'abziehen', 'abzielen', 'abzocken', 'abzüglich', 'ächzen',
    'ackern', 'ahnden', 'ähneln', 'ahnen', 'akklamieren', 'akkreditieren',
    'aktien', 'aktivieren', 'aktualisieren', 'akzeptieren', 'alarmieren',
    'alimentieren', 'alkylieren', 'amateurhaft', 'ambitioniert', 'ambulant',
    'ameliorieren', 'amnestieren', 'amortisieren', 'ampeln', 'amputieren',
    'analysieren', 'anbahnen', 'anbändeln', 'anbehalten', 'anbeißen', 'anbeten',
    'anbiedern', 'anbieten', 'anbinden', 'anblaffen', 'anblasen', 'anblicken',
    'anbraten', 'anbrechen', 'anbrennen', 'anbringen', 'anbrüllen', 'andauern',
    'andeuten', 'anecken', 'aneignen', 'anerkennen', 'anfahren', 'anfallen',
    'anfangen', 'anfassen', 'anfertigen', 'anfeuchten', 'anfeuern', 'anflehen',
    'anfliegen', 'anfordern', 'anfragen', 'anführen', 'anfüllen', 'angaffen',
    'angeben', 'angehen', 'angewöhnen', 'angleichen', 'angliedern', 'angreifen',
    'angrenzen', 'angucken', 'anhaben', 'anhalten', 'anhängen', 'anhauen',
    'anheben', 'anheften', 'anheimeln', 'anheizen', 'anherrschen', 'anhäufen',
    'ankämpfen', 'ankleben', 'ankleiden', 'anklopfen', 'anknüpfen', 'ankommen',
    'ankündigen', 'ankurbeln', 'anlächeln', 'anlachen', 'anlangen', 'anlassen',
    'anlaufen', 'anlegen', 'anleiten', 'anlernen', 'anliefern', 'anlocken',
    'anlügen', 'anmalen', 'anmaßen', 'anmelden', 'anmerken', 'annähen',
    'annehmen', 'annullieren', 'anordnen', 'anpacken', 'anpassen', 'anpflanzen',
    'anprangern', 'anpreisen', 'anprobieren', 'anraten', 'anrechnen', 'anregen',
    'anreichern', 'anreisen', 'anrempeln', 'anrichten', 'anrufen', 'ansagen',
    'ansammeln', 'anschaffen', 'anschalten', 'anschauen', 'anschirren',
    'anschlagen', 'anschleichen', 'anschließen', 'anschnallen', 'anschneiden',
    'anschreiben', 'anschreien', 'ansehen', 'ansetzen', 'ansiedeln', 'ansparen',
    'anspitzen', 'ansprechen', 'anspringen', 'anstacheln', 'anstarren',
    'anstauen', 'anstecken', 'anstehen', 'ansteigen', 'anstellen', 'anstimmen',
    'anstoßen', 'anstreben', 'anstreichen', 'anstrengen', 'antasten', 'antippen',
    'antragen', 'antreffen', 'antreiben', 'antreten', 'antun', 'anvertrauen',
    'anwachsen', 'anwählen', 'anwärmen', 'anweisen', 'anwenden', 'anwerben',
    'anwidern', 'anzeigen', 'anziehen', 'anzünden', 'appellieren', 'approbieren',
    'arbeiten', 'argumentieren', 'arrangieren', 'arretieren', 'assimilieren',
    'attackieren', 'ätzen', 'aufbahren', 'aufbauen', 'aufbäumen', 'aufbessern',
    'aufbewahren', 'aufbinden', 'aufblasen', 'aufblähen', 'aufblättern',
    'aufblitzen', 'aufblühen', 'aufbrauchen', 'aufbrechen', 'aufbringen',
    'aufdecken', 'aufdrehen', 'aufdrucken', 'aufdunsen', 'aufeinander',
    'aufessen', 'auffädeln', 'auffahren', 'auffallen', 'auffangen', 'auffassen',
    'auffinden', 'auffliegen', 'auffordern', 'auffressen', 'auffrischen',
    'aufführen', 'aufgeben', 'aufgehen', 'aufgießen', 'aufgreifen', 'aufhalten',
    'aufhängen', 'aufhäufen', 'aufheben', 'aufheitern', 'aufhelfen', 'aufhellen',
    'aufhetzen', 'aufhorchen', 'aufhören', 'aufkaufen', 'aufklappen', 'aufklären',
    'aufkleben', 'aufkommen', 'aufkündigen', 'auflachen', 'aufladen', 'auflauern',
    'auflaufen', 'aufleben', 'auflegen', 'auflehnen', 'auflisten', 'auflockern',
    'auflösen', 'aufmachen', 'aufmarschieren', 'aufmuntern', 'aufnehmen',
    'aufnötigen', 'aufopfern', 'aufpacken', 'aufpassen', 'aufpflanzen',
    'aufplustern', 'aufpolieren', 'aufputschen', 'aufraffen', 'aufräumen',
    'aufrechnen', 'aufregen', 'aufreiben', 'aufreißen', 'aufrichten', 'aufrollen',
    'aufrücken', 'aufrufen', 'aufrunden', 'aufrüsten', 'aufrütteln', 'aufsagen',
    'aufsammeln', 'aufschichten', 'aufschieben', 'aufschlagen', 'aufschließen',
    'aufschlitzen', 'aufschneiden', 'aufschreiben', 'aufschreien', 'aufschürfen',
    'aufschwimmen', 'aufschwingen', 'aufsehen', 'aufsetzen', 'aufsitzen',
    'aufspannen', 'aufsparen', 'aufsperren', 'aufspielen', 'aufsprengen',
    'aufspringen', 'aufspüren', 'aufstacheln', 'aufstampfen', 'aufstauen',
    'aufstechen', 'aufstehen', 'aufsteigen', 'aufstellen', 'aufstocken',
    'aufstöhnen', 'aufsuchen', 'auftanken', 'auftauchen', 'auftauen', 'aufteilen',
    'auftischen', 'auftragen', 'auftreffen', 'auftreiben', 'auftreten',
    'auftrumpfen', 'auftun', 'aufwachen', 'aufwachsen', 'aufwallen', 'aufwärmen',
    'aufwarten', 'aufwecken', 'aufweichen', 'aufweisen', 'aufwenden', 'aufwerfen',
    'aufwickeln', 'aufwiegen', 'aufwischen', 'aufwühlen', 'aufzählen',
    'aufzeichnen', 'aufziehen', 'aufzwingen', 'ausbaden', 'ausbaggern',
    'ausbauen', 'ausbessern', 'ausbeuten', 'ausbilden', 'ausbleiben', 'ausblenden',
    'ausbrechen', 'ausbreiten', 'ausbrennen', 'ausbringen', 'ausdehnen',
    'ausdenken', 'ausdrehen', 'ausdünsten', 'auserwählen', 'ausfahren',
    'ausfallen', 'ausfertigen', 'ausfragen', 'ausführen', 'ausfüllen', 'ausgeben',
    'ausgehen', 'ausgießen', 'ausgleichen', 'ausgraben', 'ausgrenzen', 'aushalten',
    'aushändigen', 'ausharren', 'ausheben', 'aushelfen', 'aushöhlen', 'ausholen',
    'auskennen', 'ausklammern', 'auskleiden', 'ausklingen', 'auskommen',
    'auskosten', 'auskratzen', 'auslachen', 'ausladen', 'auslagern', 'auslassen',
    'auslaufen', 'auslegen', 'ausleihen', 'ausliefern', 'auslöschen', 'auslösen',
    'ausmachen', 'ausmalen', 'ausmerzen', 'ausmessen', 'ausnehmen', 'ausnutzen',
    'auspacken', 'ausprobieren', 'auspumpen', 'ausradieren', 'ausrasten',
    'ausrauben', 'ausräumen', 'ausrechnen', 'ausreden', 'ausreichen', 'ausreisen',
    'ausreißen', 'ausrenken', 'ausrichten', 'ausrotten', 'ausrücken', 'ausrufen',
    'ausruhen', 'ausrüsten', 'ausrutschen', 'aussäen', 'aussagen', 'ausschalten',
    'ausscheiden', 'ausschenken', 'ausschimpfen', 'ausschlafen', 'ausschlagen',
    'ausschleusen', 'ausschließen', 'ausschlüpfen', 'ausschmücken', 'ausschneiden',
    'ausschöpfen', 'ausschreiben', 'ausschreiten', 'aussehen', 'aussetzen',
    'aussiedeln', 'aussöhnen', 'aussondern', 'aussortieren', 'ausspannen',
    'aussparen', 'aussperren', 'ausspielen', 'aussprechen', 'ausspucken',
    'ausstatten', 'ausstechen', 'ausstehen', 'aussteigen', 'ausstellen',
    'aussterben', 'ausstoßen', 'ausstrahlen', 'ausstrecken', 'ausstreuen',
    'ausströmen', 'aussuchen', 'austauschen', 'austeilen', 'austragen',
    'austreiben', 'austreten', 'ausüben', 'ausverkaufen', 'auswachsen',
    'auswählen', 'auswalzen', 'auswandern', 'auswaschen', 'auswechseln',
    'ausweichen', 'ausweisen', 'ausweiten', 'auswerfen', 'auswerten', 'auswirken',
    'auswischen', 'auszahlen', 'auszeichnen', 'ausziehen', 'autorisieren',
    'avancieren', 'avoisieren', 'ächzen', 'äußern',
  ],
}

const levelIndex = new Map<string, string>()
for (const [level, verbs] of Object.entries(verbsByLevel)) {
  for (const verb of verbs) {
    levelIndex.set(verb.toLowerCase(), level)
  }
}

export function getCEFRLevel(infinitive: string): string | null {
  return levelIndex.get(infinitive.toLowerCase()) ?? null
}

export function getVerbsByLevel(level: string): string[] {
  return verbsByLevel[level.toLowerCase()] ?? []
}

export function getAllVerbs(): { infinitive: string; level: string }[] {
  const result: { infinitive: string; level: string }[] = []
  for (const [level, verbs] of Object.entries(verbsByLevel)) {
    for (const verb of verbs) {
      result.push({ infinitive: verb, level })
    }
  }
  return result
}
