export type { SourceAdapter, SourceVerbEntry, FetchResult, ScrapeMeta } from './types'
export { getAdapter, getAvailableSources } from './registry'
export { VerbformenAdapter } from './verbformen'
export { WiktionaryAdapter } from './wiktionary'
export { CanoonetAdapter } from './canoonet'
export { CustomJsonAdapter } from './custom-json'
export { getCEFRLevel, getVerbsByLevel, getAllVerbs } from './german-verbs-list'
export { withConcurrencyLimit } from './concurrency'
