/**
 * Database Seeder
 * 
 * Seeds Arabic content from JSON files into Supabase.
 * Run with: npx tsx scripts/seed-database.ts
 * 
 * Expects JSON files in scripts/output/ generated by generate-content.ts
 * Or reads directly from existing migration data.
 */

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase environment variables')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { autoRefreshToken: false, persistSession: false },
})

interface VocabItem {
  language: string
  german_word: string
  english_translation: string
  transliteration?: string
  word_type?: string
  level: string
  category?: string
  example_sentence?: string
  example_translation?: string
  difficulty?: number
  tags?: string[]
  article?: string | null
  plural?: string | null
}

interface Expression {
  language: string
  german: string
  english: string
  transliteration?: string
  usage_context?: string
  level: string
  category?: string
  audio_url?: string | null
}

async function seedVocabulary(items: VocabItem[]) {
  console.log(`Seeding ${items.length} vocabulary items...`)
  let count = 0
  for (const item of items) {
    const { error } = await supabase.from('vocabulary').upsert({
      language: item.language,
      german_word: item.german_word,
      english_translation: item.english_translation,
      transliteration: item.transliteration || null,
      word_type: item.word_type || null,
      level: item.level,
      category: item.category || null,
      example_sentence: item.example_sentence || null,
      example_translation: item.example_translation || null,
      difficulty: item.difficulty || 1,
      tags: item.tags || [],
    }, { onConflict: 'language,german_word' })
    if (error) {
      console.error(`Error inserting ${item.german_word}:`, error.message)
    } else {
      count++
    }
  }
  console.log(`✓ Seeded ${count} vocabulary items`)
}

async function seedExpressions(items: Expression[]) {
  console.log(`Seeding ${items.length} expressions...`)
  let count = 0
  for (const item of items) {
    const { error } = await supabase.from('expressions').upsert({
      language: item.language,
      german: item.german,
      english: item.english,
      transliteration: item.transliteration || null,
      usage_context: item.usage_context || null,
      level: item.level,
      category: item.category || null,
    }, { onConflict: 'language,german' })
    if (error) {
      console.error(`Error inserting ${item.german}:`, error.message)
    } else {
      count++
    }
  }
  console.log(`✓ Seeded ${count} expressions`)
}

async function main() {
  console.log('Starting database seed...\n')

  // Seed basic Arabic greetings as expressions
  await seedExpressions([
    { language: 'ar', german: 'السلام عليكم', english: 'Peace be upon you', transliteration: 'al-salāmu ʿalaykum', usage_context: 'Formal Islamic greeting', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'وعليكم السلام', english: 'And upon you be peace', transliteration: 'wa-ʿalaykum al-salām', usage_context: 'Reply to greeting', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'أهلاً وسهلاً', english: 'Welcome', transliteration: 'ahlan wa-sahlan', usage_context: 'Warm welcome', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'صباح الخير', english: 'Good morning', transliteration: 'ṣabāḥ al-khayr', usage_context: 'Morning greeting', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'مساء الخير', english: 'Good evening', transliteration: 'masā\' al-khayr', usage_context: 'Evening greeting', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'كيف حالك؟', english: 'How are you?', transliteration: 'kayfa ḥāluka', usage_context: 'Asking about well-being', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'شكراً', english: 'Thank you', transliteration: 'shukran', usage_context: 'Expressing gratitude', level: 'A1', category: 'politeness' },
    { language: 'ar', german: 'عفواً', english: 'You\'re welcome', transliteration: 'ʿafwan', usage_context: 'Responding to thanks', level: 'A1', category: 'politeness' },
    { language: 'ar', german: 'من فضلك', english: 'Please', transliteration: 'min faḍlik', usage_context: 'Making a polite request', level: 'A1', category: 'politeness' },
    { language: 'ar', german: 'الحمد لله', english: 'Praise be to God', transliteration: 'al-ḥamdu lillāh', usage_context: 'Expression of gratitude or relief', level: 'A1', category: 'religion' },
    { language: 'ar', german: 'إن شاء الله', english: 'God willing', transliteration: 'in shā\' allāh', usage_context: 'Speaking about future plans', level: 'A1', category: 'religion' },
    { language: 'ar', german: 'ما شاء الله', english: 'What God has willed', transliteration: 'mā shā\' allāh', usage_context: 'Expression of admiration', level: 'A1', category: 'religion' },
    { language: 'ar', german: 'بسم الله', english: 'In the name of God', transliteration: 'bismi llāh', usage_context: 'Before starting any action', level: 'A1', category: 'religion' },
    { language: 'ar', german: 'إلى اللقاء', english: 'See you later', transliteration: 'ilā al-liqā\'', usage_context: 'Formal goodbye', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'مع السلامة', english: 'Goodbye (with peace)', transliteration: 'maʿa al-salāmah', usage_context: 'Saying goodbye', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'أهلاً', english: 'Hi', transliteration: 'ahlan', usage_context: 'Informal greeting', level: 'A1', category: 'greeting' },
    { language: 'ar', german: 'نعم', english: 'Yes', transliteration: 'naʿam', usage_context: 'Agreement', level: 'A1', category: 'basic' },
    { language: 'ar', german: 'لا', english: 'No', transliteration: 'lā', usage_context: 'Refusal', level: 'A1', category: 'basic' },
    { language: 'ar', german: 'تمام', english: 'Perfect / OK', transliteration: 'tamām', usage_context: 'Confirmation', level: 'A1', category: 'basic' },
    { language: 'ar', german: 'ممكن', english: 'Possible / May I?', transliteration: 'mumkin', usage_context: 'Asking permission', level: 'A1', category: 'basic' },
    { language: 'ar', german: 'مبروك', english: 'Congratulations', transliteration: 'mabrūk', usage_context: 'Happy occasions', level: 'A2', category: 'everyday' },
    { language: 'ar', german: 'بالتوفيق', english: 'Good luck', transliteration: 'bil-tawfīq', usage_context: 'Wishing success', level: 'A2', category: 'everyday' },
  ])

  // Seed Arabic vocabulary (basic words)
  await seedVocabulary([
    // Family
    { language: 'ar', german_word: 'أب', english_translation: 'father', transliteration: 'ab', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'أبي طبيب', example_translation: 'My father is a doctor', difficulty: 1, tags: ['family', 'basic'] },
    { language: 'ar', german_word: 'أم', english_translation: 'mother', transliteration: 'umm', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'أمي معلمة', example_translation: 'My mother is a teacher', difficulty: 1, tags: ['family', 'basic'] },
    { language: 'ar', german_word: 'أخ', english_translation: 'brother', transliteration: 'akh', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'أخي كبير', example_translation: 'My brother is older', difficulty: 1, tags: ['family', 'basic'] },
    { language: 'ar', german_word: 'أخت', english_translation: 'sister', transliteration: 'ukht', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'أختي صغيرة', example_translation: 'My sister is young', difficulty: 1, tags: ['family', 'basic'] },
    { language: 'ar', german_word: 'جد', english_translation: 'grandfather', transliteration: 'jadd', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'جدي كبير', example_translation: 'My grandfather is old', difficulty: 1, tags: ['family'] },
    { language: 'ar', german_word: 'جدة', english_translation: 'grandmother', transliteration: 'jaddah', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'جدتي لطيفة', example_translation: 'My grandmother is kind', difficulty: 1, tags: ['family'] },
    { language: 'ar', german_word: 'ابن', english_translation: 'son', transliteration: 'ibn', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'ابني صغير', example_translation: 'My son is young', difficulty: 1, tags: ['family'] },
    { language: 'ar', german_word: 'ابنة', english_translation: 'daughter', transliteration: 'ibnah', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'ابنتي جميلة', example_translation: 'My daughter is beautiful', difficulty: 1, tags: ['family'] },
    { language: 'ar', german_word: 'زوج', english_translation: 'husband', transliteration: 'zawj', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'زوجي مهندس', example_translation: 'My husband is an engineer', difficulty: 1, tags: ['family'] },
    { language: 'ar', german_word: 'زوجة', english_translation: 'wife', transliteration: 'zawjah', word_type: 'noun', level: 'A1', category: 'family', example_sentence: 'زوجتي طبيبة', example_translation: 'My wife is a doctor', difficulty: 1, tags: ['family'] },
    // Food
    { language: 'ar', german_word: 'خبز', english_translation: 'bread', transliteration: 'khubz', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الخبز طازج', example_translation: 'The bread is fresh', difficulty: 1, tags: ['food', 'basic'] },
    { language: 'ar', german_word: 'ماء', english_translation: 'water', transliteration: 'mā\'', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الماء بارد', example_translation: 'The water is cold', difficulty: 1, tags: ['food', 'basic'] },
    { language: 'ar', german_word: 'لحم', english_translation: 'meat', transliteration: 'lahm', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'اللحم طازج', example_translation: 'The meat is fresh', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'دجاج', english_translation: 'chicken', transliteration: 'dajāj', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الدجاج لذيذ', example_translation: 'The chicken is delicious', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'سمك', english_translation: 'fish', transliteration: 'samak', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'السمك طازج', example_translation: 'The fish is fresh', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'أرز', english_translation: 'rice', transliteration: 'aruzz', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الأرز أبيض', example_translation: 'The rice is white', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'تفاح', english_translation: 'apple', transliteration: 'tuffāḥ', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'التفاح أحمر', example_translation: 'The apple is red', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'موز', english_translation: 'banana', transliteration: 'mawz', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الموز أصفر', example_translation: 'The banana is yellow', difficulty: 1, tags: ['food'] },
    { language: 'ar', german_word: 'لبن', english_translation: 'milk', transliteration: 'laban', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'اللبن بارد', example_translation: 'The milk is cold', difficulty: 1, tags: ['food', 'basic'] },
    { language: 'ar', german_word: 'جبن', english_translation: 'cheese', transliteration: 'jubn', word_type: 'noun', level: 'A1', category: 'food', example_sentence: 'الجبن لذيذ', example_translation: 'The cheese is delicious', difficulty: 1, tags: ['food'] },
    // Colors
    { language: 'ar', german_word: 'أحمر', english_translation: 'red', transliteration: 'aḥmar', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الوردة حمراء', example_translation: 'The rose is red', difficulty: 1, tags: ['colors'] },
    { language: 'ar', german_word: 'أزرق', english_translation: 'blue', transliteration: 'azraq', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'البحر أزرق', example_translation: 'The sea is blue', difficulty: 1, tags: ['colors'] },
    { language: 'ar', german_word: 'أصفر', english_translation: 'yellow', transliteration: 'aṣfar', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الشمس صفراء', example_translation: 'The sun is yellow', difficulty: 1, tags: ['colors'] },
    { language: 'ar', german_word: 'أخضر', english_translation: 'green', transliteration: 'akhḍar', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'العشب أخضر', example_translation: 'The grass is green', difficulty: 1, tags: ['colors'] },
    { language: 'ar', german_word: 'أسود', english_translation: 'black', transliteration: 'aswad', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الليل أسود', example_translation: 'The night is black', difficulty: 1, tags: ['colors'] },
    { language: 'ar', german_word: 'أبيض', english_translation: 'white', transliteration: 'abyaḍ', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الثلج أبيض', example_translation: 'The snow is white', difficulty: 1, tags: ['colors'] },
    // Basic adjectives
    { language: 'ar', german_word: 'كبير', english_translation: 'big/large', transliteration: 'kabīr', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'البيت كبير', example_translation: 'The house is big', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'صغير', english_translation: 'small', transliteration: 'ṣaghīr', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'القطة صغيرة', example_translation: 'The cat is small', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'طويل', english_translation: 'tall/long', transliteration: 'ṭawīl', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الرجل طويل', example_translation: 'The man is tall', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'قصير', english_translation: 'short', transliteration: 'qaṣīr', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الشعر قصير', example_translation: 'The hair is short', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'جديد', english_translation: 'new', transliteration: 'jadīd', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'هذا جديد', example_translation: 'This is new', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'قديم', english_translation: 'old', transliteration: 'qadīm', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'هذا قديم', example_translation: 'This is old', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'جميل', english_translation: 'beautiful', transliteration: 'jamīl', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'المنظر جميل', example_translation: 'The view is beautiful', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'قوي', english_translation: 'strong', transliteration: 'qawī', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'الرجل قوي', example_translation: 'The man is strong', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'سريع', english_translation: 'fast', transliteration: 'sarīʿ', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'السيارة سريعة', example_translation: 'The car is fast', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'بطيء', english_translation: 'slow', transliteration: 'baṭī\'', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'السلحفاة بطيئة', example_translation: 'The turtle is slow', difficulty: 1, tags: ['basic'] },
    // Greetings & basics
    { language: 'ar', german_word: 'مرحباً', english_translation: 'hello', transliteration: 'marḥaban', word_type: 'expression', level: 'A1', category: 'daily_life', example_sentence: 'مرحباً كيف حالك؟', example_translation: 'Hello, how are you?', difficulty: 1, tags: ['greeting', 'basic'] },
    { language: 'ar', german_word: 'نعم', english_translation: 'yes', transliteration: 'naʿam', word_type: 'adverb', level: 'A1', category: 'daily_life', example_sentence: 'نعم أنا موافق', example_translation: 'Yes, I agree', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'لا', english_translation: 'no', transliteration: 'lā', word_type: 'adverb', level: 'A1', category: 'daily_life', example_sentence: 'لا شكراً', example_translation: 'No, thank you', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'شكراً', english_translation: 'thank you', transliteration: 'shukran', word_type: 'expression', level: 'A1', category: 'daily_life', example_sentence: 'شكراً جزيلاً', example_translation: 'Thank you very much', difficulty: 1, tags: ['polite'] },
    // Daily objects
    { language: 'ar', german_word: 'بيت', english_translation: 'house', transliteration: 'bayt', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'البيت جميل', example_translation: 'The house is beautiful', difficulty: 1, tags: ['daily'] },
    { language: 'ar', german_word: 'باب', english_translation: 'door', transliteration: 'bāb', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'الباب مفتوح', example_translation: 'The door is open', difficulty: 1, tags: ['daily'] },
    { language: 'ar', german_word: 'نافذة', english_translation: 'window', transliteration: 'nāfidhah', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'النافذة واسعة', example_translation: 'The window is wide', difficulty: 1, tags: ['daily'] },
    { language: 'ar', german_word: 'كرسي', english_translation: 'chair', transliteration: 'kursī', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'الكرسي مريح', example_translation: 'The chair is comfortable', difficulty: 1, tags: ['daily'] },
    { language: 'ar', german_word: 'طاولة', english_translation: 'table', transliteration: 'ṭāwilah', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'الطاولة خشبية', example_translation: 'The table is wooden', difficulty: 1, tags: ['daily'] },
    { language: 'ar', german_word: 'مفتاح', english_translation: 'key', transliteration: 'miftāḥ', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'المفتاح صغير', example_translation: 'The key is small', difficulty: 1, tags: ['daily'] },
    // Travel
    { language: 'ar', german_word: 'سيارة', english_translation: 'car', transliteration: 'sayyārah', word_type: 'noun', level: 'A1', category: 'travel', example_sentence: 'السيارة حمراء', example_translation: 'The car is red', difficulty: 1, tags: ['travel'] },
    { language: 'ar', german_word: 'طائرة', english_translation: 'airplane', transliteration: 'ṭā\'irah', word_type: 'noun', level: 'A1', category: 'travel', example_sentence: 'الطائرة تطير', example_translation: 'The airplane flies', difficulty: 1, tags: ['travel'] },
    { language: 'ar', german_word: 'قطار', english_translation: 'train', transliteration: 'qiṭār', word_type: 'noun', level: 'A1', category: 'travel', example_sentence: 'القطار سريع', example_translation: 'The train is fast', difficulty: 1, tags: ['travel'] },
    { language: 'ar', german_word: 'مطار', english_translation: 'airport', transliteration: 'maṭār', word_type: 'noun', level: 'A1', category: 'travel', example_sentence: 'المطار كبير', example_translation: 'The airport is big', difficulty: 1, tags: ['travel'] },
    { language: 'ar', german_word: 'فندق', english_translation: 'hotel', transliteration: 'funduq', word_type: 'noun', level: 'A1', category: 'travel', example_sentence: 'الفندق جميل', example_translation: 'The hotel is beautiful', difficulty: 1, tags: ['travel'] },
    // Body parts
    { language: 'ar', german_word: 'رأس', english_translation: 'head', transliteration: 'ra\'s', word_type: 'noun', level: 'A1', category: 'health', example_sentence: 'رأسي يؤلمني', example_translation: 'My head hurts', difficulty: 1, tags: ['body'] },
    { language: 'ar', german_word: 'يد', english_translation: 'hand', transliteration: 'yad', word_type: 'noun', level: 'A1', category: 'health', example_sentence: 'يدي نظيفة', example_translation: 'My hand is clean', difficulty: 1, tags: ['body'] },
    { language: 'ar', german_word: 'عين', english_translation: 'eye', transliteration: 'ʿayn', word_type: 'noun', level: 'A1', category: 'health', example_sentence: 'عيني جميلة', example_translation: 'My eyes are beautiful', difficulty: 1, tags: ['body'] },
    { language: 'ar', german_word: 'قلب', english_translation: 'heart', transliteration: 'qalb', word_type: 'noun', level: 'A1', category: 'health', example_sentence: 'قلبي سليم', example_translation: 'My heart is healthy', difficulty: 1, tags: ['body'] },
    { language: 'ar', german_word: 'فم', english_translation: 'mouth', transliteration: 'fam', word_type: 'noun', level: 'A1', category: 'health', example_sentence: 'فمي صغير', example_translation: 'My mouth is small', difficulty: 1, tags: ['body'] },
    // Nature
    { language: 'ar', german_word: 'شمس', english_translation: 'sun', transliteration: 'shams', word_type: 'noun', level: 'A1', category: 'nature', example_sentence: 'الشمس مشرقة', example_translation: 'The sun is shining', difficulty: 1, tags: ['nature'] },
    { language: 'ar', german_word: 'قمر', english_translation: 'moon', transliteration: 'qamar', word_type: 'noun', level: 'A1', category: 'nature', example_sentence: 'القمر جميل', example_translation: 'The moon is beautiful', difficulty: 1, tags: ['nature'] },
    { language: 'ar', german_word: 'بحر', english_translation: 'sea', transliteration: 'baḥr', word_type: 'noun', level: 'A1', category: 'nature', example_sentence: 'البحر أزرق', example_translation: 'The sea is blue', difficulty: 1, tags: ['nature'] },
    { language: 'ar', german_word: 'جبل', english_translation: 'mountain', transliteration: 'jabal', word_type: 'noun', level: 'A1', category: 'nature', example_sentence: 'الجبل عالٍ', example_translation: 'The mountain is high', difficulty: 1, tags: ['nature'] },
    { language: 'ar', german_word: 'زهرة', english_translation: 'flower', transliteration: 'zahrah', word_type: 'noun', level: 'A1', category: 'nature', example_sentence: 'الزهرة حمراء', example_translation: 'The flower is red', difficulty: 1, tags: ['nature'] },
    // Education
    { language: 'ar', german_word: 'كتاب', english_translation: 'book', transliteration: 'kitāb', word_type: 'noun', level: 'A1', category: 'education', example_sentence: 'الكتاب مفيد', example_translation: 'The book is useful', difficulty: 1, tags: ['education', 'basic'] },
    { language: 'ar', german_word: 'قلم', english_translation: 'pen', transliteration: 'qalam', word_type: 'noun', level: 'A1', category: 'education', example_sentence: 'القلم أزرق', example_translation: 'The pen is blue', difficulty: 1, tags: ['education', 'basic'] },
    { language: 'ar', german_word: 'درس', english_translation: 'lesson', transliteration: 'dars', word_type: 'noun', level: 'A1', category: 'education', example_sentence: 'الدرس سهل', example_translation: 'The lesson is easy', difficulty: 1, tags: ['education'] },
    { language: 'ar', german_word: 'مدرسة', english_translation: 'school', transliteration: 'madrasah', word_type: 'noun', level: 'A1', category: 'education', example_sentence: 'المدرسة قريبة', example_translation: 'The school is near', difficulty: 1, tags: ['education', 'basic'] },
    { language: 'ar', german_word: 'جامعة', english_translation: 'university', transliteration: 'jāmiʿah', word_type: 'noun', level: 'A1', category: 'education', example_sentence: 'الجامعة كبيرة', example_translation: 'The university is big', difficulty: 1, tags: ['education'] },
    // Technology
    { language: 'ar', german_word: 'هاتف', english_translation: 'phone', transliteration: 'hātif', word_type: 'noun', level: 'A1', category: 'technology', example_sentence: 'الهاتف جديد', example_translation: 'The phone is new', difficulty: 1, tags: ['technology'] },
    { language: 'ar', german_word: 'حاسوب', english_translation: 'computer', transliteration: 'ḥāsūb', word_type: 'noun', level: 'A1', category: 'technology', example_sentence: 'الحاسوب سريع', example_translation: 'The computer is fast', difficulty: 1, tags: ['technology'] },
    // Numbers
    { language: 'ar', german_word: 'واحد', english_translation: 'one', transliteration: 'wāḥid', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'واحد اثنان ثلاثة', example_translation: 'One two three', difficulty: 1, tags: ['numbers'] },
    { language: 'ar', german_word: 'اثنان', english_translation: 'two', transliteration: 'ithnān', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'اثنان زائد اثنان', example_translation: 'Two plus two', difficulty: 1, tags: ['numbers'] },
    { language: 'ar', german_word: 'ثلاثة', english_translation: 'three', transliteration: 'thalāthah', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'ثلاثة كتب', example_translation: 'Three books', difficulty: 1, tags: ['numbers'] },
    { language: 'ar', german_word: 'ساعة', english_translation: 'clock/hour', transliteration: 'sāʿah', word_type: 'noun', level: 'A1', category: 'daily_life', example_sentence: 'الساعة الثالثة', example_translation: 'Three o\'clock', difficulty: 1, tags: ['daily'] },
    // Emotions
    { language: 'ar', german_word: 'سعيد', english_translation: 'happy', transliteration: 'saʿīd', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'أنا سعيد', example_translation: 'I am happy', difficulty: 1, tags: ['basic'] },
    { language: 'ar', german_word: 'حزين', english_translation: 'sad', transliteration: 'ḥazīn', word_type: 'adjective', level: 'A1', category: 'daily_life', example_sentence: 'هو حزين', example_translation: 'He is sad', difficulty: 1, tags: ['basic'] },
  ])

  console.log('\n✓ Database seeding complete!')
}

main().catch(console.error)
