-- DeutschMentor AI - Complete Database Schema
-- This migration sets up the entire database schema including tables, relationships, RLS policies, and indexes.

-- ============================================================
-- CORE TABLES
-- ============================================================

-- User profiles (extends Supabase auth.users)
create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null unique,
  email text,
  full_name text not null default '',
  avatar_url text,
  native_language text default 'English',
  current_level text default 'A1' check (current_level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  target_level text default 'B1' check (target_level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  learning_goal text default 'exam_preparation' check (learning_goal in ('exam_preparation', 'daily_conversation', 'business_german', 'academic', 'travel', 'relocation')),
  daily_study_minutes integer default 30,
  exam_goal text check (exam_goal in ('goethe', 'telc')),
  role text default 'student' check (role in ('student', 'teacher', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Learning goals
create table public.learning_goals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null unique,
  current_level text default 'A1' check (current_level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  target_level text default 'B1' check (target_level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  learning_goal text,
  daily_study_minutes integer default 30,
  exam_goal text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Courses
create table public.courses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  level text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  image_url text,
  teacher_id uuid references auth.users(id),
  is_published boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Lessons
create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references public.courses(id) on delete cascade not null,
  title text not null,
  description text,
  lesson_type text not null check (lesson_type in ('listening', 'reading', 'writing', 'speaking', 'vocabulary', 'grammar')),
  level text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  order_index integer not null default 0,
  duration_minutes integer default 15,
  is_published boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Lesson content (JSONB for flexible content storage)
create table public.lesson_content (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid references public.lessons(id) on delete cascade not null,
  content_type text not null,
  content jsonb not null default '{}',
  order_index integer not null default 0,
  created_at timestamptz default now()
);

-- Skills tracking (Hören, Lesen, Schreiben, Sprechen)
create table public.skills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  skill_type text not null check (skill_type in ('hoeren', 'lesen', 'schreiben', 'sprechen')),
  score integer not null default 0 check (score >= 0 and score <= 100),
  level text not null default 'A1',
  updated_at timestamptz default now(),
  unique(user_id, skill_type)
);

-- Progress tracking
create table public.progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  lesson_id uuid references public.lessons(id) on delete cascade,
  completed boolean default false,
  score integer check (score >= 0 and score <= 100),
  time_spent_minutes integer default 0,
  completed_at timestamptz,
  created_at timestamptz default now()
);

-- Daily study sessions
create table public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null default current_date,
  total_minutes integer not null default 0,
  lessons_completed integer default 0,
  created_at timestamptz default now()
);

-- Daily plans (generated by the learning engine)
create table public.daily_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null,
  activities jsonb not null default '[]',
  total_minutes integer not null default 30,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, date)
);

-- ============================================================
-- VOCABULARY SYSTEM
-- ============================================================

-- Master vocabulary bank
create table public.vocabulary (
  id uuid primary key default gen_random_uuid(),
  german_word text not null,
  english_translation text not null,
  article text,
  plural text,
  example_sentence text,
  level text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  category text,
  created_at timestamptz default now()
);

-- User vocabulary (spaced repetition)
create table public.user_vocabulary (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  vocabulary_id uuid references public.vocabulary(id) on delete cascade not null,
  mastered boolean default false,
  difficulty integer default 0 check (difficulty >= 0 and difficulty <= 5),
  next_review timestamptz default now(),
  review_count integer default 0,
  is_favorite boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, vocabulary_id)
);

-- Review history
create table public.review_history (
  id uuid primary key default gen_random_uuid(),
  user_vocabulary_id uuid references public.user_vocabulary(id) on delete cascade not null,
  review_date timestamptz default now(),
  performance integer not null check (performance >= 0 and performance <= 5),
  created_at timestamptz default now()
);

-- ============================================================
-- USER SUBMISSIONS
-- ============================================================

-- Mistakes tracking
create table public.mistakes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  lesson_id uuid references public.lessons(id) on delete set null,
  mistake_type text not null,
  user_answer text not null,
  correct_answer text not null,
  context text,
  created_at timestamptz default now()
);

-- Writing submissions
create table public.writing_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  title text default 'Untitled',
  original_text text not null,
  corrected_text text,
  feedback jsonb,
  score integer check (score >= 0 and score <= 100),
  level_estimate text,
  created_at timestamptz default now()
);

-- Speaking sessions
create table public.speaking_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  topic text not null,
  duration_seconds integer default 0,
  feedback jsonb,
  score integer check (score >= 0 and score <= 100),
  created_at timestamptz default now()
);

-- Exam attempts
create table public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  exam_type text not null check (exam_type in ('goethe', 'telc')),
  level text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1')),
  module text not null check (module in ('hoeren', 'lesen', 'schreiben', 'sprechen')),
  score integer not null check (score >= 0 and score <= 100),
  max_score integer not null default 100,
  passed boolean default false,
  attempt_date timestamptz default now(),
  created_at timestamptz default now()
);

-- AI feedback storage
create table public.ai_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  feedback_type text not null,
  content jsonb not null default '{}',
  reference_id uuid,
  reference_type text,
  created_at timestamptz default now()
);

-- ============================================================
-- ACHIEVEMENTS
-- ============================================================

create table public.achievements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  icon text,
  requirement jsonb default '{}',
  created_at timestamptz default now()
);

create table public.user_achievements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  achievement_id uuid references public.achievements(id) on delete cascade not null,
  achieved_at timestamptz default now(),
  unique(user_id, achievement_id)
);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  message text,
  type text default 'info',
  read boolean default false,
  created_at timestamptz default now()
);

-- ============================================================
-- INDEXES
-- ============================================================

create index idx_profiles_user_id on public.profiles(user_id);
create index idx_profiles_role on public.profiles(role);
create index idx_lessons_course_id on public.lessons(course_id);
create index idx_lessons_level on public.lessons(level);
create index idx_progress_user_id on public.progress(user_id);
create index idx_progress_lesson_id on public.progress(lesson_id);
create index idx_skills_user_id on public.skills(user_id);
create index idx_vocabulary_level on public.vocabulary(level);
create index idx_user_vocabulary_user_id on public.user_vocabulary(user_id);
create index idx_user_vocabulary_next_review on public.user_vocabulary(next_review);
create index idx_mistakes_user_id on public.mistakes(user_id);
create index idx_writing_submissions_user_id on public.writing_submissions(user_id);
create index idx_speaking_sessions_user_id on public.speaking_sessions(user_id);
create index idx_exam_attempts_user_id on public.exam_attempts(user_id);
create index idx_study_sessions_user_date on public.study_sessions(user_id, date);
create index idx_daily_plans_user_date on public.daily_plans(user_id, date);
create index idx_notifications_user_read on public.notifications(user_id, read);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.learning_goals enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_content enable row level security;
alter table public.skills enable row level security;
alter table public.progress enable row level security;
alter table public.study_sessions enable row level security;
alter table public.daily_plans enable row level security;
alter table public.vocabulary enable row level security;
alter table public.user_vocabulary enable row level security;
alter table public.review_history enable row level security;
alter table public.mistakes enable row level security;
alter table public.writing_submissions enable row level security;
alter table public.speaking_sessions enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.ai_feedback enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;
alter table public.notifications enable row level security;

-- Profiles: users can read their own, admins can read all
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = user_id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = user_id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = user_id);

create policy "Admins can manage all profiles"
  on public.profiles for all
  using (exists (
    select 1 from public.profiles where user_id = auth.uid() and role = 'admin'
  ));

-- Learning goals: user-specific
create policy "Users can manage own learning goals"
  on public.learning_goals for all
  using (auth.uid() = user_id);

-- Courses: published courses visible to all, teachers can manage their own
create policy "Anyone can view published courses"
  on public.courses for select
  using (is_published = true);

create policy "Teachers can manage own courses"
  on public.courses for all
  using (auth.uid() = teacher_id);

create policy "Admins can manage all courses"
  on public.courses for all
  using (exists (
    select 1 from public.profiles where user_id = auth.uid() and role = 'admin'
  ));

-- Lessons: visible with published courses
create policy "Anyone can view published lesson"
  on public.lessons for select
  using (is_published = true);

create policy "Teachers can manage own lessons"
  on public.lessons for all
  using (exists (
    select 1 from public.courses where id = course_id and teacher_id = auth.uid()
  ));

-- Skills: user-specific
create policy "Users can view own skills"
  on public.skills for select
  using (auth.uid() = user_id);

create policy "Users can update own skills"
  on public.skills for update
  using (auth.uid() = user_id);

create policy "System can insert skills"
  on public.skills for insert
  with check (auth.uid() = user_id);

-- Progress: user-specific
create policy "Users can view own progress"
  on public.progress for select
  using (auth.uid() = user_id);

create policy "Users can manage own progress"
  on public.progress for insert
  with check (auth.uid() = user_id);

create policy "Users can update own progress"
  on public.progress for update
  using (auth.uid() = user_id);

-- Study sessions: user-specific
create policy "Users can manage own study sessions"
  on public.study_sessions for all
  using (auth.uid() = user_id);

-- Daily plans: user-specific
create policy "Users can manage own daily plans"
  on public.daily_plans for all
  using (auth.uid() = user_id);

-- Vocabulary: all authenticated users can view
create policy "Auth users can view vocabulary"
  on public.vocabulary for select
  using (auth.role() = 'authenticated');

create policy "Admins can manage vocabulary"
  on public.vocabulary for all
  using (exists (
    select 1 from public.profiles where user_id = auth.uid() and role = 'admin'
  ));

-- User vocabulary: user-specific
create policy "Users can manage own vocabulary"
  on public.user_vocabulary for all
  using (auth.uid() = user_id);

-- Review history: user-specific
create policy "Users can view own review history"
  on public.review_history for select
  using (exists (
    select 1 from public.user_vocabulary where id = user_vocabulary_id and user_id = auth.uid()
  ));

create policy "Users can insert own review history"
  on public.review_history for insert
  with check (exists (
    select 1 from public.user_vocabulary where id = user_vocabulary_id and user_id = auth.uid()
  ));

-- Mistakes: user-specific
create policy "Users can manage own mistakes"
  on public.mistakes for all
  using (auth.uid() = user_id);

-- Writing submissions: user-specific
create policy "Users can manage own writing"
  on public.writing_submissions for all
  using (auth.uid() = user_id);

-- Speaking sessions: user-specific
create policy "Users can manage own speaking"
  on public.speaking_sessions for all
  using (auth.uid() = user_id);

-- Exam attempts: user-specific
create policy "Users can manage own exam attempts"
  on public.exam_attempts for all
  using (auth.uid() = user_id);

-- AI feedback: user-specific
create policy "Users can view own AI feedback"
  on public.ai_feedback for select
  using (auth.uid() = user_id);

-- Achievements: all viewable
create policy "Anyone can view achievements"
  on public.achievements for select
  using (true);

-- User achievements: user-specific
create policy "Users can view own achievements"
  on public.user_achievements for select
  using (auth.uid() = user_id);

-- Notifications: user-specific
create policy "Users can manage own notifications"
  on public.notifications for all
  using (auth.uid() = user_id);

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

-- Auto-create skills record for new users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (user_id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''));

  insert into public.skills (user_id, skill_type) values
    (new.id, 'hoeren'),
    (new.id, 'lesen'),
    (new.id, 'schreiben'),
    (new.id, 'sprechen');

  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Update updated_at timestamp
create or replace function public.update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
  before update on public.profiles
  for each row execute function public.update_updated_at();

create trigger update_courses_updated_at
  before update on public.courses
  for each row execute function public.update_updated_at();

create trigger update_lessons_updated_at
  before update on public.lessons
  for each row execute function public.update_updated_at();

create trigger update_user_vocabulary_updated_at
  before update on public.user_vocabulary
  for each row execute function public.update_updated_at();

-- Calculate streak
create or replace function public.get_current_streak(p_user_id uuid)
returns integer as $$
declare
  streak integer := 0;
  current_date_var date := current_date;
begin
  while exists (
    select 1 from public.study_sessions
    where user_id = p_user_id and date = current_date_var
  ) loop
    streak := streak + 1;
    current_date_var := current_date_var - 1;
  end loop;
  return streak;
end;
$$ language plpgsql security definer;

-- ============================================================
-- SEED DATA
-- ============================================================

-- Sample achievements
insert into public.achievements (title, description, icon, requirement) values
  ('Erste Schritte', 'Complete your first lesson', 'star', '{"lessons_completed": 1}'),
  ('Sprachenlerner', 'Study for 7 days in a row', 'flame', '{"streak": 7}'),
  ('Wortmeister', 'Learn 100 vocabulary words', 'book', '{"vocabulary_learned": 100}'),
  ('Hörverstehen', 'Score 90% on a listening exercise', 'headphones', '{"listening_score": 90}'),
  ('Schriftsteller', 'Submit 10 writing exercises', 'pen', '{"writing_submissions": 10}'),
  ('Konversationsprofi', 'Complete 5 speaking sessions', 'mic', '{"speaking_sessions": 5}'),
  ('Goethe Bereit', 'Complete a full mock exam', 'graduation_cap', '{"mock_exam_completed": 1}'),
  ('A1 Abgeschlossen', 'Complete all A1 lessons', 'check', '{"a1_lessons_completed": true}'),
  ('A2 Abgeschlossen', 'Complete all A2 lessons', 'check', '{"a2_lessons_completed": true}'),
  ('B1 Abgeschlossen', 'Complete all B1 lessons', 'check', '{"b1_lessons_completed": true}');
