-- DeutschMentor AI - C1 Vocabulary Seed Data (100 words)
-- Advanced exam-relevant vocabulary for Goethe/TELC C1 level
-- Themes: Academic & Scientific, Philosophical & Abstract, Formal & Literary,
-- Professional & Specialized, Complex Social Issues, Advanced Legal & Political, Nuanced Expressions

-- ============================================================
-- THEME 1: Academic & Scientific (20 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Korrelation', 'correlation', 'die', 'die Korrelationen', 'Die Studie zeigt eine signifikante Korrelation zwischen Bildung und Einkommen. — The study shows a significant correlation between education and income.', 'C1', 'academic', 'Academic & Scientific', 'corrélation', 'ارتباط', '/kɔʁelaˈt͡si̯oːn/', ARRAY['Wechselbeziehung', 'Zusammenhang', 'Abhängigkeit'], ARRAY['Unabhängigkeit', 'Zufälligkeit'], ARRAY['korrelieren', 'korrelativ', 'Korrelationskoeffizient'], NULL, 'rare', 4, 'noun', ARRAY['C1', 'academic', 'science']),
  (gen_random_uuid(), 'Differenzierung', 'differentiation', 'die', 'die Differenzierungen', 'Eine präzise Differenzierung der Begriffe ist in der Wissenschaft unerlässlich. — A precise differentiation of terms is essential in science.', 'C1', 'academic', 'Academic & Scientific', 'différenciation', 'تفاضل/تمييز', '/dɪfəʁɛnˈt͡siːʁʊŋ/', ARRAY['Unterscheidung', 'Abgrenzung', 'Spezifizierung'], ARRAY['Vermischung', 'Verallgemeinerung'], ARRAY['differenzieren', 'differenziert', 'Differenzial'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Empirie', 'empiricism', 'die', NULL, 'Die Empirie liefert die Grundlage für evidenzbasierte Forschung. — Empiricism provides the basis for evidence-based research.', 'C1', 'academic', 'Academic & Scientific', 'empirisme', 'تجريبية', '/ɛmpiˈʁiː/', ARRAY['Erfahrungswissenschaft', 'Empirik', 'Erfahrungsforschung'], ARRAY['Theorie', 'Spekulation'], ARRAY['empirisch', 'Empiriker', 'empiristisch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Paradigma', 'paradigm', 'das', 'die Paradigmen', 'Der Wechsel des wissenschaftlichen Paradigmas erfolgte nach der bahnbrechenden Entdeckung. — The shift of the scientific paradigm occurred after the groundbreaking discovery.', 'C1', 'academic', 'Academic & Scientific', 'paradigme', 'نموذج', '/paʁaˈdɪɡma/', ARRAY['Leitbild', 'Denkmodell', 'Weltanschauung'], NULL, ARRAY['paradigmatisch', 'Paradigmenwechsel', 'Paradigmenforschung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Qualifikation', 'qualification', 'die', 'die Qualifikationen', 'Für diese Position sind besondere fachliche Qualifikationen erforderlich. — This position requires special professional qualifications.', 'C1', 'academic', 'Academic & Scientific', 'qualification', 'مؤهل', '/kvalifikaˈt͡si̯oːn/', ARRAY['Kompetenz', 'Befähigung', 'Eignung'], ARRAY['Inkompetenz', 'Unfähigkeit'], ARRAY['qualifizieren', 'qualifiziert', 'Qualifikationsnachweis'], NULL, 'common', 4, 'noun', ARRAY['C1', 'academic', 'business']),
  (gen_random_uuid(), 'Zertifizierung', 'certification', 'die', 'die Zertifizierungen', 'Die Zertifizierung nach ISO-Normen ist für viele Unternehmen verpflichtend. — Certification according to ISO standards is mandatory for many companies.', 'C1', 'academic', 'Academic & Scientific', 'certification', 'شهادة اعتماد', '/t͡sɛʁtifiˈt͡siːʁʊŋ/', ARRAY['Akkreditierung', 'Beglaubigung', 'Bestätigung'], NULL, ARRAY['zertifizieren', 'Zertifikat', 'zertifiziert'], NULL, 'rare', 4, 'noun', ARRAY['C1', 'academic', 'business']),
  (gen_random_uuid(), 'Evaluation', 'evaluation', 'die', 'die Evaluationen', 'Die Evaluation des Projekts ergab überwiegend positive Ergebnisse. — The evaluation of the project yielded predominantly positive results.', 'C1', 'academic', 'Academic & Scientific', 'évaluation', 'تقييم', '/ʔevaluaˈt͡si̯oːn/', ARRAY['Bewertung', 'Beurteilung', 'Auswertung'], NULL, ARRAY['evalutieren', 'evaluativ', 'Evaluationsbericht'], NULL, 'common', 4, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Replikation', 'replication', 'die', 'die Replikationen', 'Die Replikation der Studie in einem anderen Land bestätigte die Ergebnisse. — The replication of the study in another country confirmed the results.', 'C1', 'academic', 'Academic & Scientific', 'reproduction', 'تكرار/استنساخ', '/ʁeplikaˈt͡si̯oːn/', ARRAY['Wiederholung', 'Nachbildung', 'Reproduktion'], NULL, ARRAY['replizieren', 'replizierbar', 'Replikationsstudie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Spektrum', 'spectrum', 'das', 'die Spektren', 'Das Spektrum der Forschungsmöglichkeiten in diesem Bereich ist breit gefächert. — The spectrum of research opportunities in this field is broad.', 'C1', 'academic', 'Academic & Scientific', 'spectre', 'طيف', '/ˈʃpɛktʁʊm/', ARRAY['Bandbreite', 'Palette', 'Breite'], ARRAY['Begrenzung', 'Einschränkung'], ARRAY['spektral', 'spektroskopisch', 'Spektralanalyse'], NULL, 'common', 4, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Validität', 'validity', 'die', NULL, 'Die Validität der Testergebnisse wurde durch mehrere Methoden überprüft. — The validity of the test results was verified using several methods.', 'C1', 'academic', 'Academic & Scientific', 'validité', 'صلاحية/صدق', '/validiˈtɛːt/', ARRAY['Gültigkeit', 'Aussagekraft', 'Stichhaltigkeit'], ARRAY['Ungültigkeit', 'Anfechtbarkeit'], ARRAY['valide', 'validieren', 'Validitätsprüfung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Reliabilität', 'reliability', 'die', NULL, 'Die Reliabilität des Messinstruments muss vor der Hauptstudie getestet werden. — The reliability of the measuring instrument must be tested before the main study.', 'C1', 'academic', 'Academic & Scientific', 'fiabilité', 'موثوقية', '/ʁeliabiliˈtɛːt/', ARRAY['Zuverlässigkeit', 'Verlässlichkeit', 'Genauigkeit'], ARRAY['Unzuverlässigkeit', 'Fehleranfälligkeit'], ARRAY['reliabel', 'reliabilitätsprüfung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Stringenz', 'stringency', 'die', NULL, 'Die Stringenz seiner Argumentation überzeugte die Gutachter. — The stringency of his argumentation convinced the reviewers.', 'C1', 'academic', 'Academic & Scientific', 'rigueur', 'صرامة/دقة', '/ʃtʁɪnˈɡɛnt͡s/', ARRAY['Strenge', 'Konsequenz', 'Folgerichtigkeit'], ARRAY['Inkonsequenz', 'Willkür'], ARRAY['stringent', 'Stringenzprüfung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Extrapolation', 'extrapolation', 'die', 'die Extrapolationen', 'Auf Basis der aktuellen Daten ist eine Extrapolation der Bevölkerungsentwicklung möglich. — Based on the current data, an extrapolation of population development is possible.', 'C1', 'academic', 'Academic & Scientific', 'extrapolation', 'استقراء', '/ɛkstʁapolaˈt͡si̯oːn/', ARRAY['Hochrechnung', 'Projektion', 'Vorhersage'], NULL, ARRAY['extrapolieren', 'extrapolativ'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Abstraktion', 'abstraction', 'die', 'die Abstraktionen', 'Die Fähigkeit zur Abstraktion ist in der Mathematik von zentraler Bedeutung. — The ability to abstract is of central importance in mathematics.', 'C1', 'academic', 'Academic & Scientific', 'abstraction', 'تجريد', '/apstʁakˈt͡si̯oːn/', ARRAY['Verallgemeinerung', 'Idealisierung', 'Begriffsbildung'], ARRAY['Konkretion', 'Anschaulichkeit'], ARRAY['abstrakt', 'abstrahieren', 'Abstraktionsvermögen'], NULL, 'common', 4, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Determinante', 'determinant', 'die', 'die Determinanten', 'Sozioökonomische Determinanten beeinflussen die Bildungschancen erheblich. — Socioeconomic determinants significantly influence educational opportunities.', 'C1', 'academic', 'Academic & Scientific', 'déterminant', 'محدد', '/detɛʁmiˈnantə/', ARRAY['Einflussfaktor', 'Bestimmungsgröße', 'Variable'], NULL, ARRAY['determinieren', 'deterministisch', 'Determinismus'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Taxonomie', 'taxonomy', 'die', 'die Taxonomien', 'Die Taxonomie der Lebewesen wird ständig an neue Erkenntnisse angepasst. — The taxonomy of living beings is constantly being adapted to new findings.', 'C1', 'academic', 'Academic & Scientific', 'taxonomie', 'تصنيف', '/taksonoˈmiː/', ARRAY['Klassifikation', 'Systematik', 'Ordnungssystem'], NULL, ARRAY['taxonomisch', 'Taxonom', 'Taxonomieforschung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Hypothese', 'hypothesis', 'die', 'die Hypothesen', 'Die Nullhypothese konnte auf dem Fünf-Prozent-Niveau verworfen werden. — The null hypothesis could be rejected at the five percent level.', 'C1', 'academic', 'Academic & Scientific', 'hypothèse', 'فرضية', '/hypoˈteːzə/', ARRAY['Annahme', 'These', 'Postulat'], ARRAY['Gewissheit', 'Beweis'], ARRAY['hypothetisch', 'Hypothesentest', 'Falsifikation'], NULL, 'common', 4, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Triangulation', 'triangulation', 'die', 'die Triangulationen', 'Die Triangulation verschiedener Forschungsmethoden erhöht die Aussagekraft der Studie. — Triangulation of different research methods increases the validity of the study.', 'C1', 'academic', 'Academic & Scientific', 'triangulation', 'تثليث', '/tʁiʔaŋɡulaˈt͡si̯oːn/', ARRAY['Methodenmix', 'Mehrfachvermessung'], NULL, ARRAY['triangulieren', 'triangulierend'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Metaanalyse', 'meta-analysis', 'die', 'die Metaanalysen', 'Eine Metaanalyse fasst die Ergebnisse mehrerer unabhängiger Studien zusammen. — A meta-analysis summarizes the results of several independent studies.', 'C1', 'academic', 'Academic & Scientific', 'méta-analyse', 'تحليل تلوي', '/ˈmeːtaʔanaˌlyːzə/', ARRAY['Studienzusammenfassung', 'Überblicksstudie', 'Sekundäranalyse'], NULL, ARRAY['Meta', 'Analyse', 'metaanalytisch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']),
  (gen_random_uuid(), 'Operationalisierung', 'operationalization', 'die', 'die Operationalisierungen', 'Die Operationalisierung abstrakter Konzepte ist eine zentrale Herausforderung der Sozialforschung. — The operationalization of abstract concepts is a central challenge of social research.', 'C1', 'academic', 'Academic & Scientific', 'opérationnalisation', 'تسويغ/تفعيل', '/ʔoːpəʁat͡si̯onaliˈziːʁʊŋ/', ARRAY['Messbarmachung', 'Konkretisierung', 'Definition'], NULL, ARRAY['operationalisieren', 'operational', 'Operationalisierungsschritt'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'academic']);

-- ============================================================
-- THEME 2: Philosophical & Abstract (15 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Existenz', 'existence', 'die', 'die Existenzen', 'Die Philosophie beschäftigt sich seit jeher mit der Frage nach der menschlichen Existenz. — Philosophy has always dealt with the question of human existence.', 'C1', 'philosophy', 'Philosophical & Abstract', 'existence', 'وجود', '/ɛksɪsˈtɛnt͡s/', ARRAY['Dasein', 'Sein', 'Lebensdasein'], ARRAY['Nichtexistenz', 'Nichts', 'Vernichtung'], ARRAY['existieren', 'existentiell', 'Existenzialismus'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Wahrnehmung', 'perception', 'die', 'die Wahrnehmungen', 'Die Wahrnehmung der Realität ist subjektiv und kulturell geprägt. — The perception of reality is subjective and culturally shaped.', 'C1', 'philosophy', 'Philosophical & Abstract', 'perception', 'إدراك', '/ˈvaːɐ̯neːmʊŋ/', ARRAY['Perzeption', 'Empfindung', 'Auffassung'], ARRAY['Ignoranz', 'Verkennung'], ARRAY['wahrnehmen', 'wahrnehmbar', 'Wahrnehmungspsychologie'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy', 'psychology']),
  (gen_random_uuid(), 'Kognition', 'cognition', 'die', 'die Kognitionen', 'Kognition umfasst Prozesse wie Denken, Erinnern und Problemlösen. — Cognition includes processes such as thinking, remembering, and problem-solving.', 'C1', 'philosophy', 'Philosophical & Abstract', 'cognition', 'إدراك معرفي', '/kɔɡniˈt͡si̯oːn/', ARRAY['Erkenntnisvermögen', 'Denkprozess', 'Wahrnehmungsfähigkeit'], NULL, ARRAY['kognitiv', 'kognitionswissenschaftlich', 'Kognitionspsychologie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy', 'psychology']),
  (gen_random_uuid(), 'Ambivalenz', 'ambivalence', 'die', 'die Ambivalenzen', 'Die Ambivalenz seiner Gefühle machte eine Entscheidung nahezu unmöglich. — The ambivalence of his feelings made a decision almost impossible.', 'C1', 'philosophy', 'Philosophical & Abstract', 'ambivalence', 'ازدواجية', '/ambivaˈlɛnt͡s/', ARRAY['Zwiespältigkeit', 'Widersprüchlichkeit', 'Gespaltenheit'], ARRAY['Eindeutigkeit', 'Klarheit', 'Entschlossenheit'], ARRAY['ambivalent', 'ambivalent'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy', 'psychology']),
  (gen_random_uuid(), 'Dialektik', 'dialectics', 'die', NULL, 'Die Dialektik von These und Antithese führt zur Synthese. — The dialectic of thesis and antithesis leads to synthesis.', 'C1', 'philosophy', 'Philosophical & Abstract', 'dialectique', 'جدل', '/diaˈlɛktɪk/', ARRAY['Dialogik', 'Wechselwirkung', 'Gegensatzdenken'], NULL, ARRAY['dialektisch', 'Dialektiker', 'dialektisch-materialistisch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Phänomen', 'phenomenon', 'das', 'die Phänomene', 'Das Phänomen der Lichtbrechung lässt sich physikalisch erklären. — The phenomenon of light refraction can be explained physically.', 'C1', 'philosophy', 'Philosophical & Abstract', 'phénomène', 'ظاهرة', '/fɛnoˈmeːn/', ARRAY['Erscheinung', 'Ereignis', 'Fakt'], NULL, ARRAY['phänomenal', 'Phänomenologie', 'phänomenologisch'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Kausalität', 'causality', 'die', NULL, 'Der Philosoph hinterfragte das Prinzip der Kausalität. — The philosopher questioned the principle of causality.', 'C1', 'philosophy', 'Philosophical & Abstract', 'causalité', 'سببية', '/kaʊ̯zaliˈtɛːt/', ARRAY['Ursächlichkeit', 'Ursache-Wirkung', 'Kausalnexus'], ARRAY['Zufall', 'Akausalität'], ARRAY['kausal', 'Kausalkette', 'Kausalzusammenhang'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Transzendenz', 'transcendence', 'die', NULL, 'Fragen nach der Transzendenz bewegen die Menschheit seit Jahrtausenden. — Questions about transcendence have moved humanity for millennia.', 'C1', 'philosophy', 'Philosophical & Abstract', 'transcendance', 'تعالي/سمو', '/tʁanst͡sɛnˈdɛnt͡s/', ARRAY['Übersinnlichkeit', 'Metaphysik', 'Jenseitigkeit'], ARRAY['Immanenz', 'Diesseitigkeit'], ARRAY['transzendent', 'transzendieren', 'Transzendentalphilosophie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Subjektivität', 'subjectivity', 'die', NULL, 'Die Subjektivität der Wahrnehmung erschwert objektive Urteile. — The subjectivity of perception makes objective judgments difficult.', 'C1', 'philosophy', 'Philosophical & Abstract', 'subjectivité', 'ذاتية', '/zʊpjɛktiviˈtɛːt/', ARRAY['Perspektivität', 'Individualität', 'Persönliche Sicht'], ARRAY['Objektivität', 'Neutralität', 'Sachlichkeit'], ARRAY['subjektiv', 'subjektivistisch', 'Subjekt'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Kontingenz', 'contingency', 'die', 'die Kontingenzen', 'Die Kontingenz historischer Ereignisse macht Prognosen schwierig. — The contingency of historical events makes predictions difficult.', 'C1', 'philosophy', 'Philosophical & Abstract', 'contingence', 'احتمالية/طارئ', '/kɔntɪnˈɡɛnt͡s/', ARRAY['Zufälligkeit', 'Möglichkeit', 'Ungewissheit'], ARRAY['Notwendigkeit', 'Determiniertheit'], ARRAY['kontingent', 'Kontingenztheorie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Antinomie', 'antinomy', 'die', 'die Antinomien', 'Die Antinomie zwischen Freiheit und Sicherheit ist ein Grundproblem der Rechtsphilosophie. — The antinomy between freedom and security is a fundamental problem of legal philosophy.', 'C1', 'philosophy', 'Philosophical & Abstract', 'antinomie', 'تناقض/نقيض', '/antinoˈmiː/', ARRAY['Widerspruch', 'Paradoxon', 'Gegensatz'], ARRAY['Harmonie', 'Übereinstimmung'], ARRAY['antinomisch', 'Antinomismus'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Hermeneutik', 'hermeneutics', 'die', NULL, 'Die Hermeneutik befasst sich mit der Theorie des Verstehens und der Interpretation. — Hermeneutics deals with the theory of understanding and interpretation.', 'C1', 'philosophy', 'Philosophical & Abstract', 'herméneutique', 'تأويلية', '/hɛʁməˈnɔʏ̯tɪk/', ARRAY['Interpretationslehre', 'Textauslegung', 'Verstehenskunst'], NULL, ARRAY['hermeneutisch', 'Hermeneutiker', 'philosophische Hermeneutik'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Ästhetik', 'aesthetics', 'die', NULL, 'Die Ästhetik der Moderne hat traditionelle Schönheitsideale in Frage gestellt. — The aesthetics of modernity have questioned traditional ideals of beauty.', 'C1', 'philosophy', 'Philosophical & Abstract', 'esthétique', 'علم الجمال', '/ʔɛsˈteːtɪk/', ARRAY['Schönheitslehre', 'Geschmackslehre', 'Kunstphilosophie'], NULL, ARRAY['ästhetisch', 'Ästhet', 'ästhetisieren'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy', 'art']),
  (gen_random_uuid(), 'Synthese', 'synthesis', 'die', 'die Synthesen', 'Die Synthese verschiedener Theorien führte zu einem neuen Erklärungsmodell. — The synthesis of different theories led to a new explanatory model.', 'C1', 'philosophy', 'Philosophical & Abstract', 'synthèse', 'توليف/تركيب', '/zʏnˈteːzə/', ARRAY['Vereinigung', 'Integration', 'Kombination'], ARRAY['Analyse', 'Trennung', 'Zerlegung'], ARRAY['synthetisch', 'synthetisieren', 'Syntheseleistung'], NULL, 'common', 4, 'noun', ARRAY['C1', 'philosophy']),
  (gen_random_uuid(), 'Postulat', 'postulate', 'das', 'die Postulate', 'Das Postulat der Menschenwürde ist Grundlage unseres Rechtssystems. — The postulate of human dignity is the foundation of our legal system.', 'C1', 'philosophy', 'Philosophical & Abstract', 'postulat', 'مسلمة', '/pɔstuˈlaːt/', ARRAY['Grundannahme', 'Prinzip', 'Axiom'], ARRAY['Beweis', 'Fakt'], ARRAY['postulieren', 'postulatorisch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'philosophy']);

-- ============================================================
-- THEME 3: Formal & Literary (15 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Poesie', 'poetry', 'die', NULL, 'Die Poesie der Romantik ist von tiefen Gefühlen und Naturverbundenheit geprägt. — Romantic poetry is characterized by deep feelings and connection to nature.', 'C1', 'literature', 'Formal & Literary', 'poésie', 'شعر', '/poeˈziː/', ARRAY['Lyrik', 'Dichtkunst', 'Verskunst'], ARRAY['Prosa', 'Alltagssprache'], ARRAY['poetisch', 'Poet', 'Poetik'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Rhetorik', 'rhetoric', 'die', NULL, 'Die Rhetorik des Redners überzeugte das gesamte Publikum. — The rhetoric of the speaker convinced the entire audience.', 'C1', 'literature', 'Formal & Literary', 'rhétorique', 'بلاغة', '/ʁeˈtoːʁɪk/', ARRAY['Redekunst', 'Beredsamkeit', 'Eloquenz'], ARRAY['Schweigsamkeit', 'Sprachlosigkeit'], ARRAY['rhetorisch', 'Rhetoriker', 'rhetorisieren'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Metapher', 'metaphor', 'die', 'die Metaphern', 'Die Metapher des Lebens als Reise findet sich in vielen Kulturen. — The metaphor of life as a journey is found in many cultures.', 'C1', 'literature', 'Formal & Literary', 'métaphore', 'استعارة', '/meˈtafɐ/', ARRAY['Bildsprache', 'Übertragung', 'Sprachbild'], ARRAY['Wörtlichkeit', 'Literalität'], ARRAY['metaphorisch', 'Metaphorik', 'Metapherngebrauch'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Narration', 'narration', 'die', 'die Narrationen', 'Die Narration des Romans wechselt zwischen verschiedenen Perspektiven. — The narration of the novel alternates between different perspectives.', 'C1', 'literature', 'Formal & Literary', 'narration', 'سرد', '/naʁaˈt͡si̯oːn/', ARRAY['Erzählung', 'Erzählweise', 'Erzählstruktur'], NULL, ARRAY['narrativ', 'erzählen', 'Narrativität'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Rezeption', 'reception', 'die', 'die Rezeptionen', 'Die Rezeption des Werkes in der Kritik war überwiegend positiv. — The reception of the work in the criticism was predominantly positive.', 'C1', 'literature', 'Formal & Literary', 'réception', 'تلقٍ', '/ʁet͡sɛpˈt͡si̯oːn/', ARRAY['Aufnahme', 'Wahrnehmung', 'Wirkung'], NULL, ARRAY['rezipieren', 'Rezipient', 'Rezeptionsgeschichte'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Konnotation', 'connotation', 'die', 'die Konnotationen', 'Das Wort hat eine negative Konnotation, die man im Kontext beachten sollte. — The word has a negative connotation that should be noted in context.', 'C1', 'literature', 'Formal & Literary', 'connotation', 'دلالة', '/kɔnotaˈt͡si̯oːn/', ARRAY['Nebenbedeutung', 'Assoziation', 'Beiklang'], ARRAY['Denotation', 'Hauptbedeutung'], ARRAY['konnotativ', 'konnotieren', 'Bedeutungskonnotation'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Stilistik', 'stylistics', 'die', NULL, 'Die Stilistik des Autors ist durch lange, komplexe Satzgefüge gekennzeichnet. — The author''s stylistics is characterized by long, complex sentence structures.', 'C1', 'literature', 'Formal & Literary', 'stylistique', 'أسلوبية', '/ʃtiˈlɪstɪk/', ARRAY['Stillehre', 'Sprachstil', 'Ausdrucksweise'], NULL, ARRAY['stilistisch', 'Stilist', 'stilistisch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Allegorie', 'allegory', 'die', 'die Allegorien', 'Die Allegorie der Höhle von Platon ist ein bekanntes philosophisches Gleichnis. — Plato''s allegory of the cave is a well-known philosophical parable.', 'C1', 'literature', 'Formal & Literary', 'allégorie', 'رمزية', '/alɛɡoˈʁiː/', ARRAY['Sinnbild', 'Gleichnis', 'Parabel'], NULL, ARRAY['allegorisch', 'allegorisieren', 'Allegorieforschung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Paradoxon', 'paradox', 'das', 'die Paradoxa', 'Das Paradoxon des Lügners beschäftigt Logiker seit der Antike. — The liar paradox has occupied logicians since antiquity.', 'C1', 'literature', 'Formal & Literary', 'paradoxe', 'مفارقة', '/paˈʁadɔksɔn/', ARRAY['Widerspruch', 'Antinomie', 'Paradoxie'], ARRAY['Logik', 'Konsistenz'], ARRAY['paradox', 'paradoxerweise'], NULL, 'common', 5, 'noun', ARRAY['C1', 'literature', 'philosophy']),
  (gen_random_uuid(), 'Philologie', 'philology', 'die', NULL, 'Die Philologie befasst sich mit der historischen Entwicklung von Sprachen und Texten. — Philology deals with the historical development of languages and texts.', 'C1', 'literature', 'Formal & Literary', 'philologie', 'فقه اللغة', '/filoloˈɡiː/', ARRAY['Sprachwissenschaft', 'Textkritik', 'Literaturwissenschaft'], NULL, ARRAY['philologisch', 'Philologe', 'Philologiestudium'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Vers', 'verse', 'der', 'die Verse', 'Der Vers besteht aus fünf Hebungen und folgt einem strengen Metrum. — The verse consists of five beats and follows a strict meter.', 'C1', 'literature', 'Formal & Literary', 'vers', 'بيت شعري', '/fɛʁs/', ARRAY['Verszeile', 'Strophe', 'Versmaß'], ARRAY['Prosa'], ARRAY['versweise', 'Versform', 'Versbau'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Pathos', 'pathos', 'das', NULL, 'Die Rede war voller Pathos und appellierte an die Emotionen der Zuhörer. — The speech was full of pathos and appealed to the emotions of the listeners.', 'C1', 'literature', 'Formal & Literary', 'pathos', 'شجن/إثارة عاطفية', '/ˈpaːtɔs/', ARRAY['Leidenschaft', 'Emotionalität', 'Ausdruckskraft'], ARRAY['Sachlichkeit', 'Nüchternheit', 'Distanziertheit'], ARRAY['pathetisch', 'Pathosformel'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']),
  (gen_random_uuid(), 'Klassik', 'classical period', 'die', NULL, 'Die Weimarer Klassik gilt als Höhepunkt der deutschen Literaturgeschichte. — The Weimar Classicism is considered the pinnacle of German literary history.', 'C1', 'literature', 'Formal & Literary', 'classicisme', 'كلاسيكية', '/ˈklasɪk/', ARRAY['Klassizismus', 'Antike', 'Humanitätsideal'], ARRAY['Romantik', 'Moderne'], ARRAY['klassisch', 'Klassiker', 'Klassizität'], NULL, 'common', 4, 'noun', ARRAY['C1', 'literature']),

  (gen_random_uuid(), 'Intertextualität', 'intertextuality', 'die', NULL, 'Die Intertextualität des Romans zeigt sich in zahlreichen Anspielungen auf andere Werke. — The intertextuality of the novel is evident in numerous allusions to other works.', 'C1', 'literature', 'Formal & Literary', 'intertextualité', 'تناص', '/ɪntɐtɛkstu̯aliˈtɛːt/', ARRAY['Textreferenz', 'Textbeziehung', 'Zitathaftigkeit'], NULL, ARRAY['intertextuell', 'intertextuell'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'literature']);

-- ============================================================
-- THEME 4: Professional & Specialized (15 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Spezifikation', 'specification', 'die', 'die Spezifikationen', 'Die technischen Spezifikationen des Produkts müssen genau eingehalten werden. — The technical specifications of the product must be strictly adhered to.', 'C1', 'business', 'Professional & Specialized', 'spécification', 'مواصفات', '/ʃpet͡sifikaˈt͡si̯oːn/', ARRAY['Anforderung', 'Detailbeschreibung', 'Definition'], NULL, ARRAY['spezifizieren', 'spezifisch', 'Spezifikationsblatt'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business', 'tech']),
  (gen_random_uuid(), 'Implementierung', 'implementation', 'die', 'die Implementierungen', 'Die Implementierung der neuen Software verlief reibungslos. — The implementation of the new software went smoothly.', 'C1', 'business', 'Professional & Specialized', 'implémentation', 'تنفيذ', '/ɪmplemɛnˈtiːʁʊŋ/', ARRAY['Umsetzung', 'Durchführung', 'Realisierung'], ARRAY['Planung', 'Entwurf', 'Konzeption'], ARRAY['implementieren', 'implementierbar'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business', 'tech']),
  (gen_random_uuid(), 'Akquisition', 'acquisition', 'die', 'die Akquisitionen', 'Die Akquisition des Start-ups war ein strategischer Schritt des Konzerns. — The acquisition of the startup was a strategic move by the corporation.', 'C1', 'business', 'Professional & Specialized', 'acquisition', 'استحواذ', '/akviziˈt͡si̯oːn/', ARRAY['Übernahme', 'Erwerb', 'Zukauf'], ARRAY['Verkauf', 'Veräußerung'], ARRAY['akquirieren', 'Akquisiteur', 'Akquisitionsstrategie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Optimierung', 'optimization', 'die', 'die Optimierungen', 'Die Optimierung der Produktionsabläufe führte zu erheblichen Kosteneinsparungen. — The optimization of production processes led to significant cost savings.', 'C1', 'business', 'Professional & Specialized', 'optimisation', 'تحسين أمثل', '/ɔptɪˈmiːʁʊŋ/', ARRAY['Verbesserung', 'Effizienzsteigerung', 'Perfektionierung'], ARRAY['Verschlechterung', 'Verschwendung'], ARRAY['optimieren', 'optimal', 'Optimierungsprozess'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Allokation', 'allocation', 'die', 'die Allokationen', 'Die effiziente Allokation von Ressourcen ist eine zentrale Aufgabe der Volkswirtschaftslehre. — The efficient allocation of resources is a central task of economics.', 'C1', 'business', 'Professional & Specialized', 'allocation', 'توزيع', '/alokaˈt͡si̯oːn/', ARRAY['Zuteilung', 'Verteilung', 'Zuordnung'], NULL, ARRAY['allozieren', 'Allokationsmechanismus'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business', 'economics']),
  (gen_random_uuid(), 'Diversifikation', 'diversification', 'die', 'die Diversifikationen', 'Zur Risikominimung empfiehlt sich eine breite Diversifikation des Portfolios. — To minimize risk, a broad diversification of the portfolio is recommended.', 'C1', 'business', 'Professional & Specialized', 'diversification', 'تنويع', '/divɛʁzifikaˈt͡si̯oːn/', ARRAY['Streuung', 'Variation', 'Diversifizierung'], ARRAY['Konzentration', 'Spezialisierung'], ARRAY['diversifizieren', 'divers', 'Diversifikationsstrategie'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business', 'finance']),
  (gen_random_uuid(), 'Konsolidierung', 'consolidation', 'die', 'die Konsolidierungen', 'Nach der Expansion folgte die Phase der Konsolidierung des Unternehmens. — After the expansion, the consolidation phase of the company followed.', 'C1', 'business', 'Professional & Specialized', 'consolidation', 'توطيد/دمج', '/kɔnzolidiːˈʁʊŋ/', ARRAY['Festigung', 'Stabilisierung', 'Zusammenfassung'], ARRAY['Expansion', 'Wachstum', 'Ausweitung'], ARRAY['konsolidieren', 'konsolidiert', 'Konsolidierungsphase'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Due Diligence', 'due diligence', 'die', NULL, 'Vor der Übernahme wurde eine umfassende Due Diligence durchgeführt. — Before the takeover, a comprehensive due diligence was carried out.', 'C1', 'business', 'Professional & Specialized', 'due diligence', 'العناية الواجبة', '/djuː dɪlɪdʒəns/', ARRAY['Sorgfaltsprüfung', 'Unternehmensprüfung', 'Prüfverfahren'], NULL, ARRAY['Due-Diligence-Prüfung'], NULL, 'rare', 5, 'expression', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Controlling', 'controlling', 'das', NULL, 'Das Controlling überwacht die Einhaltung der finanziellen Ziele des Unternehmens. — Controlling monitors compliance with the company''s financial goals.', 'C1', 'business', 'Professional & Specialized', 'contrôle de gestion', 'رقابة إدارية', '/kɔnˈtʁoːlɪŋ/', ARRAY['Finanzkontrolle', 'Unternehmenssteuerung', 'Managementkontrolle'], NULL, ARRAY['Controller', 'Controllingabteilung'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Synergie', 'synergy', 'die', 'die Synergien', 'Die Synergie zwischen den beiden Abteilungen führte zu innovativen Lösungen. — The synergy between the two departments led to innovative solutions.', 'C1', 'business', 'Professional & Specialized', 'synergie', 'تآزر', '/zynɛʁˈɡiː/', ARRAY['Wechselwirkung', 'Zusammenwirken', 'Kooperationseffekt'], ARRAY['Reibungsverlust', 'Dysfunktionalität'], ARRAY['synergistisch', 'Synergieeffekt'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Restrukturierung', 'restructuring', 'die', 'die Restrukturierungen', 'Die Restrukturierung des Unternehmens war aufgrund der finanziellen Schieflage notwendig. — The restructuring of the company was necessary due to its financial difficulties.', 'C1', 'business', 'Professional & Specialized', 'restructuration', 'إعادة هيكلة', '/ʁeʃtʁʊktuˈʁiːʁʊŋ/', ARRAY['Umstrukturierung', 'Sanierung', 'Neuorganisation'], NULL, ARRAY['restrukturieren', 'Restrukturierungsplan'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Benchmark', 'benchmark', 'der', 'die Benchmarks', 'Der Benchmark für die Branche liegt bei einer Rendite von acht Prozent. — The benchmark for the industry is a return of eight percent.', 'C1', 'business', 'Professional & Specialized', 'référence/comparaison', 'معيار مرجعي', '/ˈbɛntʃmaʁk/', ARRAY['Vergleichsmaßstab', 'Referenzwert', 'Richtwert'], NULL, ARRAY['Benchmarking', 'Benchmark-Analyse', 'benchmarken'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Prognose', 'forecast', 'die', 'die Prognosen', 'Die Prognosen für das Wirtschaftswachstum wurden nach unten korrigiert. — The forecasts for economic growth have been revised downwards.', 'C1', 'business', 'Professional & Specialized', 'prévision', 'توقع', '/pʁoˈɡnoːzə/', ARRAY['Vorhersage', 'Prognostizierung', 'Hochrechnung'], NULL, ARRAY['prognostizieren', 'prognostisch', 'Prognosemodell'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business']),
  (gen_random_uuid(), 'Rendite', 'yield', 'die', 'die Renditen', 'Die Rendite der Anleihe liegt derzeit bei dreieinhalb Prozent. — The yield on the bond is currently at three and a half percent.', 'C1', 'business', 'Professional & Specialized', 'rendement', 'عائد', '/ʁɛnˈdiːtə/', ARRAY['Ertrag', 'Gewinnmarge', 'Verzinsung'], ARRAY['Verlust', 'Minusrendite'], ARRAY['renditestark', 'Renditeerwartung', 'Renditeobjekt'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business', 'finance']),
  (gen_random_uuid(), 'Delegation', 'delegation', 'die', 'die Delegationen', 'Die Delegation von Verantwortung ist eine wichtige Führungskompetenz. — The delegation of responsibility is an important leadership skill.', 'C1', 'business', 'Professional & Specialized', 'délégation', 'تفويض', '/deleɡaˈt͡si̯oːn/', ARRAY['Übertragung', 'Bevollmächtigung', 'Abgabe'], NULL, ARRAY['delegieren', 'delegierbar', 'Delegationsprinzip'], NULL, 'common', 4, 'noun', ARRAY['C1', 'business']);

-- ============================================================
-- THEME 5: Complex Social Issues (15 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Diskrepanz', 'discrepancy', 'die', 'die Diskrepanzen', 'Die Diskrepanz zwischen Anspruch und Wirklichkeit ist in vielen Politikbereichen offensichtlich. — The discrepancy between aspiration and reality is obvious in many policy areas.', 'C1', 'society', 'Complex Social Issues', 'discrepance', 'تباين', '/dɪsˈkʁepants/', ARRAY['Widerspruch', 'Missverhältnis', 'Differenz'], ARRAY['Übereinstimmung', 'Harmonie', 'Kongruenz'], ARRAY['diskrepant'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Solidarität', 'solidarity', 'die', NULL, 'Internationale Solidarität ist in Zeiten globaler Krisen unverzichtbar. — International solidarity is indispensable in times of global crises.', 'C1', 'society', 'Complex Social Issues', 'solidarité', 'تضامن', '/zolidaʁiˈtɛːt/', ARRAY['Zusammenhalt', 'Verbundenheit', 'Gemeinssinn'], ARRAY['Egoismus', 'Individualismus', 'Gleichgültigkeit'], ARRAY['solidarisch', 'solidarisieren', 'Solidaritätsprinzip'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Radikalisierung', 'radicalization', 'die', 'die Radikalisierungen', 'Die Radikalisierung junger Menschen ist ein besorgniserregender gesellschaftlicher Trend. — The radicalization of young people is a worrying social trend.', 'C1', 'society', 'Complex Social Issues', 'radicalisation', 'تطرف', '/ʁadikaliˈziːʁʊŋ/', ARRAY['Extremismus', 'Fundamentalisierung', 'Politisierung'], ARRAY['Mäßigung', 'Gemäßigkeit', 'Demokratisierung'], ARRAY['radikalisieren', 'radikal', 'Radikalisierungsprävention'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Säkularisierung', 'secularization', 'die', NULL, 'Die Säkularisierung hat in westlichen Gesellschaften zu einem Bedeutungsverlust der Religion geführt. — Secularization has led to a loss of importance of religion in Western societies.', 'C1', 'society', 'Complex Social Issues', 'sécularisation', 'علمنة', '/zɛkulaʁiˈziːʁʊŋ/', ARRAY['Verweltlichung', 'Entkirchlichung', 'Laisierung'], ARRAY['Sakralisierung', 'Rekonfessionalisierung'], ARRAY['säkular', 'säkularisieren', 'Säkularisierungsprozess'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Segregation', 'segregation', 'die', 'die Segregationen', 'Die soziale Segregation in Großstädten verstärkt bestehende Ungleichheiten. — Social segregation in large cities reinforces existing inequalities.', 'C1', 'society', 'Complex Social Issues', 'ségrégation', 'فصل عنصري', '/zeɡʁeɡaˈt͡si̯oːn/', ARRAY['Trennung', 'Absonderung', 'Isolation'], ARRAY['Integration', 'Vermischung', 'Inklusion'], ARRAY['segregieren', 'segregativ', 'Segregationsprozess'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Partizipation', 'participation', 'die', NULL, 'Politische Partizipation ist ein Grundpfeiler jeder Demokratie. — Political participation is a fundamental pillar of any democracy.', 'C1', 'society', 'Complex Social Issues', 'participation', 'مشاركة', '/paʁtit͡siˈpaːt͡si̯oːn/', ARRAY['Teilhabe', 'Beteiligung', 'Mitwirkung'], ARRAY['Ausschluss', 'Exklusion', 'Enthaltung'], ARRAY['partizipieren', 'partizipativ', 'Partizipationsmöglichkeit'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Inklusion', 'inclusion', 'die', NULL, 'Inklusion bedeutet die gleichberechtigte Teilhabe aller Menschen an der Gesellschaft. — Inclusion means the equal participation of all people in society.', 'C1', 'society', 'Complex Social Issues', 'inclusion', 'إدماج/شمولية', '/ɪnkluˈzi̯oːn/', ARRAY['Integration', 'Einbeziehung', 'Teilhabe'], ARRAY['Exklusion', 'Ausgrenzung', 'Diskriminierung'], ARRAY['inklusiv', 'inkluieren', 'Inklusionspädagogik'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Exklusion', 'exclusion', 'die', 'die Exklusionen', 'Soziale Exklusion kann zu schwerwiegenden gesellschaftlichen Problemen führen. — Social exclusion can lead to serious societal problems.', 'C1', 'society', 'Complex Social Issues', 'exclusion', 'إقصاء', '/ɛkskluˈzi̯oːn/', ARRAY['Ausgrenzung', 'Ausschluss', 'Marginalisierung'], ARRAY['Inklusion', 'Integration', 'Teilhabe'], ARRAY['exklusiv', 'exkludieren', 'Exklusionsmechanismus'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Marginalisierung', 'marginalization', 'die', NULL, 'Die Marginalisierung bestimmter Bevölkerungsgruppen widerspricht dem Gleichheitsgrundsatz. — The marginalization of certain population groups contradicts the principle of equality.', 'C1', 'society', 'Complex Social Issues', 'marginalisation', 'تهميش', '/maʁɡinaliˈziːʁʊŋ/', ARRAY['Randständigkeit', 'Ausgrenzung', 'Benachteiligung'], ARRAY['Integration', 'Zentrierung', 'Förderung'], ARRAY['marginalisieren', 'marginal', 'Marginalisierungsprozess'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Populismus', 'populism', 'der', NULL, 'Der Populismus vereinfacht komplexe gesellschaftliche Probleme auf gefährliche Weise. — Populism simplifies complex social problems in a dangerous way.', 'C1', 'society', 'Complex Social Issues', 'populisme', 'شعبوية', '/popuˈlɪsmʊs/', ARRAY['Demagogie', 'Volksverführung', 'Politischer Extremismus'], ARRAY['Sachpolitik', 'Expertokratie'], ARRAY['populistisch', 'Populist', 'populistisch'], NULL, 'common', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Demographie', 'demographics', 'die', 'die Demographien', 'Der demographische Wandel stellt die Sozialsysteme vor enorme Herausforderungen. — Demographic change poses enormous challenges to social systems.', 'C1', 'society', 'Complex Social Issues', 'démographie', 'ديموغرافيا', '/demoɡʁaˈfiː/', ARRAY['Bevölkerungsentwicklung', 'Bevölkerungsstatistik'], NULL, ARRAY['demographisch', 'Demograph', 'demographischer Wandel'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Pluralismus', 'pluralism', 'der', NULL, 'Der gesellschaftliche Pluralismus ist eine Bereicherung für demokratische Systeme. — Social pluralism is an enrichment for democratic systems.', 'C1', 'society', 'Complex Social Issues', 'pluralisme', 'تعددية', '/pluʁaˈlɪsmʊs/', ARRAY['Vielfalt', 'Multikulturalismus', 'Diversität'], ARRAY['Uniformität', 'Gleichschaltung', 'Monolithismus'], ARRAY['pluralistisch', 'plural', 'Pluralismuskonzept'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Subkultur', 'subculture', 'die', 'die Subkulturen', 'Jugendliche Subkulturen entwickeln oft eigene Werte und Ausdrucksformen. — Youth subcultures often develop their own values and forms of expression.', 'C1', 'society', 'Complex Social Issues', 'sous-culture', 'ثقافة فرعية', '/ˈzʊpkʊlˌtuːɐ̯/', ARRAY['Jugendkultur', 'Szene', 'Milieu'], ARRAY['Mainstream', 'Hochkultur'], ARRAY['subkulturell', 'Kultur', 'subkulturelle Szene'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']),
  (gen_random_uuid(), 'Diskurs', 'discourse', 'der', 'die Diskurse', 'Der öffentliche Diskurs über Migration ist oft von Emotionen statt Fakten geprägt. — The public discourse on migration is often characterized by emotions rather than facts.', 'C1', 'society', 'Complex Social Issues', 'discours', 'خطاب', '/dɪsˈkʊʁs/', ARRAY['Debatte', 'Dialog', 'Meinungsaustausch'], NULL, ARRAY['diskursiv', 'Diskursanalyse', 'Diskursbeitrag'], NULL, 'common', 4, 'noun', ARRAY['C1', 'society']);

-- ============================================================
-- THEME 6: Advanced Legal & Political (10 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Rechtsprechung', 'jurisdiction/case law', 'die', 'die Rechtsprechungen', 'Die Rechtsprechung des Bundesverfassungsgerichts hat richtungsweisende Urteile gefällt. — The jurisdiction of the Federal Constitutional Court has issued landmark judgments.', 'C1', 'law', 'Advanced Legal & Political', 'jurisprudence', 'قضاء/سوابق قضائية', '/ˈʁɛçtʃpʁɛçʊŋ/', ARRAY['Judikative', 'Gerichtsbarkeit', 'Rechtspraxis'], NULL, ARRAY['Recht', 'sprechen', 'Rechtsprechungsorgan'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law']),
  (gen_random_uuid(), 'Verfassung', 'constitution', 'die', 'die Verfassungen', 'Die Verfassung garantiert die Grundrechte jedes Bürgers. — The constitution guarantees the fundamental rights of every citizen.', 'C1', 'law', 'Advanced Legal & Political', 'constitution', 'دستور', '/fɛɐˈfasʊŋ/', ARRAY['Grundgesetz', 'Staatsordnung', 'Verfassungsordnung'], ARRAY['Gesetzlosigkeit', 'Anarchie'], ARRAY['verfassungsgemäß', 'Verfassungsgerichtshof', 'Verfassungsänderung'], NULL, 'common', 4, 'noun', ARRAY['C1', 'law', 'politics']),
  (gen_random_uuid(), 'Legitimation', 'legitimation', 'die', 'die Legitimationen', 'Die demokratische Legitimation politischer Entscheidungen ist von zentraler Bedeutung. — The democratic legitimation of political decisions is of central importance.', 'C1', 'law', 'Advanced Legal & Political', 'légitimation', 'شرعية', '/leɡitimaˈt͡si̯oːn/', ARRAY['Rechtfertigung', 'Berechtigung', 'Legitimität'], ARRAY['Illegitimität', 'Unrechtmäßigkeit'], ARRAY['legitimieren', 'legitim', 'Legitimationskrise'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law', 'politics']),
  (gen_random_uuid(), 'Gewaltenteilung', 'separation of powers', 'die', NULL, 'Die Gewaltenteilung ist ein fundamentales Prinzip des Rechtsstaats. — The separation of powers is a fundamental principle of the constitutional state.', 'C1', 'law', 'Advanced Legal & Political', 'séparation des pouvoirs', 'فصل السلطات', '/ɡəˈvaltn̩ˌtaɪlʊŋ/', ARRAY['Checks and Balances', 'Machtteilung', 'Gewaltenverschränkung'], ARRAY['Machtkonzentration', 'Diktatur'], ARRAY['Gewalt', 'teilen', 'Gewaltenkontrolle'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law', 'politics']),
  (gen_random_uuid(), 'Präzedenzfall', 'precedent', 'der', 'die Präzedenzfälle', 'Das Urteil schuf einen Präzedenzfall für ähnliche Verfahren in der Zukunft. — The judgment created a precedent for similar proceedings in the future.', 'C1', 'law', 'Advanced Legal & Political', 'précédent', 'سابقة قضائية', '/pʁɛt͡seˈdɛnt͡sfal/', ARRAY['Musterfall', 'Referenzfall', 'Leiturteil'], NULL, ARRAY['präzedenzlos', 'Präzedenzwirkung'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law']),
  (gen_random_uuid(), 'Begnadigung', 'pardon', 'die', 'die Begnadigungen', 'Die Begnadigung des Häftlings durch den Präsidenten stieß auf gemischte Reaktionen. — The pardon of the prisoner by the president met with mixed reactions.', 'C1', 'law', 'Advanced Legal & Political', 'grâce', 'عفو', '/bəˈɡnaːdɪɡʊŋ/', ARRAY['Amnestie', 'Straferlass', 'Gnadenakt'], ARRAY['Verurteilung', 'Bestrafung'], ARRAY['begnadigen', 'begnadigt', 'Begnadigungsrecht'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law']),
  (gen_random_uuid(), 'Immunität', 'immunity', 'die', 'die Immunitäten', 'Der Abgeordnete genießt politische Immunität vor Strafverfolgung. — The member of parliament enjoys political immunity from prosecution.', 'C1', 'law', 'Advanced Legal & Political', 'immunité', 'حصانة', '/ɪmuniˈtɛːt/', ARRAY['Strafverfolgungsfreiheit', 'Indemnität', 'Schutz'], ARRAY['Strafbarkeit', 'Verfolgbarkeit'], ARRAY['immun', 'immunisieren', 'Immunitätsausschuss'], NULL, 'common', 4, 'noun', ARRAY['C1', 'law', 'politics']),
  (gen_random_uuid(), 'Ratifizierung', 'ratification', 'die', 'die Ratifizierungen', 'Die Ratifizierung des Vertrags erfordert eine Zweidrittelmehrheit im Parlament. — The ratification of the treaty requires a two-thirds majority in parliament.', 'C1', 'law', 'Advanced Legal & Political', 'ratification', 'تصديق', '/ʁatifɪˈt͡siːʁʊŋ/', ARRAY['Bestätigung', 'Inkraftsetzung', 'Genehmigung'], ARRAY['Ablehnung', 'Verwerfung'], ARRAY['ratifizieren', 'Ratifikationsprozess'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law', 'politics']),
  (gen_random_uuid(), 'Nichtigkeitserklärung', 'annulment', 'die', 'die Nichtigkeitserklärungen', 'Das Gericht sprach die Nichtigkeitserklärung des umstrittenen Gesetzes aus. — The court issued the annulment of the controversial law.', 'C1', 'law', 'Advanced Legal & Political', 'annulation', 'إبطال', '/ˈnɪçtɪçkaɪt͡sʔɛɐˌklɛːʁʊŋ/', ARRAY['Aufhebung', 'Annullierung', 'Außerkraftsetzung'], ARRAY['Bestätigung', 'Inkraftsetzung'], ARRAY['nichtig', 'erklären', 'Nichtigkeitsklage'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law']),
  (gen_random_uuid(), 'Suprematie', 'supremacy', 'die', NULL, 'Die Suprematie des Rechts über politische Macht ist ein Kernprinzip des Rechtsstaats. — The supremacy of law over political power is a core principle of the constitutional state.', 'C1', 'law', 'Advanced Legal & Political', 'suprématie', 'سيادة', '/zupʁemaˈtiː/', ARRAY['Vorherrschaft', 'Überlegenheit', 'Dominanz'], ARRAY['Unterordnung', 'Gleichrangigkeit'], ARRAY['suprem', 'Suprematieanspruch'], NULL, 'rare', 5, 'noun', ARRAY['C1', 'law']);

-- ============================================================
-- THEME 7: Nuanced Expressions (10 words)
-- ============================================================
INSERT INTO public.vocabulary (id, german_word, english_translation, article, plural, example_sentence, level, category, theme, french_translation, arabic_translation, ipa, synonyms, antonyms, word_family, verb_forms, frequency, difficulty_score, word_type, tags) VALUES
  (gen_random_uuid(), 'Fragwürdig', 'questionable', NULL, NULL, 'Seine Motivation für den plötzlichen Rücktritt erscheint mir äußerst fragwürdig. — His motivation for the sudden resignation seems extremely questionable to me.', 'C1', 'language', 'Nuanced Expressions', 'douteux/discutable', 'مشكوك فيه', '/ˈfʁaːkˌvʏʁdɪç/', ARRAY['zweifelhaft', 'bedenklich', 'anfechtbar'], ARRAY['zweifelsfrei', 'unbestritten', 'eindeutig'], ARRAY['Frage', 'würdig', 'Fragwürdigkeit'], NULL, 'common', 4, 'adjective', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Nichtsdestotrotz', 'nevertheless', NULL, NULL, 'Die Ergebnisse waren nicht signifikant; nichtsdestotrotz sollte man die Tendenz beachten. — The results were not significant; nevertheless, one should note the trend.', 'C1', 'language', 'Nuanced Expressions', 'néanmoins/malgré tout', 'ومع ذلك', '/nɪçtsdestoˈtʁɔt͡s/', ARRAY['trotzdem', 'dennoch', 'gleichwohl'], NULL, ARRAY['nichts', 'desto', 'trotz'], NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Inwiefern', 'to what extent', NULL, NULL, 'Inwiefern die neuen Maßnahmen tatsächlich wirken, wird sich erst zeigen. — To what extent the new measures actually work remains to be seen.', 'C1', 'language', 'Nuanced Expressions', 'dans quelle mesure', 'إلى أي مدى', '/ˈɪnviːfɛʁn/', ARRAY['inwieweit', 'in welchem Maße', 'wie sehr'], NULL, NULL, NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Augenscheinlich', 'apparent', NULL, NULL, 'Der augenscheinliche Widerspruch lässt sich bei genauerer Betrachtung auflösen. — The apparent contradiction can be resolved upon closer examination.', 'C1', 'language', 'Nuanced Expressions', 'apparent/visible', 'ظاهري', '/ˈaʊ̯ɡn̩ˌʃaɪ̯nlɪç/', ARRAY['offensichtlich', 'ersichtlich', 'anscheinend'], ARRAY['verborgen', 'unsichtbar', 'uneinsichtig'], ARRAY['Augenschein', 'Augenscheinlichkeit'], NULL, 'common', 4, 'adjective', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Unterdessen', 'meanwhile', NULL, NULL, 'Der Chef verhandelt im Ausland; unterdessen läuft das Geschäft zu Hause weiter. — The boss is negotiating abroad; meanwhile, business continues at home.', 'C1', 'language', 'Nuanced Expressions', 'entre-temps', 'في هذه الأثناء', '/ʊntɐˈdɛsn̩/', ARRAY['inzwischen', 'indessen', 'mittlerweile'], NULL, NULL, NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Gleichwohl', 'nonetheless', NULL, NULL, 'Die Theorie ist umstritten; gleichwohl bietet sie interessante Erklärungsansätze. — The theory is controversial; nonetheless, it offers interesting explanatory approaches.', 'C1', 'language', 'Nuanced Expressions', 'néanmoins', 'مع ذلك', '/ˈɡlaɪ̯çvoːl/', ARRAY['dennoch', 'trotzdem', 'nichtsdestotrotz'], NULL, ARRAY['gleich', 'wohl', 'nichtsdestoweniger'], NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Demgegenüber', 'in contrast', NULL, NULL, 'Die Gewinne sind gestiegen; demgegenüber stehen jedoch höhere Kosten. — Profits have risen; in contrast, however, there are higher costs.', 'C1', 'language', 'Nuanced Expressions', 'en revanche', 'في المقابل', '/deːmɡeːɡn̩ˈʔyːbɐ/', ARRAY['hingegen', 'dagegen', 'im Gegensatz dazu'], NULL, ARRAY['dem', 'gegenüber', 'gegenüberstellen'], NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Infolgedessen', 'consequently', NULL, NULL, 'Die Nachfrage stieg rapide an; infolgedessen musste die Produktion verdoppelt werden. — Demand rose rapidly; consequently, production had to be doubled.', 'C1', 'language', 'Nuanced Expressions', 'par conséquent', 'ونتيجة لذلك', '/ɪnˈfɔlɡədɛsn̩/', ARRAY['folglich', 'daher', 'deshalb'], NULL, NULL, NULL, 'common', 4, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Nichtsdestoweniger', 'notwithstanding', NULL, NULL, 'Die Einwände sind ernst zu nehmen; nichtsdestoweniger sollten wir den Plan weiterverfolgen. — The objections are to be taken seriously; notwithstanding, we should continue to pursue the plan.', 'C1', 'language', 'Nuanced Expressions', 'nonobstant', 'على الرغم من ذلك', '/nɪçtsdestoˈveːnɪɡɐ/', ARRAY['dennoch', 'trotzdem', 'nichtsdestotrotz'], NULL, NULL, NULL, 'rare', 5, 'adverb', ARRAY['C1', 'language']),
  (gen_random_uuid(), 'Schlussfolgernd', 'concluding', NULL, NULL, 'Schlussfolgernd kann man sagen, dass die Hypothese bestätigt wurde. — Concluding, one can say that the hypothesis was confirmed.', 'C1', 'language', 'Nuanced Expressions', 'conclusif', 'استنتاجي', '/ˈʃlʊsˌfɔlɡɐnt/', ARRAY['fazitartig', 'abschließend', 'resümierend'], NULL, ARRAY['Schluss', 'folgern', 'Schlussfolgerung'], NULL, 'rare', 4, 'adjective', ARRAY['C1', 'language']);
