-- B1 Listening Lesson: Auf der Bank – Ein Konto eröffnen
-- Natural dialogue optimized for neural TTS (Google/Azure/ElevenLabs)
-- Goethe/TELC exam style with native conversational German

-- Lesson
insert into public.audio_lessons (id, title, description, audio_url, transcript, level, duration_seconds, category, is_published, speaker_gender, speaker_age_group, accent, scenario, cefr_level, estimated_duration, grammar_involved, vocabulary_involved, difficulty_rating, speaker_count) values

('11111111-1111-1111-1111-111111111126',
'Auf der Bank – Ein Konto eröffnen',
'Opening a bank account in Germany — natural conversation with a bank advisor',
'',  -- audio_url: generated by TTS on demand
E'Angestellte: Guten Morgen, Herr Wagner. Schön, dass Sie bei uns vorbeischauen. Was kann ich für Sie tun?\nKunde: Guten Morgen, Frau Schäfer. Ja, also, ich möchte gern ein Girokonto bei Ihnen eröffnen.\nAngestellte: Sehr gerne. Haben Sie schon einen Termin?\nKunde: Nein, ehrlich gesagt nicht. Ich war gerade in der Stadt und dachte, ich komm einfach mal vorbei.\nAngestellte: Ach, das passt perfekt. Ich hab gerade einen Moment Zeit. Setzen Sie sich, bitte. Also, für ein Girokonto brauchen wir Ihren Personalausweis oder Reisepass. Und eine aktuelle Meldebescheinigung.\nKunde: Moment ... ja, hier ist mein Ausweis. Die Meldebescheinigung hab ich leider nicht dabei.\nAngestellte: Kein Problem, wirklich. Die können Sie ganz einfach später nachreichen. Per E-Mail oder im Online-Portal.\nKunde: Ja, das mach ich. Kann ich von zu Hause aus schicken.\nAngestellte: Perfekt. So, dann fangen wir mal an. Möchten Sie das Konto allein führen oder als Gemeinschaftskonto?\nKunde: Einzelkonto, bitte. Nur für mich.\nAngestellte: Alles klar. Und brauchen Sie dazu eine Kreditkarte?\nKunde: Ja, auf jeden Fall. Eine Visa-Karte wäre gut. Sagen Sie mal, was kostet das Konto eigentlich im Monat?\nAngestellte: Unser Standardkonto kostet sechs Euro monatlich. Die Visa-Karte ist da schon inklusive. Wenn Sie Student sind oder unter 28, gibt es ein kostenloses Modell.\nKunde: Ach, leider nicht. Ich bin 31 und arbeite seit zwei Jahren.\nAngestellte: Okay, dann das Standardkonto. Sechs Euro, Visa-Karte inklusive. Sie bekommen auch Zugriff auf unser Online-Banking und die App.\nKunde: Das klingt gut. Kann ich das Online-Banking eigentlich noch heute einrichten?\nAngestellte: Ja, das machen wir direkt mit. Sie bekommen Ihre Zugangsdaten dann in zwei bis drei Werktagen per Post.\nKunde: Und die Karte? Wie lange dauert die?\nAngestellte: Die Karte ist innerhalb von fünf Werktagen da. Den PIN kriegen Sie extra, in einem separaten Brief.\nKunde: Okay, super. Dann bin ich zufrieden. Noch eine Sache – kann ich von hier aus auch ein Tagesgeldkonto eröffnen?\nAngestellte: Na klar, das geht. Machen wir gleich mit. Ein Tagesgeldkonto ist kostenlos und Sie können flexibel Geld drauf überweisen oder wieder abheben.\nKunde: Das ist perfekt. Dann machen wir das auch.\nAngestellte: Prima! Dann brauche ich jetzt noch Ihre Unterschrift. Hier, bitte unterschreiben Sie hier und hier.\nKunde: ... So, das wär erledigt.\nAngestellte: Vielen Dank, Herr Wagner. Dann ist alles in trockenen Tüchern. In ungefähr einer Woche haben Sie alles beisammen.\nKunde: Vielen Dank, Frau Schäfer. Das war wirklich eine sehr freundliche Beratung.\nAngestellte: Gern geschehen! Wenn irgendwas ist, kommen Sie einfach vorbei oder rufen Sie an. Einen schönen Tag noch!\nKunde: Gleichfalls. Tschüss!',
'B1', 150, 'daily', true, 'female', 'adult', 'standard', 'daily', 'B1', '2-3 min',
'{"Modalverben (können, müssen, möchte)", "Konjunktiv II (wäre gut, hätte)", "Temporale Angaben (in zwei bis drei Werktagen, innerhalb von fünf Werktagen)", "Satzklammer (kann ich ... eröffnen)"}',
'{"Bank & Konto", "Geld & Finanzen", "Dokumente & Ausweise", "Formulare & Unterschriften"}',
3, 2);

-- Exercises
insert into public.listening_exercises (audio_lesson_id, question, options, correct_answer, order_index, question_type, distractors, difficulty_level, hint, explanation) values

('11111111-1111-1111-1111-111111111126',
'Warum möchte Herr Wagner zur Bank kommen?',
'["Er möchte ein Girokonto eröffnen", "Er hat einen Termin bei Frau Schäfer", "Er möchte Geld abheben", "Er sucht eine Kreditkarte"]',
'Er möchte ein Girokonto eröffnen',
1, 'multiple_choice',
'["Er hat einen Termin bei Frau Schäfer (er sagt deutlich: er hat keinen Termin)", "Er möchte Geld abheben (darum geht es nicht)", "Er sucht eine Kreditkarte (die Karte ist ein Extra, nicht der Hauptgrund)"]',
1,
'Hören Sie den ersten Satz des Kunden.',
'Der Kunde sagt: "Ja, also, ich möchte gern ein Girokonto bei Ihnen eröffnen."'),

('11111111-1111-1111-1111-111111111126',
'Der Kunde hat einen Termin vereinbart.',
'["Wahr", "Falsch"]',
'Falsch',
2, 'true_false',
'["Wahr (der Kunde sagt: Nein, ehrlich gesagt nicht)"]',
1,
'Achten Sie auf die Frage der Angestellten.',
'Die Angestellte fragt: "Haben Sie schon einen Termin?" Der Kunde antwortet: "Nein, ehrlich gesagt nicht."'),

('11111111-1111-1111-1111-111111111126',
'Was muss der Kunde noch nachreichen?',
'["Die Meldebescheinigung", "Den Personalausweis", "Die Kreditkarte", "Die Unterschrift"]',
'Die Meldebescheinigung',
3, 'multiple_choice',
'["Den Personalausweis (den hat er bereits dabei und gezeigt)", "Die Kreditkarte (die bekommt er von der Bank)", "Die Unterschrift (die gibt er direkt vor Ort)"]',
2,
'Die Angestellte sagt, dass etwas fehlt, aber kein Problem ist.',
'Die Angestellte sagt: "Die können Sie ganz einfach später nachreichen." – gemeint ist die Meldebescheinigung.'),

('11111111-1111-1111-1111-111111111126',
'Ordnen Sie die Schritte der Kontoeröffnung: A) Kunde unterschreibt die Formulare. B) Kunde zeigt seinen Personalausweis. C) Kunde bekommt Zugangsdaten per Post. D) Kunde und Angestellte besprechen das Kontomodell.',
'["B -> D -> A -> C", "D -> B -> A -> C", "B -> A -> D -> C", "B -> D -> C -> A"]',
'B -> D -> A -> C',
4, 'order_events',
'["D -> B -> A -> C (Besprechung vor Ausweis?)", "B -> A -> D -> C (Unterschrift vor Besprechung?)", "B -> D -> C -> A (Post vor Unterschrift?)"]',
2,
'Folgen Sie dem Gesprächsablauf von Anfang bis Ende.',
'Zuerst zeigt der Kunde seinen Ausweis (B), dann besprechen sie das Konto (D), dann unterschreibt er (A), und die Zugangsdaten kommen per Post (C).'),

('11111111-1111-1111-1111-111111111126',
'Wie viel kostet das Standardkonto pro Monat?',
'["Sechs Euro", "Fünf Euro", "Zehn Euro", "Kostenlos"]',
'Sechs Euro',
5, 'multiple_choice',
'["Fünf Euro (die Angestellte sagt sechs, nicht fünf)", "Zehn Euro (deutlich mehr als genannt)", "Kostenlos (nur für Studenten oder unter 28)"]',
1,
'Hören Sie die genaue Preisangabe.',
'Die Angestellte sagt: "Unser Standardkonto kostet sechs Euro monatlich."'),

('11111111-1111-1111-1111-111111111126',
'Welche zwei Produkte eröffnet Herr Wagner bei der Bank?',
'["Girokonto und Tagesgeldkonto", "Girokonto und Kreditkarte", "Tagesgeldkonto und Kreditkarte", "Festgeldkonto und Girokonto"]',
'Girokonto und Tagesgeldkonto',
6, 'multiple_choice',
'["Girokonto und Kreditkarte (die Kreditkarte gehört zum Konto, ist kein separates Produkt)", "Tagesgeldkonto und Kreditkarte (das Girokonto fehlt)", "Festgeldkonto und Girokonto (der Kunde fragt nach Tagesgeld, nicht Festgeld)"]',
3,
'Hören Sie die zweite Frage des Kunden am Ende des Gesprächs.',
'Der Kunde fragt: "Kann ich von hier aus auch ein Tagesgeldkonto eröffnen?" und die Angestellte sagt: "Machen wir gleich mit."'),

('11111111-1111-1111-1111-111111111126',
'Warum bekommt der Kunde das kostenlose Kontomodell nicht?',
'["Weil er 31 ist und arbeitet", "Weil er kein Student ist", "Weil er schon ein Konto hat", "Weil er in einer anderen Stadt wohnt"]',
'Weil er 31 ist und arbeitet',
7, 'short_answer',
'["Weil er kein Student ist (das stimmt, aber er ist auch über 28)", "Weil er schon ein Konto hat (nicht genannt)", "Weil er in einer anderen Stadt wohnt (nicht genannt)"]',
2,
'Die Angestellte sagt die zwei Bedingungen für das kostenlose Modell.',
'Die Angestellte sagt: "Wenn Sie Student sind oder unter 28." Der Kunde ist 31 und arbeitet – beides trifft nicht zu.');

-- Vocabulary
insert into public.listening_vocabulary (audio_lesson_id, german_word, english_translation, article, plural, part_of_speech, context_sentence, context_translation, usage_notes, cefr_level, frequency, order_index) values

('11111111-1111-1111-1111-111111111126',
'Girokonto', 'current/checking account', 'das', 'Girokonten', 'noun',
'Ich möchte ein Girokonto eröffnen.',
'I''d like to open a checking account.',
'Das Standardprodukt jeder deutschen Bank für den täglichen Zahlungsverkehr.',
'B1', 'very_common', 1),

('11111111-1111-1111-1111-111111111126',
'eröffnen', 'to open (an account)', null, null, 'verb',
'Ich möchte gern ein Konto bei Ihnen eröffnen.',
'I''d like to open an account with you.',
'Wird für Konten, Ausstellungen und Geschäfte verwendet. Perfekt mit "hat eröffnet".',
'B1', 'common', 2),

('11111111-1111-1111-1111-111111111126',
'Meldebescheinigung', 'registration certificate (proof of address)', 'die', 'Meldebescheinigungen', 'noun',
'Die können Sie später online nachreichen.',
'You can submit that later online.',
'Offizielles Dokument vom Einwohnermeldeamt. Wird in Deutschland bei vielen Behördengängen verlangt.',
'B1', 'common', 3),

('11111111-1111-1111-1111-111111111126',
'nachreichen', 'to submit later', null, null, 'verb',
'Die Meldebescheinigung können Sie später nachreichen.',
'You can submit the registration certificate later.',
'Trennbar: reicht nach, hat nachgereicht. Typisch für Behörden- und Banksprache.',
'B1', 'common', 4),

('11111111-1111-1111-1111-111111111126',
'Tagesgeldkonto', 'savings account (daily money)', 'das', 'Tagesgeldkonten', 'noun',
'Kann ich von hier aus auch ein Tagesgeldkonto eröffnen?',
'Can I also open a savings account from here?',
'Flexibles Sparkonto mit täglicher Verfügbarkeit. Andere Begriffe: Sparkonto (Sparkasse), Geldmarkt (seltener).',
'B1', 'common', 5),

('11111111-1111-1111-1111-111111111126',
'Zugangsdaten', 'login/access credentials', 'die', null, 'noun',
'Sie bekommen Ihre Zugangsdaten in zwei bis drei Werktagen per Post.',
'You will receive your login credentials by post in two to three working days.',
'Nur Plural (Pluraletantum). Umfasst meist Benutzername, Passwort und TAN-Liste.',
'B1', 'common', 6),

('11111111-1111-1111-1111-111111111126',
'Unterschrift', 'signature', 'die', 'Unterschriften', 'noun',
'Dann brauche ich jetzt noch Ihre Unterschrift.',
'Then I still need your signature.',
'Auf Formularen oft mit "Unterschrift" oder "Unterschreiben" markiert.',
'B1', 'very_common', 7),

('11111111-1111-1111-1111-111111111126',
'inklusive', 'included/inclusive', null, null, 'preposition',
'Die Visa-Karte ist da schon inklusive.',
'The Visa card is already included there.',
'Steht meist nach dem Nomen (Postposition). Alternativ: "einschließlich".',
'B1', 'common', 8),

('11111111-1111-1111-1111-111111111126',
'separat', 'separate', null, null, 'adjective',
'Den PIN kriegen Sie extra, in einem separaten Brief.',
'You get the PIN separately, in a separate letter.',
'Wird oft im Bank- und Behördendeutsch verwendet. "Separat" hat die Betonung auf der letzten Silbe.',
'B1', 'common', 9),

('11111111-1111-1111-1111-111111111126',
'in trockenen Tüchern sein', 'to be in the bag / settled', null, null, 'idiom',
'Dann ist alles in trockenen Tüchern.',
'Then everything is settled.',
'Umgangssprachliche Redewendung. Wörtlich: to be in dry towels. Bedeutet: alles ist erledigt und sicher.',
'B1', 'rare', 10);

-- Phrases
insert into public.listening_phrases (audio_lesson_id, german_phrase, english_translation, literal_translation, usage_context, formality_level, is_idiom, is_colloquial, order_index) values

('11111111-1111-1111-1111-111111111126',
'Ich war gerade in der Stadt und dachte, ich komm einfach mal vorbei.',
'I was just in town and thought I''d just stop by.',
null,
'Used to explain an unplanned visit. The "einfach mal" makes it sound casual and natural.',
'neutral', false, true, 1),

('11111111-1111-1111-1111-111111111126',
'Sagen Sie mal, was kostet das Konto eigentlich im Monat?',
'Tell me, what does the account actually cost per month?',
null,
'"Sagen Sie mal" is a polite conversation starter. "Eigentlich" adds a curious tone.',
'neutral', false, false, 2),

('11111111-1111-1111-1111-111111111126',
'Na klar, das geht. Machen wir gleich mit.',
'Of course, that works. We''ll do that right away.',
null,
'Friendly confirmation. "Na klar" is enthusiastic, "gleich mit" means "along with the current process".',
'neutral', false, true, 3),

('11111111-1111-1111-1111-111111111126',
'Das war wirklich eine sehr freundliche Beratung.',
'That was really a very friendly consultation.',
null,
'Polite closing phrase. "Beratung" is the service/advice given by a professional.',
'formal', false, false, 4),

('11111111-1111-1111-1111-111111111126',
'Dann ist alles in trockenen Tüchern.',
'Then everything is all settled / in the bag.',
'Then everything is in dry towels.',
'Idiomatic expression used when paperwork or a process is complete and secure.',
'neutral', true, true, 5);

-- Grammar points
insert into public.listening_grammar_points (audio_lesson_id, grammar_topic, explanation, example_from_audio, english_translation, rule_summary, cefr_level, order_index) values

('11111111-1111-1111-1111-111111111126',
'Satzklammer mit Modalverben',
'Im Deutschen steht das konjugierte Modalverb an Position 2, der Infinitiv am Satzende. Diese "Satzklammer" umschließt den Rest des Satzes.',
'Kann ich das Online-Banking noch heute einrichten?',
'Can I set up the online banking today?',
'Modalverb (Position 2) + ... + Infinitiv (Ende). Bei Fragen: Modalverb an Position 1.',
'B1', 1),

('11111111-1111-1111-1111-111111111126',
'Temporale Angaben mit "in" und "innerhalb von"',
'"in" + Dativ für zukünftige Zeiträume (in zwei Tagen). "innerhalb von" + Genitiv/Dativ für Zeiträume innerhalb einer Frist.',
'Die Karte ist innerhalb von fünf Werktagen da.',
'The card will arrive within five working days.',
'"in" + Dativ (in einer Woche). "innerhalb von" + Dativ (innerhalb von fünf Tagen).',
'B1', 2),

('11111111-1111-1111-1111-111111111126',
'Konjunktiv II für höfliche Fragen ("wäre", "hätte")',
'Der Konjunktiv II macht Fragen und Aussagen höflicher und distanzierter. "Ich möchte" ist bereits eine höfliche Form von "ich will".',
'Eine Visa-Karte wäre gut.',
'A Visa card would be good.',
'Konjunktiv II: wäre (sein), hätte (haben), könnte (können). Wird in Alltagsgesprächen ständig für Höflichkeit verwendet.',
'B1', 3),

('11111111-1111-1111-1111-111111111126',
'Umgangssprachliche Verkürzungen ("hab", "komm", "krieg")',
'Im gesprochenen Deutsch werden Endungen oft weggelassen. "Ich habe" → "Ich hab", "ich komme" → "ich komm", "bekommen" → "kriegen". Das ist Standard in Alltagsgesprächen, aber nicht in formeller Schriftsprache.',
'Ich hab gerade einen Moment Zeit. Sie kriegen den PIN extra.',
'I have a moment right now. You get the PIN separately.',
'In gesprochenem Deutsch: Endungs-e entfällt oft. "kriegen" ist umgangssprachlich für "bekommen". Nicht in formellen Briefen verwenden.',
'B1', 4);
