-- German Verbs Seed (generated)
-- Run after migration 00031_german_verbs.sql

-- Verb: lernen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('lernen', 'to learn', 'يتعلم', 'apprendre', 'A1', 'very_common', 'regular', 'intransitive', 'none', NULL, NULL, false, NULL, 'haben', 'gelernt', NULL, '/ˈlɛʁnən/', 'on first syllable', 'lernen', '{"pauken","studieren"}', '{"vergessen","verlernen"}', '{"school","education","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'praesens', 'lerne', 'lernst', 'lernt', 'lernen', 'lernt', 'lernen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'praeteritum', 'lernte', 'lerntest', 'lernte', 'lernten', 'lerntet', 'lernten');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'perfekt', 'habe gelernt', 'hast gelernt', 'hat gelernt', 'haben gelernt', 'habt gelernt', 'haben gelernt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'plusquamperfekt', 'hatte gelernt', 'hattest gelernt', 'hatte gelernt', 'hatten gelernt', 'hattet gelernt', 'hatten gelernt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'futur_i', 'werde lernen', 'wirst lernen', 'wird lernen', 'werden lernen', 'werdet lernen', 'werden lernen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'futur_ii', 'werde gelernt haben', 'wirst gelernt haben', 'wird gelernt haben', 'werden gelernt haben', 'werdet gelernt haben', 'werden gelernt haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'konjunktiv_ii', 'würde lernen', 'würdest lernen', 'würde lernen', 'würden lernen', 'würdet lernen', 'würden lernen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'lernen'), 'imperativ', NULL, 'lern!', NULL, NULL, 'lernt!', 'lernen Sie!');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'beginner', 'Ich lerne Deutsch.', 'I am learning German.', 'أنا أتعلم الألمانية.', 'J''apprends l''allemand.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'beginner', 'Lernst du jeden Tag?', 'Do you study every day?', 'هل تتعلم كل يوم؟', 'Apprends-tu tous les jours ?');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'beginner', 'Wir lernen zusammen.', 'We study together.', 'نتعلم معًا.', 'Nous apprenons ensemble.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'beginner', 'Er lernt für die Prüfung.', 'He is studying for the exam.', 'يدرس من أجل الامتحان.', 'Il étudie pour l''examen.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'beginner', 'Die Kinder lernen schnell.', 'The children learn quickly.', 'الأطفال يتعلمون بسرعة.', 'Les enfants apprennent vite.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'intermediate', 'Sie hat gestern drei Stunden gelernt.', 'She studied for three hours yesterday.', 'درست لمدة ثلاث ساعات أمس.', 'Elle a étudié trois heures hier.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'intermediate', 'Man lernt nie aus.', 'You learn something new every day.', 'لا يتوقف المرء عن التعلم أبدًا.', 'On n''arrête jamais d''apprendre.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'intermediate', 'Ich lerne Deutsch, seit ich in Berlin wohne.', 'I''ve been learning German since I moved to Berlin.', 'أتعلم الألمانية منذ أن انتقلت إلى برلين.', 'J''apprends l''allemand depuis que j''habite à Berlin.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'intermediate', 'Für diesen Beruf muss man viel lernen.', 'You have to study a lot for this profession.', 'لهذه المهنة يجب أن تدرس كثيرًا.', 'Pour ce métier, il faut beaucoup étudier.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'intermediate', 'Ohne Fleiß kein Preis - man muss hart lernen.', 'No pain no gain - you have to work hard.', 'بدون اجتهاد لا نجاح - يجب أن تدرس بجد.', 'Sans effort, pas de récompense - il faut étudier dur.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'advanced', 'Die Studierenden lernen die komplexen Zusammenhänge der Quantenphysik.', 'The students are learning the complex relationships of quantum physics.', 'يدرس الطلاب العلاقات المعقدة لفيزياء الكم.', 'Les étudiants apprennent les relations complexes de la physique quantique.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'advanced', 'Aus Fehlern lernt man, sagt man - aber nur, wenn man reflektiert.', 'You learn from mistakes, they say - but only if you reflect.', 'من الأخطاء يتعلم المرء، كما يقال - ولكن فقط إذا تأمل.', 'On apprend de ses erreurs, dit-on - mais seulement si on réfléchit.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'advanced', 'Zeitlebens zu lernen ist in unserer sich schnell wandelnden Gesellschaft unerlässlich.', 'Lifelong learning is essential in our rapidly changing society.', 'التعلم مدى الحياة أمر أساسي في مجتمعنا سريع التغير.', 'Apprendre tout au long de la vie est essentiel dans notre société en évolution rapide.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'Deutsch lernen', 'to learn German', 'تعلم الألمانية', 'apprendre l''allemand');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'aus Fehlern lernen', 'to learn from mistakes', 'التعلم من الأخطاء', 'apprendre de ses erreurs');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'für die Prüfung lernen', 'to study for the exam', 'الدراسة من أجل الامتحان', 'étudier pour l''examen');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'Was lernst du gerade?', 'What are you learning right now?', 'ماذا تتعلم الآن؟', 'Qu''apprends-tu en ce moment ?');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'lernen'), 'Wie lange lernst du schon Deutsch?', 'How long have you been learning German?', 'منذ متى وأنت تتعلم الألمانية؟', 'Depuis combien de temps apprends-tu l''allemand ?');
insert into public.verb_common_mistakes (verb_id, incorrect, correct, explanation, arabic_explanation, french_explanation) values ((select id from public.german_verbs where slug = 'lernen'), 'Ich lerne für Deutsch.', 'Ich lerne Deutsch.', 'lernen takes accusative directly. You don''t need für before the subject.', 'الفعل lernen يأخذ المفعول به مباشرة بدون حرف جر.', 'Le verbe lernen prend l''accusatif directement, sans préposition.');
insert into public.verb_prefix_explanations (verb_id, prefix, explanation, example, english_explanation) values ((select id from public.german_verbs where slug = 'lernen'), 'er-', 'Erlernen implies mastering, achieving complete knowledge through learning.', 'erlernen - to master (a skill)', 'The prefix er- often indicates achieving or reaching a goal through the action.');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'lernen'), 'memory_trick', 'Think learnin'' - like English learning but with the German -en ending.');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'lernen'), 'usage_notes', 'Lernen is used for acquiring knowledge or skills. For to teach, use lehren (jemanden etwas lehren).');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'lernen'), 'common_contexts', 'Used in school contexts (für die Schule lernen), language learning (Deutsch lernen), and professional development (einen Beruf lernen).');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'lernen'), 'formal_vs_informal', 'Lernen is neutral. In formal contexts, prefer sich bilden or sich weiterbilden');

-- Verb: haben (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('haben', 'to have', 'име', 'avoir', 'A1', 'very_common', 'irregular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gehabt', NULL, '/ˈhaːbən/', 'on first syllable', 'haben', '{"besitzen","verfügen"}', '{"nicht haben","entbehren"}', '{"daily_life","family","relationships"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'praesens', 'habe', 'hast', 'hat', 'haben', 'habt', 'haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'praeteritum', 'hatte', 'hattest', 'hatte', 'hatten', 'hattet', 'hatten');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'perfekt', 'habe gehabt', 'hast gehabt', 'hat gehabt', 'haben gehabt', 'habt gehabt', 'haben gehabt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'plusquamperfekt', 'hatte gehabt', 'hattest gehabt', 'hatte gehabt', 'hatten gehabt', 'hattet gehabt', 'hatten gehabt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'futur_i', 'werde haben', 'wirst haben', 'wird haben', 'werden haben', 'werdet haben', 'werden haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'futur_ii', 'werde gehabt haben', 'wirst gehabt haben', 'wird gehabt haben', 'werden gehabt haben', 'werdet gehabt haben', 'werden gehabt haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'konjunktiv_ii', 'würde haben', 'würdest haben', 'würde haben', 'würden haben', 'würdet haben', 'würden haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'imperativ', NULL, 'habe!', NULL, NULL, 'habt!', 'haben Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'haben'), 'passiv', 'werde gehabt', 'wirst gehabt', 'wird gehabt', 'werden gehabt', 'werdet gehabt', 'werden gehabt');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'beginner', 'Ich habe ein Auto.', 'I have a car.', 'لي سيارة.', 'J''ai une voiture.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'beginner', 'Du hast ein Fahrrad.', 'You have a bike.', 'لي دراجة.', 'Tu as un vélo.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'beginner', 'Wir haben eine Familie.', 'We have a family.', 'لدينا عائلة.', 'Nous avons une famille.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'intermediate', 'Ich habe seit drei Jahren ein Handy.', 'I''ve had a cell phone for three years.', 'لدي هاتف خلوي منذ ثلاث سنوات.', 'J''ai un portable depuis trois ans.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'intermediate', 'Mein Bruder hat einen Hund.', 'My brother has a dog.', 'لي أخ كلب.', 'Mon frère a un chien.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'advanced', 'Die Firma hat seit vielen Jahren Erfahrung im Bereich der erneuerbaren Energien.', 'The company has years of experience in the field of renewable energy.', 'الشركة لديها سنوات من الخبرة في مجال الطاقة المتجددة.', 'L''entreprise a des années d''expérience dans le domaine des énergies renouvelables.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'etwas haben', 'to have something', 'име شيء', 'avoir quelque chose');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'jemanden haben', 'to have someone', 'име شخص', 'avoir quelqu''un');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'Was hast du?', 'What do you have?', 'ماذا لديك؟', 'Qu''est-ce que tu as ?');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'haben'), 'Wie viel Geld hast du?', 'How much money do you have?', 'كم tiền لديك؟', 'Combien d''argent as-tu ?');
insert into public.verb_common_mistakes (verb_id, incorrect, correct, explanation, arabic_explanation, french_explanation) values ((select id from public.german_verbs where slug = 'haben'), 'Ich bin reich, ich habe viel Geld.', 'Ich bin reich, ich habe viel Geld.', 'The sentence is correct, but the meaning might be different from what you want to express.', 'الجملة صحيحة، لكن المعنى قد يختلف عما تريد التعبير عنه.', 'La phrase est correcte, mais le sens peut être différent de ce que vous voulez exprimer.');
insert into public.verb_prefix_explanations (verb_id, prefix, explanation, example, english_explanation) values ((select id from public.german_verbs where slug = 'haben'), 'be-', 'To have something, to possess something.', 'besitzen - to possess', 'The prefix be- often indicates to have or possess something.');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'haben'), 'memory_trick', 'Think of having as possessing something.');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'haben'), 'usage_notes', 'Haben is used for possession, but also for relationships and family ties.');
insert into public.verb_learning_tips (verb_id, tip_type, content) values ((select id from public.german_verbs where slug = 'haben'), 'common_contexts', 'Used in everyday conversations about family, relationships, and possessions.');

-- Verb: aufstehen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('aufstehen', 'to get up', 'النهوض', 'se lever', 'A1', 'very_common', 'separable', 'intransitive', 'none', NULL, NULL, false, NULL, 'sein', 'aufgestanden', 'auf', '/ˈaʊ̯fˌʃteːn/', 'on first syllable', 'aufstehen', '{"aufwachen"}', '{"zurücklegen"}', '{"daily_life","morning_routine"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'praesens', 'stehe auf', 'stehst auf', 'steht auf', 'stehen auf', 'steht auf', 'stehen auf');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'praeteritum', 'stand auf', 'standst auf', 'stand auf', 'standen auf', 'standt auf', 'standen auf');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'perfekt', 'bin aufgestanden', 'bist aufgestanden', 'ist aufgestanden', 'sind aufgestanden', 'seid aufgestanden', 'sind aufgestanden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'plusquamperfekt', 'war aufgestanden', 'warst aufgestanden', 'war aufgestanden', 'waren aufgestanden', 'wart aufgestanden', 'waren aufgestanden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'futur_i', 'werde aufstehen', 'wirst aufstehen', 'wird aufstehen', 'werden aufstehen', 'werdet aufstehen', 'werden aufstehen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'futur_ii', 'werde aufgestanden sein', 'wirst aufgestanden sein', 'wird aufgestanden sein', 'werden aufgestanden sein', 'werdet aufgestanden sein', 'werden aufgestandan sein');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'konjunktiv_ii', 'würde aufstehen', 'würdest aufstehen', 'würde aufstehen', 'würden aufstehen', 'würdet aufstehen', 'würden aufstehen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'aufstehen'), 'imperativ', NULL, 'stehe auf!', NULL, NULL, 'steht auf!', 'stehen Sie auf!');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'beginner', 'Ich stehe jeden Morgen früh auf.', 'I get up early every morning.', 'أنهض كل صباح مبكرا.', 'Je me lève tôt chaque matin.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'beginner', 'Du stehst auf, um zur Schule zu gehen.', 'You get up to go to school.', 'تستيقظ لتحضر المدرسة.', 'Tu te lèves pour aller à l''école.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'intermediate', 'Wir stehen früh auf, um zu frühstücken.', 'We get up early to have breakfast.', 'نستيقظ مبكرا لنأكل الإفطار.', 'On se lève tôt pour déjeuner.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'intermediate', 'Er steht spät auf, weil er gestern spät ins Bett gegangen ist.', 'He gets up late because he went to bed late yesterday.', 'يستيقظ متأخرا لأنّه ذهب إلى الفراش متأخرا بالأمس.', 'Il se lève tard parce qu''il est allé au lit tard hier.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'advanced', 'Man muss früh aufstehen, um den Tag richtig zu beginnen.', 'One has to get up early to start the day properly.', 'يتعين الاستيقاظ مبكرا لبدء اليوم بشكل صحيح.', 'Il faut se lever tôt pour commencer la journée correctement.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'früh aufstehen', 'to get up early', 'النهوض مبكرا', 'se lever tôt');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'aufstehen'), 'Wann stehst du normalerweise auf?', 'What time do you usually get up?', 'في أي وقت تستيقظ عادة؟', 'À quelle heure te lèves-tu habituellement ?');
insert into public.verb_common_mistakes (verb_id, incorrect, correct, explanation, arabic_explanation, french_explanation) values ((select id from public.german_verbs where slug = 'aufstehen'), 'Ich stehe auf um 7 Uhr.', 'Ich stehe um 7 Uhr auf.', 'The separable prefix ''auf'' is placed at the end of the sentence in the present tense.', 'الprefix ''auf'' ي đặt في نهایة الجملة في الزمن الحاضر.', 'Le préfixe séparable ''auf'' est placé à la fin de la phrase au présent.');

-- Verb:  essen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
(' essen', 'to eat', 'أكل', 'manger', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gegessen', NULL, '/ˈɛsən/', 'on first syllable', 'essen', '{"fressen"}', '{"fasten"}', '{"food","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'praesens', 'esse', 'isst', 'isst', 'essen', 'esst', 'essen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'praeteritum', 'aß', 'aßt', 'aß', 'aßen', 'aßt', 'aßen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'perfekt', 'habe gegessen', 'hast gegessen', 'hat gegessen', 'haben gegessen', 'habt gegessen', 'haben gegessen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'plusquamperfekt', 'hatte gegessen', 'hattest gegessen', 'hatte gegessen', 'hatten gegessen', 'hattet gegessen', 'hatten gegessen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'futur_i', 'werde essen', 'wirst essen', 'wird essen', 'werden essen', 'werdet essen', 'werden essen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'futur_ii', 'werde gegessen haben', 'wirst gegessen haben', 'wird gegessen haben', 'werden gegessen haben', 'werdet gegessen haben', 'werden gegessen haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'konjunktiv_ii', 'würde essen', 'würdest essen', 'würde essen', 'würden essen', 'würdet essen', 'würden essen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'imperativ', NULL, 'iss!', NULL, NULL, 'esst!', 'essen Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'essen'), 'passiv', 'werde gegessen', 'wirst gegessen', 'wird gegessen', 'werden gegessen', 'werdet gegessen', 'werden gegessen');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'beginner', 'Ich esse ein Sandwich zum Mittag.', 'I eat a sandwich for lunch.', 'آكل شطيرة في الغداء.', 'Je mange un sandwich pour déjeuner.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'beginner', 'Du isst zu viel Schokolade.', 'You eat too much chocolate.', 'تأكل الكثير من الشوكولاتة.', 'Tu manges trop de chocolat.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'intermediate', 'Wir essen immer zusammen.', 'We always eat together.', 'نأكل معا دائما.', 'On mange toujours ensemble.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'intermediate', 'Er isst sehr langsam.', 'He eats very slowly.', 'يأكل ببطء.', 'Il mange très lentement.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'advanced', 'Man sollte drei Mahlzeiten pro Tag essen.', 'One should eat three meals per day.', 'ينبغي للأشخاص تناول ثلاث وجبات يوميا.', 'Il faut manger trois repas par jour.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'zu Mittag essen', 'to eat lunch', 'أكل الغداء', 'manger à midi');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'essen'), 'Was isst du zum Frühstück?', 'What do you eat for breakfast?', 'ماذا تأكل في الإفطار؟', 'Qu''est-ce que tu manges pour petit déjeuner ?');
insert into public.verb_common_mistakes (verb_id, incorrect, correct, explanation, arabic_explanation, french_explanation) values ((select id from public.german_verbs where slug = 'essen'), 'Ich habe gegessen das Sandwich.', 'Ich habe das Sandwich gegessen.', 'The verb ''haben'' is used as an auxiliary verb in the perfect tense and the past participle ''gegessen'' must be placed after the object.', 'يستخدم الفعل ''haben'' كفعل مساعد في الزمن الماضي الم완료 وال participle الماضي ''gegessen'' يجب وضعه بعد المفعول به.', 'Le verbe ''haben'' est utilisé comme verbe auxiliaire au parfait et le participe passé ''gegessen'' doit être placé après l''objet.');

-- Verb: trinken (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('trinken', 'to drink', 'شرب', 'boire', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'getrunken', NULL, '/ˈtʀɪŋkŋ̩/', 'on first syllable', 'trinken', '{"schlucken"}', '{"ausspucken"}', '{"drinks","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'praesens', 'trinke', 'trinkst', 'trinkt', 'trinken', 'trinkt', 'trinken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'praeteritum', 'trank', 'trankst', 'trank', 'tranken', 'trankt', 'tranken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'perfekt', 'habe getrunken', 'hast getrunken', 'hat getrunken', 'haben getrunken', 'habt getrunken', 'haben getrunken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'plusquamperfekt', 'hatte getrunken', 'hattest getrunken', 'hatte getrunken', 'hatten getrunken', 'hattet getrunken', 'hatten getrunken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'futur_i', 'werde trinken', 'wirst trinken', 'wird trinken', 'werden trinken', 'werdet trinken', 'werden trinken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'futur_ii', 'werde getrunken haben', 'wirst getrunken haben', 'wird getrunken haben', 'werden getrunken haben', 'werdet getrunken haben', 'werden getrunken haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'konjunktiv_ii', 'würde trinken', 'würdest trinken', 'würde trinken', 'würden trinken', 'würdet trinken', 'würden trinken');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'imperativ', NULL, 'trinke!', NULL, NULL, 'trinkt!', 'trinken Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'trinken'), 'passiv', 'werde getrunken', 'wirst getrunken', 'wird getrunken', 'werden getrunken', 'werdet getrunken', 'werden getrunken');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'beginner', 'Ich trinke ein Glas Wasser.', 'I drink a glass of water.', 'أشرب كأس ماء.', 'Je bois un verre d''eau.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'beginner', 'Du trinkst zu viel Kaffee.', 'You drink too much coffee.', 'تशرب الكثير من القهوة.', 'Tu bois trop de café.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'intermediate', 'Wir trinken immer Tee zusammen.', 'We always drink tea together.', 'نشرب الشاي معا دائما.', 'On boit toujours du thé ensemble.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'intermediate', 'Er trinkt sehr schnell.', 'He drinks very quickly.', 'يشرب بسرعة.', 'Il boit très rapidement.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'advanced', 'Man sollte viel Wasser trinken.', 'One should drink a lot of water.', 'ينبغي للناس شرب الكثير من الماء.', 'Il faut boire beaucoup d''eau.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'ein Glas Wasser trinken', 'to drink a glass of water', 'شرب كأس ماء', 'boire un verre d''eau');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'trinken'), 'Was trinkst du am liebsten?', 'What do you like to drink?', 'ماذا تشرب؟', 'Qu''est-ce que tu préfères boire ?');
insert into public.verb_common_mistakes (verb_id, incorrect, correct, explanation, arabic_explanation, french_explanation) values ((select id from public.german_verbs where slug = 'trinken'), 'Ich trinke das Glas.', 'Ich trinke aus dem Glas.', 'The preposition ''aus'' is used to indicate the source of the drink.', 'يستخدم حرف الجر ''aus'' لتحديد مصدر المشروب.', 'La préposition ''aus'' est utilisée pour indiquer la source de la boisson.');

-- Verb: sein (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('sein', 'to be', 'يكون', 'être', 'A1', 'very_common', 'auxiliary', 'intransitive', 'none', NULL, NULL, false, NULL, 'sein', 'gewesen', NULL, '/zaɪn/', 'on first syllable', 'sein', '{"existieren","vorhanden sein"}', '{"nicht sein","fehlen"}', '{"family","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'praesens', 'bin', 'bist', 'ist', 'sind', 'seid', 'sind');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'praeteritum', 'war', 'warst', 'war', 'waren', 'wart', 'waren');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'perfekt', 'bin gewesen', 'bist gewesen', 'ist gewesen', 'sind gewesen', 'seid gewesen', 'sind gewesen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'plusquamperfekt', 'war gewesen', 'warst gewesen', 'war gewesen', 'waren gewesen', 'wart gewesen', 'waren gewesen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'futur_i', 'werde sein', 'wirst sein', 'wird sein', 'werden sein', 'werdet sein', 'werden sein');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'futur_ii', 'werde gewesen sein', 'wirst gewesen sein', 'wird gewesen sein', 'werden gewesen sein', 'werdet gewesen sein', 'werden gewesen sein');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'konjunktiv_ii', 'wäre', 'wärst', 'wäre', 'wären', 'wäret', 'wären');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'sein'), 'imperativ', NULL, 'sei', NULL, NULL, 'seid', 'seien Sie');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'sein'), 'beginner', 'Ich bin ein Student.', 'I am a student.', 'أنا طالب.', 'Je suis étudiant.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'sein'), 'intermediate', 'Ich war gestern krank.', 'I was sick yesterday.', 'كنت مريضًا yesterday.', 'J''étais malade hier.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'sein'), 'so sein', 'to be like that', 'يكون كذلك', 'être ainsi');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'sein'), 'Wie alt bist du?', 'How old are you?', 'كم عمرك؟', 'Quel âge as-tu ?');

-- Verb: werden (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('werden', 'to become', 'يسير', 'devenir', 'A1', 'very_common', 'auxiliary', 'intransitive', 'none', NULL, NULL, false, NULL, 'werden', 'geworden', NULL, '/vɛʁdən/', 'on first syllable', 'werden', '{"entwickeln","wachsen"}', '{"bleiben","stagnieren"}', '{"family","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'praesens', 'werde', 'wirst', 'wird', 'werden', 'werdet', 'werden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'praeteritum', 'wurde', 'wurdest', 'wurde', 'wurden', 'wurdet', 'wurden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'perfekt', 'bin geworden', 'bist geworden', 'ist geworden', 'sind geworden', 'seid geworden', 'sind geworden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'plusquamperfekt', 'war geworden', 'warst geworden', 'war geworden', 'waren geworden', 'wart geworden', 'waren geworden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'futur_i', 'werde werden', 'wirst werden', 'wird werden', 'werden werden', 'werdet werden', 'werden werden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'futur_ii', 'werde geworden sein', 'wirst geworden sein', 'wird geworden sein', 'werden geworden sein', 'werdet geworden sein', 'werden geworden sein');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'konjunktiv_ii', 'würde', 'würdest', 'würde', 'würden', 'würdet', 'würden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'werden'), 'imperativ', NULL, 'werde', NULL, NULL, 'werdet', 'werden Sie');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'werden'), 'beginner', 'Ich werde groß.', 'I am getting big.', 'أنا أكبر.', 'Je grandis.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'werden'), 'intermediate', 'Ich werde Arzt.', 'I will be a doctor.', 'سأكون طبيبًا.', 'Je serai médecin.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'werden'), 'werden groß', 'to grow up', 'يبهر', 'grandir');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'werden'), 'Wie alt wirst du?', 'How old will you be?', 'كم سوف يبلغ عمرك؟', 'Quel âge auras-tu ?');

-- Verb: heißen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('heißen', 'to be called', 'يدعى', 's''appeler', 'A1', 'common', 'regular', 'intransitive', 'none', NULL, NULL, false, NULL, 'haben', 'geheißen', NULL, '/haɪsən/', 'on first syllable', 'heissen', '{"genannt werden","bekannt sein als"}', '{"unbekannt sein"," anonym sein"}', '{"family","introduction"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'praesens', 'heiße', 'heißt', 'heißt', 'heißt', 'heißt', 'heißt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'praeteritum', 'hieß', 'hießt', 'hieß', 'hießen', 'hießt', 'hießen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'perfekt', 'habe geheißen', 'hast geheißen', 'hat geheißen', 'haben geheißen', 'habt geheißen', 'haben geheißen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'plusquamperfekt', 'hatte geheißen', 'hattest geheißen', 'hatte geheißen', 'hatten geheißen', 'hattet geheißen', 'hatten geheißen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'futur_i', 'werde heißen', 'wirst heißen', 'wird heißen', 'werden heißen', 'werdet heißen', 'werden heißen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'futur_ii', 'werde geheißen haben', 'wirst geheißen haben', 'wird geheißen haben', 'werden geheißen haben', 'werdet geheißen haben', 'werden geheißen haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'konjunktiv_ii', 'hieße', 'hießest', 'hieße', 'hießen', 'hießet', 'hießen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'heissen'), 'imperativ', NULL, 'heiße', NULL, NULL, 'heißt', 'heißt');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'heissen'), 'beginner', 'Ich heiße Hans.', 'My name is Hans.', 'اسمي هانس.', 'Je m''appelle Hans.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'heissen'), 'intermediate', 'Wie heißt du?', 'What''s your name?', 'ما اسمك؟', 'Comment t''appelles-tu ?');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'heissen'), 'sich heißen', 'to be called', 'يدعى', 's''appeler');
insert into public.verb_typical_questions (verb_id, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'heissen'), 'Wie heißt du?', 'What''s your name?', 'ما اسمك؟', 'Comment t''appelles-tu ?');

-- Verb: kaufen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('kaufen', 'to buy', 'يشتري', 'acheter', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gekauft', NULL, '/ˈkaʊ̯fən/', 'on first syllable', 'kaufen', '{"einkaufen","besorgen"}', '{"verkaufen","abgeben"}', '{"shopping","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'praesens', 'kaufe', 'kaufst', 'kauft', 'kaufen', 'kauft', 'kaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'praeteritum', 'kaufte', 'kaufest', 'kaufte', 'kauften', 'kauftet', 'kauften');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'perfekt', 'habe gekauft', 'hast gekauft', 'hat gekauft', 'haben gekauft', 'habt gekauft', 'haben gekauft');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'plusquamperfekt', 'hatte gekauft', 'hattest gekauft', 'hatte gekauft', 'hatten gekauft', 'hattet gekauft', 'hatten gekauft');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'futur_i', 'werde kaufen', 'wirst kaufen', 'wird kaufen', 'werden kaufen', 'werdet kaufen', 'werden kaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'futur_ii', 'werde gekauft haben', 'wirst gekauft haben', 'wird gekauft haben', 'werden gekauft haben', 'werdet gekauft haben', 'werden gekauft haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'konjunktiv_ii', 'würde kaufen', 'würdest kaufen', 'würde kaufen', 'würden kaufen', 'würdet kaufen', 'würden kaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'imperativ', NULL, 'kaufe!', NULL, NULL, 'kauft!', 'kaufen Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'kaufen'), 'passiv', 'werde gekauft', 'wirst gekauft', 'wird gekauft', 'werden gekauft', 'werdet gekauft', 'werden gekauft');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'kaufen'), 'beginner', 'Ich kaufe ein neues Handy.', 'I am buying a new cell phone.', 'أنا أشتري هاتفًا جديدًا.', 'J''achète un nouveau téléphone portable.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'kaufen'), 'intermediate', 'Meine Mutter kauft immer bei dem gleichen Laden ein.', 'My mother always shops at the same store.', 'أمي تشتري دائمًا من المتجر نفسه.', 'Ma mère achète toujours chez le même magasin.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'kaufen'), 'etwas kaufen', 'to buy something', 'يشتري شيئًا', 'acheter quelque chose');

-- Verb: verkaufen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('verkaufen', 'to sell', 'يباع', 'vendre', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'verkauft', NULL, '/fɛʁˈkaʊ̯fən/', 'on first syllable', 'verkaufen', '{"anbieten","feilbieten"}', '{"kaufen","erwerben"}', '{"shopping","business"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'praesens', 'verkaufe', 'verkaufst', 'verkauft', 'verkaufen', 'verkauft', 'verkaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'praeteritum', 'verkaufte', 'verkaufest', 'verkaufte', 'verkauften', 'verkauftet', 'verkauften');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'perfekt', 'habe verkauft', 'hast verkauft', 'hat verkauft', 'haben verkauft', 'habt verkauft', 'haben verkauft');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'plusquamperfekt', 'hatte verkauft', 'hattest verkauft', 'hatte verkauft', 'hatten verkauft', 'hattet verkauft', 'hatten verkauft');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'futur_i', 'werde verkaufen', 'wirst verkaufen', 'wird verkaufen', 'werden verkaufen', 'werdet verkaufen', 'werden verkaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'futur_ii', 'werde verkauft haben', 'wirst verkauft haben', 'wird verkauft haben', 'werden verkauft haben', 'werdet verkauft haben', 'werden verkauft haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'konjunktiv_ii', 'würde verkaufen', 'würdest verkaufen', 'würde verkaufen', 'würden verkaufen', 'würdet verkaufen', 'würden verkaufen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'imperativ', NULL, 'verkaufe!', NULL, NULL, 'verkauft!', 'verkaufen Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verkaufen'), 'passiv', 'werde verkauft', 'wirst verkauft', 'wird verkauft', 'werden verkauft', 'werdet verkauft', 'werden verkauft');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'verkaufen'), 'beginner', 'Ich verkaufe mein altes Auto.', 'I am selling my old car.', 'أنا أ bán سيارتي القديمة.', 'Je vends ma vieille voiture.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'verkaufen'), 'intermediate', 'Die Firma verkauft viele Produkte.', 'The company sells many products.', 'تبيع الشركة العديد من المنتجات.', 'L''entreprise vend beaucoup de produits.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'verkaufen'), 'etwas verkaufen', 'to sell something', 'يباع شيئًا', 'vendre quelque chose');

-- Verb: zahlen (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('zahlen', 'to pay', 'يدفع', 'payer', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gezahlt', NULL, '/ˈtsaːlən/', 'on first syllable', 'zahlen', '{"bezahlen","entrichten"}', '{"bekommen","erhalten"}', '{"shopping","finance"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'praesens', 'zahle', 'zahlst', 'zahlt', 'zahlen', 'zahlt', 'zahlen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'praeteritum', 'zahlte', 'zahltest', 'zahlte', 'zahlten', 'zahtet', 'zahlten');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'perfekt', 'habe gezahlt', 'hast gezahlt', 'hat gezahlt', 'haben gezahlt', 'habt gezahlt', 'haben gezahlt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'plusquamperfekt', 'hatte gezahlt', 'hattest gezahlt', 'hatte gezahlt', 'hatten gezahlt', 'hattet gezahlt', 'hatten gezahlt');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'futur_i', 'werde zahlen', 'wirst zahlen', 'wird zahlen', 'werden zahlen', 'werdet zahlen', 'werden zahlen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'futur_ii', 'werde gezahlt haben', 'wirst gezahlt haben', 'wird gezahlt haben', 'werden gezahlt haben', 'werdet gezahlt haben', 'werden gezahlt haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'konjunktiv_ii', 'würde zahlen', 'würdest zahlen', 'würde zahlen', 'würden zahlen', 'würdet zahlen', 'würden zahlen');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'imperativ', NULL, 'zahle!', NULL, NULL, 'zahlt!', 'zahlen Sie!');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'zahlen'), 'passiv', 'werde gezahlt', 'wirst gezahlt', 'wird gezahlt', 'werden gezahlt', 'werdet gezahlt', 'werden gezahlt');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'zahlen'), 'beginner', 'Ich zahle mit meiner Kreditkarte.', 'I pay with my credit card.', 'أدفع ببطاقتي الائتمانية.', 'Je paie avec ma carte de crédit.');
insert into public.verb_examples (verb_id, difficulty, german, english, arabic, french) values ((select id from public.german_verbs where slug = 'zahlen'), 'intermediate', 'Die Firma zahlt ihre Mitarbeiter gut.', 'The company pays its employees well.', 'تदفع الشركة موظفيها جيدًا.', 'L''entreprise paie bien ses employés.');
insert into public.verb_collocations (verb_id, collocation, english, arabic, french) values ((select id from public.german_verbs where slug = 'zahlen'), 'zahlen für', 'to pay for', 'يدفع من أجل', 'payer pour');

-- Verb: verwenden (A1)
insert into public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, stress, slug, synonyms, antonyms, tags) values
('verwenden', 'to use', 'يستخدم', 'utiliser', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'verwendet', NULL, '/fɛʁˈvɛndən/', 'on first syllable', 'verwenden', '{"anwenden","benutzen"}', '{"sparen","aufheben"}', '{"shopping","daily_life"}');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'praesens', 'verwende', 'verwendest', 'verwendet', 'verwenden', 'verwendet', 'verwenden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'praeteritum', 'verwendete', 'verwendetest', 'verwendete', 'verwendeten', 'verwendetet', 'verwendeten');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'perfekt', 'habe verwendet', 'hast verwendet', 'hat verwendet', 'haben verwendet', 'habt verwendet', 'haben verwendet');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'plusquamperfekt', 'hatte verwendet', 'hattest verwendet', 'hatte verwendet', 'hatten verwendet', 'hattet verwendet', 'hatten verwendet');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'futur_i', 'werde verwenden', 'wirst verwenden', 'wird verwenden', 'werden verwenden', 'werdet verwenden', 'werden verwenden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'futur_ii', 'werde verwendet haben', 'wirst verwendet haben', 'wird verwendet haben', 'werden verwendet haben', 'werdet verwendet haben', 'werden verwendet haben');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'konjunktiv_ii', 'würde verwenden', 'würdest verwenden', 'würde verwenden', 'würden verwenden', 'würdet verwenden', 'würden verwenden');
insert into public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) values ((select id from public.german_verbs where slug = 'verwenden'), 'imperativ', NULL, 'verwende!', NULL, NULL, 'verwendet!', 'verwenden Sie!');

