-- German Verbs Seed v2 (generated)
-- Run after migration 00031_german_verbs.sql

-- Verb: stehen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('stehen', 'to stand', 'الواقف', 'se tenir debout', 'A1', 'very_common', 'regular', 'intransitive', 'none', NULL, NULL, false, NULL, 'sein', 'gestanden', NULL, '/stehən/', 'stehen', '{"sich befinden"}', '{"sitzen"}', '{"position","location"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'praesens', 'stehe', 'stehst', 'steht', 'stehen', 'steht', 'stehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'praeteritum', 'stand', 'standst', 'stand', 'standen', 'standet', 'standen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'perfekt', 'bin gestanden', 'bist gestanden', 'ist gestanden', 'sind gestanden', 'seid gestanden', 'sind gestanden') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'plusquamperfekt', 'war gestanden', 'warst gestanden', 'war gestanden', 'waren gestanden', 'wart gestanden', 'waren gestanden') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'futur_i', 'werde stehen', 'wirst stehen', 'wird stehen', 'werden stehen', 'werdet stehen', 'werden stehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'futur_ii', 'werde gestanden sein', 'wirst gestanden sein', 'wird gestanden sein', 'werden gestanden sein', 'werdet gestanden sein', 'werden gestanden sein') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'konjunktiv_ii', 'würde stehen', 'würdest stehen', 'würde stehen', 'würden stehen', 'würdet stehen', 'würden stehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'imperativ', NULL, 'steh', NULL, NULL, 'steht', 'stehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'beginner', 'Ich stehe hier.', 'I am standing here.', 'أنا واقف هنا', 'Je suis debout ici.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'beginner', 'Die Statue steht im Park.', 'The statue is standing in the park.', 'التمثال واقف في الحديقة', 'La statue se trouve dans le parc.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'beginner', 'Die Menschen stehen in der Schlange.', 'The people are standing in line.', 'الناس واقفون في الصف', 'Les gens sont debout dans la ligne.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'stehen bleiben', 'to remain standing', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'stehen'), 'stehen bleiben lassen', 'to leave standing', NULL, NULL);

-- Verb: sprechen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('sprechen', 'to speak', 'يتكلم', 'parler', 'A1', 'very_common', 'irregular', 'intransitive', 'none', NULL, NULL, false, NULL, 'haben', 'gesprochen', NULL, '/sprechən/', 'sprechen', '{"reden","diskutieren"}', '{}', '{"communication","language"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'praesens', 'spreche', 'sprichst', 'spricht', 'sprechen', 'sprecht', 'sprechen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'praeteritum', 'sprach', 'sprachst', 'sprach', 'sprachen', 'spracht', 'sprachen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'perfekt', 'habe gesprochen', 'hast gesprochen', 'hat gesprochen', 'haben gesprochen', 'habt gesprochen', 'haben gesprochen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'plusquamperfekt', 'hatte gesprochen', 'hattest gesprochen', 'hatte gesprochen', 'hatten gesprochen', 'hattet gesprochen', 'hatten gesprochen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'futur_i', 'werde sprechen', 'wirst sprechen', 'wird sprechen', 'werden sprechen', 'werdet sprechen', 'werden sprechen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'futur_ii', 'werde gesprochen haben', 'wirst gesprochen haben', 'wird gesprochen haben', 'werden gesprochen haben', 'werdet gesprochen haben', 'werden gesprochen haben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'konjunktiv_ii', 'würde sprechen', 'würdest sprechen', 'würde sprechen', 'würden sprechen', 'würdet sprechen', 'würden sprechen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'imperativ', NULL, 'sprich', NULL, NULL, 'sprecht', 'sprechen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'beginner', 'Ich spreche Deutsch.', 'I speak German.', 'أنا أتحدث الألمانية', 'Je parle allemand.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'beginner', 'Die Frau spricht mit ihrem Freund.', 'The woman is talking to her friend.', 'المرأة تتكلم مع صديقها', 'La femme parle avec son ami.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'beginner', 'Die Menschen sprechen verschiedene Sprachen.', 'The people speak different languages.', 'الناس يتكلمون لغات مختلفة', 'Les gens parlent différentes langues.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'über etwas sprechen', 'to talk about something', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sprechen'), 'mit jemandem sprechen', 'to speak with someone', NULL, NULL);

-- Verb: schreiben (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('schreiben', 'to write', 'يكتب', 'écrire', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'geschrieben', NULL, '/schreibən/', 'schreiben', '{"tippen","diktieren"}', '{}', '{"writing","literature"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'praesens', 'schreibe', 'schreibst', 'schreibt', 'schreiben', 'schreibt', 'schreiben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'praeteritum', 'schrieb', 'schriebst', 'schrieb', 'schrieben', 'schriebt', 'schrieben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'perfekt', 'habe geschrieben', 'hast geschrieben', 'hat geschrieben', 'haben geschrieben', 'habt geschrieben', 'haben geschrieben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'plusquamperfekt', 'hatte geschrieben', 'hattest geschrieben', 'hatte geschrieben', 'hatten geschrieben', 'hattet geschrieben', 'hatten geschrieben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'futur_i', 'werde schreiben', 'wirst schreiben', 'wird schreiben', 'werden schreiben', 'werdet schreiben', 'werden schreiben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'futur_ii', 'werde geschrieben haben', 'wirst geschrieben haben', 'wird geschrieben haben', 'werden geschrieben haben', 'werdet geschrieben haben', 'werden geschrieben haben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'konjunktiv_ii', 'würde schreiben', 'würdest schreiben', 'würde schreiben', 'würden schreiben', 'würdet schreiben', 'würden schreiben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'imperativ', NULL, 'schreib', NULL, NULL, 'schreibt', 'schreiben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'beginner', 'Ich schreibe einen Brief.', 'I am writing a letter.', 'أنا أكتب رسالة', 'Je suis en train d''écrire une lettre.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'beginner', 'Die Frau schreibt ein Buch.', 'The woman is writing a book.', 'المرأة تكتب كتاب', 'La femme écrit un livre.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'beginner', 'Die Menschen schreiben E-Mails.', 'The people are writing emails.', 'الناس يكتبون رسائل إلكترونية', 'Les gens écrivent des e-mails.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'etwas schreiben', 'to write something', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'schreiben'), 'an jemanden schreiben', 'to write to someone', NULL, NULL);

-- Verb: lesen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('lesen', 'to read', 'يقرأ', 'lire', 'A1', 'very_common', 'regular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gelesen', NULL, '/lesən/', 'lesen', '{"studieren","durchlesen"}', '{}', '{"reading","literature"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'praesens', 'lese', 'liest', 'liest', 'lesen', 'lest', 'lesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'praeteritum', 'las', 'last', 'las', 'lasen', 'last', 'lasen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'perfekt', 'habe gelesen', 'hast gelesen', 'hat gelesen', 'haben gelesen', 'habt gelesen', 'haben gelesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'plusquamperfekt', 'hatte gelesen', 'hattest gelesen', 'hatte gelesen', 'hatten gelesen', 'hattet gelesen', 'hatten gelesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'futur_i', 'werde lesen', 'wirst lesen', 'wird lesen', 'werden lesen', 'werdet lesen', 'werden lesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'futur_ii', 'werde gelesen haben', 'wirst gelesen haben', 'wird gelesen haben', 'werden gelesen haben', 'werdet gelesen haben', 'werden gelesen haben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'konjunktiv_ii', 'würde lesen', 'würdest lesen', 'würde lesen', 'würden lesen', 'würdet lesen', 'würden lesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'imperativ', NULL, 'lie', NULL, NULL, 'lest', 'lesen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'beginner', 'Ich lese ein Buch.', 'I am reading a book.', 'أنا أقرأ كتاب', 'Je suis en train de lire un livre.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'beginner', 'Die Frau liest eine Zeitschrift.', 'The woman is reading a magazine.', 'المرأة تقرأ مجلة', 'La femme lit un magazine.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'beginner', 'Die Menschen lesen Nachrichten im Internet.', 'The people are reading news on the internet.', 'الناس يقرؤون أخبار على الإنترنت', 'Les gens lisent des nouvelles sur internet.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'etwas lesen', 'to read something', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'lesen'), 'in etwas lesen', 'to read in something', NULL, NULL);

-- Verb: hören (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('hören', 'to hear', 'يسمع', 'entendre', 'A1', 'very_common', 'irregular', 'intransitive', 'none', NULL, NULL, false, NULL, 'haben', 'gehört', NULL, '/hörən/', 'hoeren', '{"lauschen","zuhören"}', '{}', '{"hearing","sound"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'praesens', 'höre', 'hörst', 'hört', 'hören', 'hört', 'hören') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'praeteritum', 'hörte', 'hörtest', 'hörte', 'hörten', 'hörtet', 'hörten') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'perfekt', 'habe gehört', 'hast gehört', 'hat gehört', 'haben gehört', 'habt gehört', 'haben gehört') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'plusquamperfekt', 'hatte gehört', 'hattest gehört', 'hatte gehört', 'hatten gehört', 'hattet gehört', 'hatten gehört') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'futur_i', 'werde hören', 'wirst hören', 'wird hören', 'werden hören', 'werdet hören', 'werden hören') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'futur_ii', 'werde gehört haben', 'wirst gehört haben', 'wird gehört haben', 'werden gehört haben', 'werdet gehört haben', 'werden gehört haben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'konjunktiv_ii', 'würde hören', 'würdest hören', 'würde hören', 'würden hören', 'würdet hören', 'würden hören') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'imperativ', NULL, 'hör', NULL, NULL, 'hört', 'hören') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'beginner', 'Ich höre Musik.', 'I am listening to music.', 'أنا أسمع الموسيقى', 'Je suis en train d''écouter de la musique.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'beginner', 'Die Frau hört einem Mann zu.', 'The woman is listening to a man.', 'المرأة تسمع رجل', 'La femme écoute un homme.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'beginner', 'Die Menschen hören Nachrichten im Radio.', 'The people are listening to news on the radio.', 'الناس يسمعون أخبار على الراديو', 'Les gens écoutent des nouvelles à la radio.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'auf etwas hören', 'to listen to something', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'hoeren'), 'jemandem zuhören', 'to listen to someone', NULL, NULL);

-- Verb: sehen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('sehen', 'to see', 'يرى', 'voir', 'A1', 'very_common', 'irregular', 'transitive', 'akkusativ', NULL, NULL, false, NULL, 'haben', 'gesehen', NULL, '/sehən/', 'sehen', '{"blicken","schauen"}', '{}', '{"vision","sight"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'praesens', 'sehe', 'siehst', 'sieht', 'sehen', 'seht', 'sehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'praeteritum', 'sah', 'sahst', 'sah', 'sahen', 'saht', 'sahen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'perfekt', 'habe gesehen', 'hast gesehen', 'hat gesehen', 'haben gesehen', 'habt gesehen', 'haben gesehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'plusquamperfekt', 'hatte gesehen', 'hattest gesehen', 'hatte gesehen', 'hatten gesehen', 'hattet gesehen', 'hatten gesehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'futur_i', 'werde sehen', 'wirst sehen', 'wird sehen', 'werden sehen', 'werdet sehen', 'werden sehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'futur_ii', 'werde gesehen haben', 'wirst gesehen haben', 'wird gesehen haben', 'werden gesehen haben', 'werdet gesehen haben', 'werden gesehen haben') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'konjunktiv_ii', 'würde sehen', 'würdest sehen', 'würde sehen', 'würden sehen', 'würdet sehen', 'würden sehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'imperativ', NULL, 'sieh', NULL, NULL, 'seht', 'sehen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'beginner', 'Ich sehe einen Film.', 'I am watching a movie.', 'أنا أرى فيلم', 'Je regarde un film.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'beginner', 'Die Frau sieht einen Mann.', 'The woman is seeing a man.', 'المرأة ترى رجل', 'La femme voit un homme.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'beginner', 'Die Menschen sehen eine Ausstellung.', 'The people are seeing an exhibition.', 'الناس يرون معرض', 'Les gens visitent une exposition.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'etwas sehen', 'to see something', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'sehen'), 'jemanden sehen', 'to see someone', NULL, NULL);

-- Verb: laufen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('laufen', 'to run', 'يركض', 'courir', 'A1', 'common', 'irregular', 'intransitive', 'none', NULL, NULL, false, NULL, 'sein', 'gelaufen', NULL, '/laufən/', 'laufen', '{"rennen","joggen"}', '{}', '{"running","sports"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'praesens', 'laufe', 'laufst', 'lauft', 'laufen', 'lauft', 'laufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'praeteritum', 'lief', 'liefst', 'lief', 'liefen', 'lieft', 'liefen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'perfekt', 'bin gelaufen', 'bist gelaufen', 'ist gelaufen', 'sind gelaufen', 'seid gelaufen', 'sind gelaufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'plusquamperfekt', 'war gelaufen', 'warst gelaufen', 'war gelaufen', 'waren gelaufen', 'wart gelaufen', 'waren gelaufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'futur_i', 'werde laufen', 'wirst laufen', 'wird laufen', 'werden laufen', 'werdet laufen', 'werden laufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'futur_ii', 'werde gelaufen sein', 'wirst gelaufen sein', 'wird gelaufen sein', 'werden gelaufen sein', 'werdet gelaufen sein', 'werden gelaufen sein') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'konjunktiv_ii', 'würde laufen', 'würdest laufen', 'würde laufen', 'würden laufen', 'würdet laufen', 'würden laufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'imperativ', NULL, 'lauf', NULL, NULL, 'lauft', 'laufen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'beginner', 'Ich laufe im Park.', 'I am running in the park.', 'أنا أركض في الحديقة', 'Je cours dans le parc.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'beginner', 'Die Frau läuft zum Bus.', 'The woman is running to the bus.', 'المرأة تركض إلى الحافلة', 'La femme court vers le bus.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'beginner', 'Die Menschen laufen im Marathon.', 'The people are running in the marathon.', 'الناس يركضون في الماراثون', 'Les gens courent dans le marathon.');
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'um sein Leben laufen', 'to run for one''s life', NULL, NULL);
INSERT INTO public.verb_collocations (verb_id, collocation, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'laufen'), 'für etwas laufen', 'to run for something', NULL, NULL);

-- Verb: springen (A1)
INSERT INTO public.german_verbs (infinitive, english_translation, arabic_translation, french_translation, cefr_level, frequency, verb_type, transitivity, object_case, preposition, preposition_case, is_reflexive, reflexive_pronoun, auxiliary, partizip_2, separable_prefix, ipa, slug, synonyms, antonyms, tags) VALUES
('springen', 'to jump', 'يقفز', 'sauter', 'A1', 'common', 'irregular', 'intransitive', 'none', NULL, NULL, false, NULL, 'sein', 'gesprungen', NULL, '/springən/', 'springen', '{}', '{}', '{"jumping","movement"}') on conflict (slug) do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'praesens', 'springe', 'springst', 'springt', 'springen', 'springt', 'springen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'praeteritum', 'sprang', 'sprangst', 'sprang', 'sprangen', 'sprangt', 'sprangen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'perfekt', 'bin gesprungen', 'bist gesprungen', 'ist gesprungen', 'sind gesprungen', 'seid gesprungen', 'sind gesprungen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'plusquamperfekt', 'war gesprungen', 'warst gesprungen', 'war gesprungen', 'waren gesprungen', 'wart gesprungen', 'waren gesprungen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'futur_i', 'werde springen', 'wirst springen', 'wird springen', 'werden springen', 'werdet springen', 'werden springen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'futur_ii', 'werde gesprungen sein', 'wirst gesprungen sein', 'wird gesprungen sein', 'werden gesprungen sein', 'werdet gesprungen sein', 'werden gesprungen sein') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'konjunktiv_ii', 'würde springen', 'würdest springen', 'würde springen', 'würden springen', 'würdet springen', 'würden springen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_conjugations (verb_id, tense, ich, du, er_sie_es, wir, ihr, Sie) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'imperativ', NULL, 'spring', NULL, NULL, 'springt', 'springen') on conflict on constraint verb_conjugations_verb_id_tense_key do nothing;
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'beginner', 'Ich springe über einen Graben.', 'I am jumping over a ditch.', 'أنا أقفز فوق خندق', 'Je saute par-dessus un fossé.');
INSERT INTO public.verb_examples (verb_id, difficulty, german, english, arabic, french) VALUES ((SELECT id FROM public.german_verbs WHERE slug = 'springen'), 'beginner', 'Die Frau springt in den Pool.', 'The woman is jumping into the pool.', 'المرأة تقفز في المسبح', 'La femme saute dans la piscine.');

